// Code generated by andurel; DO NOT EDIT.

export const routes = {
  confirmationCreate: () => '/users/confirmation',
  confirmationNew: () => '/users/confirmation/new',
  homePage: () => '/',
  passwordCreate: () => '/users/password',
  passwordEdit: (token: string) => `/users/password/${token}/edit`,
  passwordNew: () => '/users/password/new',
  passwordUpdate: () => '/users/password',
  registrationCreate: () => '/users',
  registrationNew: () => '/users/sign-up',
  sessionCreate: () => '/users/sign-in',
  sessionDestroy: () => '/users/sign-out',
  sessionNew: () => '/users/sign-in',
}
