api = "0.12"

[buildpack]
id = "com.deploycrate.node-assets"
name = "DeployCrate Node Assets"
version = "0.5.0"

[metadata]
default-npm-version = "11.5.2"
default-pnpm-version = "11.18.0"
default-bun-version = "1.2.20"
default-yarn-version = "1.22.22"

[[targets]]
os = "linux"
