// Package inertia provides Inertia.js rendering helpers.
// Code generated by andurel v1.5.2; DO NOT EDIT.
package inertia

import (
	"encoding/json"
	"fmt"
	"html/template"
	"strings"

	"deploycrate-ce/internal/server"
)

type viteTags struct {
	ViteHead template.HTML
	ViteBody template.HTML
}

type viteManifestEntry struct {
	File    string   `json:"file"`
	CSS     []string `json:"css"`
	Src     string   `json:"src"`
	IsEntry bool     `json:"isEntry"`
}

func initVite(env, buildPath string, manifestData []byte) (*viteTags, error) {
	if env != server.ProdEnvironment {
		tags := &viteTags{
			ViteHead: template.HTML(`<script type="module" src="http://localhost:5173/assets/dist/@vite/client"></script>`),
		}

		tags.ViteBody = template.HTML(`<script type="module" src="http://localhost:5173/assets/dist/resources/js/app.ts"></script>`)

		return tags, nil
	}

	var manifest map[string]viteManifestEntry
	if err := json.Unmarshal(manifestData, &manifest); err != nil {
		return nil, fmt.Errorf("vite: parse manifest: %w", err)
	}

	entry, ok := manifest["resources/js/app.ts"]
	if !ok {
		return nil, fmt.Errorf("vite: entry point not found in manifest")
	}

	tags := &viteTags{}
	viteBuildPrefix := strings.TrimSuffix(buildPath, "*")
	for _, css := range entry.CSS {
		tags.ViteHead += template.HTML(`<link rel="stylesheet" href="` + viteBuildPrefix + css + `">`)
	}
	tags.ViteBody = template.HTML(`<script type="module" src="` + viteBuildPrefix + entry.File + `"></script>`)

	return tags, nil
}
