package factories

import (
	"context"
	"database/sql"
	"deploycrate-ce/internal/storage"
	"deploycrate-ce/models"
	"fmt"
	"time"

	"github.com/go-faker/faker/v4"
	"github.com/google/uuid"
)

// Factory declarations below are generated by Andurel.

type ApplicationFactory struct {
	models.ApplicationEntity
}

type ApplicationOption func(*ApplicationFactory)

func BuildApplication(opts ...ApplicationOption) models.ApplicationEntity {
	f := &ApplicationFactory{
		ApplicationEntity: models.ApplicationEntity{
			Name:       faker.Word(),
			Slug:       faker.Word(),
			ArchivedAt: sql.NullTime{Time: time.Now(), Valid: true},
		},
	}

	for _, opt := range opts {
		opt(f)
	}

	return f.ApplicationEntity
}

func CreateApplication(
	ctx context.Context,
	exec storage.Executor,
	opts ...ApplicationOption,
) (models.ApplicationEntity, error) {
	built := BuildApplication(opts...)

	entity := models.ApplicationEntity{
		ID:                    uuid.New(),
		CreatedAt:             time.Now(),
		UpdatedAt:             time.Now(),
		Name:                  built.Name,
		Slug:                  built.Slug,
		BasicAuthUsername:     built.BasicAuthUsername,
		BasicAuthPasswordHash: built.BasicAuthPasswordHash,
		ArchivedAt:            built.ArchivedAt,
	}

	if err := exec.NewInsert().Model(&entity).Returning("*").Scan(ctx); err != nil {
		return models.ApplicationEntity{}, err
	}

	return entity, nil
}

func CreateApplications(
	ctx context.Context,
	exec storage.Executor,
	count int,
	opts ...ApplicationOption,
) ([]models.ApplicationEntity, error) {
	applications := make([]models.ApplicationEntity, 0, count)

	for i := range count {
		entity, err := CreateApplication(ctx, exec, opts...)
		if err != nil {
			return nil, fmt.Errorf("failed to create application %d: %w", i+1, err)
		}
		applications = append(applications, entity)
	}

	return applications, nil
}

func WithApplicationsName(value string) ApplicationOption {
	return func(f *ApplicationFactory) {
		f.ApplicationEntity.Name = value
	}
}

func WithApplicationsSlug(value string) ApplicationOption {
	return func(f *ApplicationFactory) {
		f.ApplicationEntity.Slug = value
	}
}

func WithApplicationsArchivedAt(value sql.NullTime) ApplicationOption {
	return func(f *ApplicationFactory) {
		f.ApplicationEntity.ArchivedAt = value
	}
}

func WithApplicationsBasicAuthUsername(value string) ApplicationOption {
	return func(f *ApplicationFactory) {
		f.ApplicationEntity.BasicAuthUsername = value
	}
}

func WithApplicationsBasicAuthPasswordHash(value string) ApplicationOption {
	return func(f *ApplicationFactory) {
		f.ApplicationEntity.BasicAuthPasswordHash = value
	}
}
