package factories

import (
	"context"
	"database/sql"
	"deploycrate-ce/internal/storage"
	"deploycrate-ce/models"
	"fmt"
	"time"

	"github.com/go-faker/faker/v4"
	"github.com/google/uuid"
)

// Factory declarations below are generated by Andurel.

type BackupDestinationFactory struct {
	models.BackupDestinationEntity
}

type BackupDestinationOption func(*BackupDestinationFactory)

func BuildBackupDestination(credentialID uuid.UUID, opts ...BackupDestinationOption) models.BackupDestinationEntity {
	f := &BackupDestinationFactory{
		BackupDestinationEntity: models.BackupDestinationEntity{
			Name:           faker.Word(),
			CredentialID:   credentialID,
			Provider:       faker.Word(),
			Endpoint:       sql.NullString{String: faker.Word(), Valid: true},
			Region:         sql.NullString{String: faker.Word(), Valid: true},
			Bucket:         faker.Word(),
			Prefix:         sql.NullString{String: faker.Word(), Valid: true},
			ForcePathStyle: randomBool(),
			ArchivedAt:     sql.NullTime{Time: time.Now(), Valid: true},
		},
	}

	for _, opt := range opts {
		opt(f)
	}

	return f.BackupDestinationEntity
}

func CreateBackupDestination(ctx context.Context, exec storage.Executor, credentialID uuid.UUID, opts ...BackupDestinationOption) (models.BackupDestinationEntity, error) {
	built := BuildBackupDestination(credentialID, opts...)

	entity := models.BackupDestinationEntity{
		ID:             uuid.New(),
		CreatedAt:      time.Now(),
		UpdatedAt:      time.Now(),
		Name:           built.Name,
		CredentialID:   built.CredentialID,
		Provider:       built.Provider,
		Endpoint:       built.Endpoint,
		Region:         built.Region,
		Bucket:         built.Bucket,
		Prefix:         built.Prefix,
		ForcePathStyle: built.ForcePathStyle,
		ArchivedAt:     built.ArchivedAt,
	}

	if err := exec.NewInsert().Model(&entity).Returning("*").Scan(ctx); err != nil {
		return models.BackupDestinationEntity{}, err
	}

	return entity, nil
}

func CreateBackupDestinations(ctx context.Context, exec storage.Executor, credentialID uuid.UUID, count int, opts ...BackupDestinationOption) ([]models.BackupDestinationEntity, error) {
	backupdestinations := make([]models.BackupDestinationEntity, 0, count)

	for i := range count {
		entity, err := CreateBackupDestination(ctx, exec, credentialID, opts...)
		if err != nil {
			return nil, fmt.Errorf("failed to create backupdestination %d: %w", i+1, err)
		}
		backupdestinations = append(backupdestinations, entity)
	}

	return backupdestinations, nil
}

func WithBackupDestinationsName(value string) BackupDestinationOption {
	return func(f *BackupDestinationFactory) {
		f.BackupDestinationEntity.Name = value
	}
}

func WithBackupDestinationsCredentialID(value uuid.UUID) BackupDestinationOption {
	return func(f *BackupDestinationFactory) {
		f.BackupDestinationEntity.CredentialID = value
	}
}

func WithBackupDestinationsProvider(value string) BackupDestinationOption {
	return func(f *BackupDestinationFactory) {
		f.BackupDestinationEntity.Provider = value
	}
}

func WithBackupDestinationsEndpoint(value sql.NullString) BackupDestinationOption {
	return func(f *BackupDestinationFactory) {
		f.BackupDestinationEntity.Endpoint = value
	}
}

func WithBackupDestinationsRegion(value sql.NullString) BackupDestinationOption {
	return func(f *BackupDestinationFactory) {
		f.BackupDestinationEntity.Region = value
	}
}

func WithBackupDestinationsBucket(value string) BackupDestinationOption {
	return func(f *BackupDestinationFactory) {
		f.BackupDestinationEntity.Bucket = value
	}
}

func WithBackupDestinationsPrefix(value sql.NullString) BackupDestinationOption {
	return func(f *BackupDestinationFactory) {
		f.BackupDestinationEntity.Prefix = value
	}
}

func WithBackupDestinationsForcePathStyle(value bool) BackupDestinationOption {
	return func(f *BackupDestinationFactory) {
		f.BackupDestinationEntity.ForcePathStyle = value
	}
}

func WithBackupDestinationsArchivedAt(value sql.NullTime) BackupDestinationOption {
	return func(f *BackupDestinationFactory) {
		f.BackupDestinationEntity.ArchivedAt = value
	}
}
