package factories

import (
	"context"
	"database/sql"
	"deploycrate-ce/internal/storage"
	"deploycrate-ce/models"
	"encoding/json"
	"fmt"
	"time"

	"github.com/go-faker/faker/v4"
	"github.com/google/uuid"
)

// Factory declarations below are generated by Andurel.

type BackupPolicyFactory struct {
	models.BackupPolicyEntity
}

type BackupPolicyOption func(*BackupPolicyFactory)

func BuildBackupPolicy(resourceID uuid.UUID, resourceBindingID *uuid.UUID, backupDestinationID uuid.UUID, opts ...BackupPolicyOption) models.BackupPolicyEntity {
	f := &BackupPolicyFactory{
		BackupPolicyEntity: models.BackupPolicyEntity{
			ResourceID:          resourceID,
			ResourceBindingID:   resourceBindingID,
			BackupDestinationID: backupDestinationID,
			Name:                faker.Word(),
			Schedule:            faker.Word(),
			Retention:           json.RawMessage{},
			Format:              faker.Word(),
			Verification:        json.RawMessage{},
			Settings:            json.RawMessage{},
			ArchivedAt:          sql.NullTime{Time: time.Now(), Valid: true},
		},
	}

	for _, opt := range opts {
		opt(f)
	}

	return f.BackupPolicyEntity
}

func CreateBackupPolicy(ctx context.Context, exec storage.Executor, resourceID uuid.UUID, resourceBindingID *uuid.UUID, backupDestinationID uuid.UUID, opts ...BackupPolicyOption) (models.BackupPolicyEntity, error) {
	built := BuildBackupPolicy(resourceID, resourceBindingID, backupDestinationID, opts...)

	entity := models.BackupPolicyEntity{
		ID:                  uuid.New(),
		CreatedAt:           time.Now(),
		UpdatedAt:           time.Now(),
		ResourceID:          built.ResourceID,
		ResourceBindingID:   built.ResourceBindingID,
		BackupDestinationID: built.BackupDestinationID,
		Name:                built.Name,
		Schedule:            built.Schedule,
		Retention:           built.Retention,
		Format:              built.Format,
		Verification:        built.Verification,
		Settings:            built.Settings,
		ArchivedAt:          built.ArchivedAt,
	}

	if err := exec.NewInsert().Model(&entity).Returning("*").Scan(ctx); err != nil {
		return models.BackupPolicyEntity{}, err
	}

	return entity, nil
}

func CreateBackupPolicies(ctx context.Context, exec storage.Executor, resourceID uuid.UUID, resourceBindingID *uuid.UUID, backupDestinationID uuid.UUID, count int, opts ...BackupPolicyOption) ([]models.BackupPolicyEntity, error) {
	backupPolicies := make([]models.BackupPolicyEntity, 0, count)

	for i := range count {
		entity, err := CreateBackupPolicy(ctx, exec, resourceID, resourceBindingID, backupDestinationID, opts...)
		if err != nil {
			return nil, fmt.Errorf("failed to create backuppolicy %d: %w", i+1, err)
		}
		backupPolicies = append(backupPolicies, entity)
	}

	return backupPolicies, nil
}

func WithBackupPoliciesResourceID(value uuid.UUID) BackupPolicyOption {
	return func(f *BackupPolicyFactory) {
		f.BackupPolicyEntity.ResourceID = value
	}
}

func WithBackupPoliciesResourceBindingID(value *uuid.UUID) BackupPolicyOption {
	return func(f *BackupPolicyFactory) {
		f.BackupPolicyEntity.ResourceBindingID = value
	}
}

func WithBackupPoliciesBackupDestinationID(value uuid.UUID) BackupPolicyOption {
	return func(f *BackupPolicyFactory) {
		f.BackupPolicyEntity.BackupDestinationID = value
	}
}

func WithBackupPoliciesName(value string) BackupPolicyOption {
	return func(f *BackupPolicyFactory) {
		f.BackupPolicyEntity.Name = value
	}
}

func WithBackupPoliciesSchedule(value string) BackupPolicyOption {
	return func(f *BackupPolicyFactory) {
		f.BackupPolicyEntity.Schedule = value
	}
}

func WithBackupPoliciesRetention(value json.RawMessage) BackupPolicyOption {
	return func(f *BackupPolicyFactory) {
		f.BackupPolicyEntity.Retention = value
	}
}

func WithBackupPoliciesFormat(value string) BackupPolicyOption {
	return func(f *BackupPolicyFactory) {
		f.BackupPolicyEntity.Format = value
	}
}

func WithBackupPoliciesVerification(value json.RawMessage) BackupPolicyOption {
	return func(f *BackupPolicyFactory) {
		f.BackupPolicyEntity.Verification = value
	}
}

func WithBackupPoliciesSettings(value json.RawMessage) BackupPolicyOption {
	return func(f *BackupPolicyFactory) {
		f.BackupPolicyEntity.Settings = value
	}
}

func WithBackupPoliciesArchivedAt(value sql.NullTime) BackupPolicyOption {
	return func(f *BackupPolicyFactory) {
		f.BackupPolicyEntity.ArchivedAt = value
	}
}
