package factories

import (
	"context"
	"database/sql"
	"deploycrate-ce/internal/storage"
	"deploycrate-ce/models"
	"encoding/json"
	"fmt"
	"time"

	"github.com/go-faker/faker/v4"
	"github.com/google/uuid"
)

// Factory declarations below are generated by Andurel.

type BackupPolicyFactory struct {
	models.BackupPolicyEntity
}

type BackupPolicyOption func(*BackupPolicyFactory)

func BuildBackupPolicy(resourceID uuid.UUID, environmentResourceID *uuid.UUID, resourceVolumeID *uuid.UUID, backupDestinationID uuid.UUID, opts ...BackupPolicyOption) models.BackupPolicyEntity {
	f := &BackupPolicyFactory{
		BackupPolicyEntity: models.BackupPolicyEntity{
			Name:                  faker.Word(),
			Schedule:              faker.Word(),
			Strategy:              faker.Word(),
			Driver:                faker.Word(),
			Retention:             json.RawMessage{},
			Format:                faker.Word(),
			Verification:          json.RawMessage{},
			Settings:              json.RawMessage{},
			ArchivedAt:            sql.NullTime{Time: time.Now(), Valid: true},
			ResourceID:            resourceID,
			EnvironmentResourceID: environmentResourceID,
			ResourceVolumeID:      resourceVolumeID,
			BackupDestinationID:   backupDestinationID,
		},
	}

	for _, opt := range opts {
		opt(f)
	}

	return f.BackupPolicyEntity
}

func CreateBackupPolicy(ctx context.Context, exec storage.Executor, resourceID uuid.UUID, environmentResourceID *uuid.UUID, resourceVolumeID *uuid.UUID, backupDestinationID uuid.UUID, opts ...BackupPolicyOption) (models.BackupPolicyEntity, error) {
	built := BuildBackupPolicy(resourceID, environmentResourceID, resourceVolumeID, backupDestinationID, opts...)

	entity := models.BackupPolicyEntity{
		ID:                    uuid.New(),
		CreatedAt:             time.Now(),
		UpdatedAt:             time.Now(),
		Name:                  built.Name,
		Schedule:              built.Schedule,
		Strategy:              built.Strategy,
		Driver:                built.Driver,
		Retention:             built.Retention,
		Format:                built.Format,
		Verification:          built.Verification,
		Settings:              built.Settings,
		ArchivedAt:            built.ArchivedAt,
		ResourceID:            built.ResourceID,
		EnvironmentResourceID: built.EnvironmentResourceID,
		ResourceVolumeID:      built.ResourceVolumeID,
		BackupDestinationID:   built.BackupDestinationID,
	}

	if err := exec.NewInsert().Model(&entity).Returning("*").Scan(ctx); err != nil {
		return models.BackupPolicyEntity{}, err
	}

	return entity, nil
}

func CreateBackupPolicys(ctx context.Context, exec storage.Executor, resourceID uuid.UUID, environmentResourceID *uuid.UUID, resourceVolumeID *uuid.UUID, backupDestinationID uuid.UUID, count int, opts ...BackupPolicyOption) ([]models.BackupPolicyEntity, error) {
	backuppolicys := make([]models.BackupPolicyEntity, 0, count)

	for i := range count {
		entity, err := CreateBackupPolicy(ctx, exec, resourceID, environmentResourceID, resourceVolumeID, backupDestinationID, opts...)
		if err != nil {
			return nil, fmt.Errorf("failed to create backuppolicy %d: %w", i+1, err)
		}
		backuppolicys = append(backuppolicys, entity)
	}

	return backuppolicys, nil
}

func WithBackupPoliciesName(value string) BackupPolicyOption {
	return func(f *BackupPolicyFactory) {
		f.BackupPolicyEntity.Name = value
	}
}

func WithBackupPoliciesSchedule(value string) BackupPolicyOption {
	return func(f *BackupPolicyFactory) {
		f.BackupPolicyEntity.Schedule = value
	}
}

func WithBackupPoliciesStrategy(value string) BackupPolicyOption {
	return func(f *BackupPolicyFactory) {
		f.BackupPolicyEntity.Strategy = value
	}
}

func WithBackupPoliciesDriver(value string) BackupPolicyOption {
	return func(f *BackupPolicyFactory) {
		f.BackupPolicyEntity.Driver = value
	}
}

func WithBackupPoliciesRetention(value json.RawMessage) BackupPolicyOption {
	return func(f *BackupPolicyFactory) {
		f.BackupPolicyEntity.Retention = value
	}
}

func WithBackupPoliciesFormat(value string) BackupPolicyOption {
	return func(f *BackupPolicyFactory) {
		f.BackupPolicyEntity.Format = value
	}
}

func WithBackupPoliciesVerification(value json.RawMessage) BackupPolicyOption {
	return func(f *BackupPolicyFactory) {
		f.BackupPolicyEntity.Verification = value
	}
}

func WithBackupPoliciesSettings(value json.RawMessage) BackupPolicyOption {
	return func(f *BackupPolicyFactory) {
		f.BackupPolicyEntity.Settings = value
	}
}

func WithBackupPoliciesArchivedAt(value sql.NullTime) BackupPolicyOption {
	return func(f *BackupPolicyFactory) {
		f.BackupPolicyEntity.ArchivedAt = value
	}
}

func WithBackupPoliciesResourceID(value uuid.UUID) BackupPolicyOption {
	return func(f *BackupPolicyFactory) {
		f.BackupPolicyEntity.ResourceID = value
	}
}

func WithBackupPoliciesEnvironmentResourceID(value *uuid.UUID) BackupPolicyOption {
	return func(f *BackupPolicyFactory) {
		f.BackupPolicyEntity.EnvironmentResourceID = value
	}
}

func WithBackupPoliciesResourceVolumeID(value *uuid.UUID) BackupPolicyOption {
	return func(f *BackupPolicyFactory) {
		f.BackupPolicyEntity.ResourceVolumeID = value
	}
}

func WithBackupPoliciesBackupDestinationID(value uuid.UUID) BackupPolicyOption {
	return func(f *BackupPolicyFactory) {
		f.BackupPolicyEntity.BackupDestinationID = value
	}
}
