package factories

import (
	"context"
	"database/sql"
	"deploycrate-ce/internal/storage"
	"deploycrate-ce/models"
	"encoding/json"
	"fmt"
	"time"

	"github.com/go-faker/faker/v4"
	"github.com/google/uuid"
)

// Factory declarations below are generated by Andurel.

type BackupFactory struct {
	models.BackupEntity
}

type BackupOption func(*BackupFactory)

func BuildBackup(
	changeID uuid.UUID,
	changeTaskID uuid.UUID,
	backupPolicyID uuid.UUID,
	serverID, resourceID, resourceInstallationID *uuid.UUID,
	backupDestinationID uuid.UUID,
	opts ...BackupOption,
) models.BackupEntity {
	f := &BackupFactory{
		BackupEntity: models.BackupEntity{
			TargetType:             faker.Word(),
			Target:                 json.RawMessage(`{}`),
			TriggerType:            faker.Word(),
			ScheduledAt:            time.Time{},
			Strategy:               faker.Word(),
			Driver:                 faker.Word(),
			Format:                 faker.Word(),
			FormatVersion:          faker.Word(),
			ArtifactReference:      faker.Word(),
			ProviderMetadata:       json.RawMessage{},
			Status:                 faker.Word(),
			RequestedAt:            time.Time{},
			StartedAt:              sql.NullTime{Time: time.Now(), Valid: true},
			UploadedAt:             sql.NullTime{Time: time.Now(), Valid: true},
			FinishedAt:             sql.NullTime{Time: time.Now(), Valid: true},
			VerifiedAt:             sql.NullTime{Time: time.Now(), Valid: true},
			PrunedAt:               sql.NullTime{Time: time.Now(), Valid: true},
			SizeBytes:              sql.NullInt64{Int64: randomInt64(1, 1000, 100), Valid: true},
			Digest:                 []byte{},
			ProducerVersion:        faker.Word(),
			Error:                  sql.NullString{String: faker.Word(), Valid: true},
			ChangeID:               changeID,
			ChangeTaskID:           changeTaskID,
			BackupPolicyID:         backupPolicyID,
			ServerID:               serverID,
			ResourceID:             resourceID,
			ResourceInstallationID: resourceInstallationID,
			BackupDestinationID:    backupDestinationID,
		},
	}

	for _, opt := range opts {
		opt(f)
	}

	return f.BackupEntity
}

func CreateBackup(
	ctx context.Context,
	exec storage.Executor,
	changeID uuid.UUID,
	changeTaskID uuid.UUID,
	backupPolicyID uuid.UUID,
	serverID, resourceID, resourceInstallationID *uuid.UUID,
	backupDestinationID uuid.UUID,
	opts ...BackupOption,
) (models.BackupEntity, error) {
	built := BuildBackup(
		changeID,
		changeTaskID,
		backupPolicyID,
		serverID,
		resourceID,
		resourceInstallationID,
		backupDestinationID,
		opts...)

	entity := models.BackupEntity{
		ID:                     uuid.New(),
		CreatedAt:              time.Now(),
		UpdatedAt:              time.Now(),
		TargetType:             built.TargetType,
		Target:                 built.Target,
		TriggerType:            built.TriggerType,
		ScheduledAt:            built.ScheduledAt,
		Strategy:               built.Strategy,
		Driver:                 built.Driver,
		Format:                 built.Format,
		FormatVersion:          built.FormatVersion,
		ArtifactReference:      built.ArtifactReference,
		ProviderMetadata:       built.ProviderMetadata,
		Status:                 built.Status,
		RequestedAt:            built.RequestedAt,
		StartedAt:              built.StartedAt,
		UploadedAt:             built.UploadedAt,
		FinishedAt:             built.FinishedAt,
		VerifiedAt:             built.VerifiedAt,
		PrunedAt:               built.PrunedAt,
		SizeBytes:              built.SizeBytes,
		Digest:                 built.Digest,
		ProducerVersion:        built.ProducerVersion,
		Error:                  built.Error,
		ChangeID:               built.ChangeID,
		ChangeTaskID:           built.ChangeTaskID,
		BackupPolicyID:         built.BackupPolicyID,
		ServerID:               built.ServerID,
		ResourceID:             built.ResourceID,
		ResourceInstallationID: built.ResourceInstallationID,
		BackupDestinationID:    built.BackupDestinationID,
	}

	if err := exec.NewInsert().Model(&entity).Returning("*").Scan(ctx); err != nil {
		return models.BackupEntity{}, err
	}

	return entity, nil
}

func CreateBackups(
	ctx context.Context,
	exec storage.Executor,
	changeID uuid.UUID,
	changeTaskID uuid.UUID,
	backupPolicyID uuid.UUID,
	serverID, resourceID, resourceInstallationID *uuid.UUID,
	backupDestinationID uuid.UUID,
	count int,
	opts ...BackupOption,
) ([]models.BackupEntity, error) {
	backups := make([]models.BackupEntity, 0, count)

	for i := range count {
		entity, err := CreateBackup(
			ctx,
			exec,
			changeID,
			changeTaskID,
			backupPolicyID,
			serverID,
			resourceID,
			resourceInstallationID,
			backupDestinationID,
			opts...)
		if err != nil {
			return nil, fmt.Errorf("failed to create backup %d: %w", i+1, err)
		}
		backups = append(backups, entity)
	}

	return backups, nil
}

func WithBackupsTargetType(value string) BackupOption {
	return func(f *BackupFactory) {
		f.BackupEntity.TargetType = value
	}
}

func WithBackupsTarget(value json.RawMessage) BackupOption {
	return func(f *BackupFactory) {
		f.BackupEntity.Target = value
	}
}

func WithBackupsTriggerType(value string) BackupOption {
	return func(f *BackupFactory) {
		f.BackupEntity.TriggerType = value
	}
}

func WithBackupsScheduledAt(value time.Time) BackupOption {
	return func(f *BackupFactory) {
		f.BackupEntity.ScheduledAt = value
	}
}

func WithBackupsStrategy(value string) BackupOption {
	return func(f *BackupFactory) {
		f.BackupEntity.Strategy = value
	}
}

func WithBackupsDriver(value string) BackupOption {
	return func(f *BackupFactory) {
		f.BackupEntity.Driver = value
	}
}

func WithBackupsFormat(value string) BackupOption {
	return func(f *BackupFactory) {
		f.BackupEntity.Format = value
	}
}

func WithBackupsFormatVersion(value string) BackupOption {
	return func(f *BackupFactory) {
		f.BackupEntity.FormatVersion = value
	}
}

func WithBackupsArtifactReference(value string) BackupOption {
	return func(f *BackupFactory) {
		f.BackupEntity.ArtifactReference = value
	}
}

func WithBackupsProviderMetadata(value json.RawMessage) BackupOption {
	return func(f *BackupFactory) {
		f.BackupEntity.ProviderMetadata = value
	}
}

func WithBackupsStatus(value string) BackupOption {
	return func(f *BackupFactory) {
		f.BackupEntity.Status = value
	}
}

func WithBackupsRequestedAt(value time.Time) BackupOption {
	return func(f *BackupFactory) {
		f.BackupEntity.RequestedAt = value
	}
}

func WithBackupsStartedAt(value sql.NullTime) BackupOption {
	return func(f *BackupFactory) {
		f.BackupEntity.StartedAt = value
	}
}

func WithBackupsUploadedAt(value sql.NullTime) BackupOption {
	return func(f *BackupFactory) {
		f.BackupEntity.UploadedAt = value
	}
}

func WithBackupsFinishedAt(value sql.NullTime) BackupOption {
	return func(f *BackupFactory) {
		f.BackupEntity.FinishedAt = value
	}
}

func WithBackupsVerifiedAt(value sql.NullTime) BackupOption {
	return func(f *BackupFactory) {
		f.BackupEntity.VerifiedAt = value
	}
}

func WithBackupsPrunedAt(value sql.NullTime) BackupOption {
	return func(f *BackupFactory) {
		f.BackupEntity.PrunedAt = value
	}
}

func WithBackupsSizeBytes(value sql.NullInt64) BackupOption {
	return func(f *BackupFactory) {
		f.BackupEntity.SizeBytes = value
	}
}

func WithBackupsDigest(value []byte) BackupOption {
	return func(f *BackupFactory) {
		f.BackupEntity.Digest = value
	}
}

func WithBackupsProducerVersion(value string) BackupOption {
	return func(f *BackupFactory) {
		f.BackupEntity.ProducerVersion = value
	}
}

func WithBackupsError(value sql.NullString) BackupOption {
	return func(f *BackupFactory) {
		f.BackupEntity.Error = value
	}
}

func WithBackupsChangeID(value uuid.UUID) BackupOption {
	return func(f *BackupFactory) {
		f.BackupEntity.ChangeID = value
	}
}

func WithBackupsChangeTaskID(value uuid.UUID) BackupOption {
	return func(f *BackupFactory) {
		f.BackupEntity.ChangeTaskID = value
	}
}

func WithBackupsBackupPolicyID(value uuid.UUID) BackupOption {
	return func(f *BackupFactory) {
		f.BackupEntity.BackupPolicyID = value
	}
}

func WithBackupsServerID(value *uuid.UUID) BackupOption {
	return func(f *BackupFactory) {
		f.BackupEntity.ServerID = value
	}
}

func WithBackupsResourceID(value *uuid.UUID) BackupOption {
	return func(f *BackupFactory) {
		f.BackupEntity.ResourceID = value
	}
}

func WithBackupsResourceInstallationID(value *uuid.UUID) BackupOption {
	return func(f *BackupFactory) {
		f.BackupEntity.ResourceInstallationID = value
	}
}

func WithBackupsBackupDestinationID(value uuid.UUID) BackupOption {
	return func(f *BackupFactory) {
		f.BackupEntity.BackupDestinationID = value
	}
}
