package factories

import (
	"context"
	"deploycrate-ce/internal/storage"
	"deploycrate-ce/models"
	"fmt"
	"time"

	"github.com/go-faker/faker/v4"
	"github.com/google/uuid"
)

// Factory declarations below are generated by Andurel.

type BuildLogFactory struct {
	models.BuildLogEntity
}

type BuildLogOption func(*BuildLogFactory)

func BuildBuildLog(buildID uuid.UUID, opts ...BuildLogOption) models.BuildLogEntity {
	f := &BuildLogFactory{
		BuildLogEntity: models.BuildLogEntity{
			Sequence:   randomInt64(1, 1000, 100),
			Stream:     faker.Word(),
			Message:    faker.Word(),
			OccurredAt: time.Time{},
			BuildID:    buildID,
		},
	}

	for _, opt := range opts {
		opt(f)
	}

	return f.BuildLogEntity
}

func CreateBuildLog(
	ctx context.Context,
	exec storage.Executor,
	buildID uuid.UUID,
	opts ...BuildLogOption,
) (models.BuildLogEntity, error) {
	built := BuildBuildLog(buildID, opts...)

	entity := models.BuildLogEntity{
		ID:         uuid.New(),
		CreatedAt:  time.Now(),
		UpdatedAt:  time.Now(),
		Sequence:   built.Sequence,
		Stream:     built.Stream,
		Message:    built.Message,
		OccurredAt: built.OccurredAt,
		BuildID:    built.BuildID,
	}

	if err := exec.NewInsert().Model(&entity).Returning("*").Scan(ctx); err != nil {
		return models.BuildLogEntity{}, err
	}

	return entity, nil
}

func CreateBuildLogs(
	ctx context.Context,
	exec storage.Executor,
	buildID uuid.UUID,
	count int,
	opts ...BuildLogOption,
) ([]models.BuildLogEntity, error) {
	buildlogs := make([]models.BuildLogEntity, 0, count)

	for i := range count {
		entity, err := CreateBuildLog(ctx, exec, buildID, opts...)
		if err != nil {
			return nil, fmt.Errorf("failed to create buildlog %d: %w", i+1, err)
		}
		buildlogs = append(buildlogs, entity)
	}

	return buildlogs, nil
}

func WithBuildLogsSequence(value int64) BuildLogOption {
	return func(f *BuildLogFactory) {
		f.BuildLogEntity.Sequence = value
	}
}

func WithBuildLogsStream(value string) BuildLogOption {
	return func(f *BuildLogFactory) {
		f.BuildLogEntity.Stream = value
	}
}

func WithBuildLogsMessage(value string) BuildLogOption {
	return func(f *BuildLogFactory) {
		f.BuildLogEntity.Message = value
	}
}

func WithBuildLogsOccurredAt(value time.Time) BuildLogOption {
	return func(f *BuildLogFactory) {
		f.BuildLogEntity.OccurredAt = value
	}
}

func WithBuildLogsBuildID(value uuid.UUID) BuildLogOption {
	return func(f *BuildLogFactory) {
		f.BuildLogEntity.BuildID = value
	}
}
