package factories

import (
	"context"
	"database/sql"
	"deploycrate-ce/internal/storage"
	"deploycrate-ce/models"
	"encoding/json"
	"fmt"
	"time"

	"github.com/go-faker/faker/v4"
	"github.com/google/uuid"
)

// Factory declarations below are generated by Andurel.

type BuildpackConfigurationFactory struct {
	models.BuildpackConfigurationEntity
}

type BuildpackConfigurationOption func(*BuildpackConfigurationFactory)

func BuildBuildpackConfiguration(environmentSourceID uuid.UUID, containerRegistryID uuid.UUID, opts ...BuildpackConfigurationOption) models.BuildpackConfigurationEntity {
	f := &BuildpackConfigurationFactory{
		BuildpackConfigurationEntity: models.BuildpackConfigurationEntity{
			ContextPath:         faker.Word(),
			BuilderReference:    sql.NullString{String: faker.Word(), Valid: true},
			Repository:          faker.Word(),
			Settings:            json.RawMessage{},
			EnvironmentSourceID: environmentSourceID,
			ContainerRegistryID: containerRegistryID,
		},
	}

	for _, opt := range opts {
		opt(f)
	}

	return f.BuildpackConfigurationEntity
}

func CreateBuildpackConfiguration(ctx context.Context, exec storage.Executor, environmentSourceID uuid.UUID, containerRegistryID uuid.UUID, opts ...BuildpackConfigurationOption) (models.BuildpackConfigurationEntity, error) {
	built := BuildBuildpackConfiguration(environmentSourceID, containerRegistryID, opts...)

	entity := models.BuildpackConfigurationEntity{
		ID:                  built.ID,
		CreatedAt:           time.Now(),
		UpdatedAt:           time.Now(),
		ContextPath:         built.ContextPath,
		BuilderReference:    built.BuilderReference,
		Repository:          built.Repository,
		Settings:            built.Settings,
		EnvironmentSourceID: built.EnvironmentSourceID,
		ContainerRegistryID: built.ContainerRegistryID,
	}

	if err := exec.NewInsert().Model(&entity).Returning("*").Scan(ctx); err != nil {
		return models.BuildpackConfigurationEntity{}, err
	}

	return entity, nil
}

func CreateBuildpackConfigurations(ctx context.Context, exec storage.Executor, environmentSourceID uuid.UUID, containerRegistryID uuid.UUID, count int, opts ...BuildpackConfigurationOption) ([]models.BuildpackConfigurationEntity, error) {
	buildpackconfigurations := make([]models.BuildpackConfigurationEntity, 0, count)

	for i := range count {
		entity, err := CreateBuildpackConfiguration(ctx, exec, environmentSourceID, containerRegistryID, opts...)
		if err != nil {
			return nil, fmt.Errorf("failed to create buildpackconfiguration %d: %w", i+1, err)
		}
		buildpackconfigurations = append(buildpackconfigurations, entity)
	}

	return buildpackconfigurations, nil
}

func WithBuildpackConfigurationsContextPath(value string) BuildpackConfigurationOption {
	return func(f *BuildpackConfigurationFactory) {
		f.BuildpackConfigurationEntity.ContextPath = value
	}
}

func WithBuildpackConfigurationsBuilderReference(value sql.NullString) BuildpackConfigurationOption {
	return func(f *BuildpackConfigurationFactory) {
		f.BuildpackConfigurationEntity.BuilderReference = value
	}
}

func WithBuildpackConfigurationsRepository(value string) BuildpackConfigurationOption {
	return func(f *BuildpackConfigurationFactory) {
		f.BuildpackConfigurationEntity.Repository = value
	}
}

func WithBuildpackConfigurationsSettings(value json.RawMessage) BuildpackConfigurationOption {
	return func(f *BuildpackConfigurationFactory) {
		f.BuildpackConfigurationEntity.Settings = value
	}
}

func WithBuildpackConfigurationsEnvironmentSourceID(value uuid.UUID) BuildpackConfigurationOption {
	return func(f *BuildpackConfigurationFactory) {
		f.BuildpackConfigurationEntity.EnvironmentSourceID = value
	}
}

func WithBuildpackConfigurationsContainerRegistryID(value uuid.UUID) BuildpackConfigurationOption {
	return func(f *BuildpackConfigurationFactory) {
		f.BuildpackConfigurationEntity.ContainerRegistryID = value
	}
}
