package factories

import (
	"context"
	"database/sql"
	"deploycrate-ce/internal/storage"
	"deploycrate-ce/models"
	"encoding/json"
	"fmt"
	"time"

	"github.com/go-faker/faker/v4"
	"github.com/google/uuid"
)

// Factory declarations below are generated by Andurel.

type BuildFactory struct {
	models.BuildEntity
}

type BuildOption func(*BuildFactory)

func BuildBuild(environmentID uuid.UUID, environmentSourceID uuid.UUID, changeID uuid.UUID, opts ...BuildOption) models.BuildEntity {
	f := &BuildFactory{
		BuildEntity: models.BuildEntity{
			SourceRevision:      faker.Word(),
			BuildMethod:         faker.Word(),
			BuildConfiguration:  json.RawMessage{},
			Status:              faker.Word(),
			ArtifactReference:   sql.NullString{String: faker.Word(), Valid: true},
			ArtifactDigest:      []byte{},
			StartedAt:           sql.NullTime{Time: time.Now(), Valid: true},
			FinishedAt:          sql.NullTime{Time: time.Now(), Valid: true},
			Error:               sql.NullString{String: faker.Word(), Valid: true},
			EnvironmentID:       environmentID,
			EnvironmentSourceID: environmentSourceID,
			ChangeID:            changeID,
		},
	}

	for _, opt := range opts {
		opt(f)
	}

	return f.BuildEntity
}

func CreateBuild(ctx context.Context, exec storage.Executor, environmentID uuid.UUID, environmentSourceID uuid.UUID, changeID uuid.UUID, opts ...BuildOption) (models.BuildEntity, error) {
	built := BuildBuild(environmentID, environmentSourceID, changeID, opts...)

	entity := models.BuildEntity{
		ID:                  uuid.New(),
		CreatedAt:           time.Now(),
		UpdatedAt:           time.Now(),
		SourceRevision:      built.SourceRevision,
		BuildMethod:         built.BuildMethod,
		BuildConfiguration:  built.BuildConfiguration,
		Status:              built.Status,
		ArtifactReference:   built.ArtifactReference,
		ArtifactDigest:      built.ArtifactDigest,
		StartedAt:           built.StartedAt,
		FinishedAt:          built.FinishedAt,
		Error:               built.Error,
		EnvironmentID:       built.EnvironmentID,
		EnvironmentSourceID: built.EnvironmentSourceID,
		ChangeID:            built.ChangeID,
	}

	if err := exec.NewInsert().Model(&entity).Returning("*").Scan(ctx); err != nil {
		return models.BuildEntity{}, err
	}

	return entity, nil
}

func CreateBuilds(ctx context.Context, exec storage.Executor, environmentID uuid.UUID, environmentSourceID uuid.UUID, changeID uuid.UUID, count int, opts ...BuildOption) ([]models.BuildEntity, error) {
	builds := make([]models.BuildEntity, 0, count)

	for i := range count {
		entity, err := CreateBuild(ctx, exec, environmentID, environmentSourceID, changeID, opts...)
		if err != nil {
			return nil, fmt.Errorf("failed to create build %d: %w", i+1, err)
		}
		builds = append(builds, entity)
	}

	return builds, nil
}

func WithBuildsSourceRevision(value string) BuildOption {
	return func(f *BuildFactory) {
		f.BuildEntity.SourceRevision = value
	}
}

func WithBuildsBuildMethod(value string) BuildOption {
	return func(f *BuildFactory) {
		f.BuildEntity.BuildMethod = value
	}
}

func WithBuildsBuildConfiguration(value json.RawMessage) BuildOption {
	return func(f *BuildFactory) {
		f.BuildEntity.BuildConfiguration = value
	}
}

func WithBuildsStatus(value string) BuildOption {
	return func(f *BuildFactory) {
		f.BuildEntity.Status = value
	}
}

func WithBuildsArtifactReference(value sql.NullString) BuildOption {
	return func(f *BuildFactory) {
		f.BuildEntity.ArtifactReference = value
	}
}

func WithBuildsArtifactDigest(value []byte) BuildOption {
	return func(f *BuildFactory) {
		f.BuildEntity.ArtifactDigest = value
	}
}

func WithBuildsStartedAt(value sql.NullTime) BuildOption {
	return func(f *BuildFactory) {
		f.BuildEntity.StartedAt = value
	}
}

func WithBuildsFinishedAt(value sql.NullTime) BuildOption {
	return func(f *BuildFactory) {
		f.BuildEntity.FinishedAt = value
	}
}

func WithBuildsError(value sql.NullString) BuildOption {
	return func(f *BuildFactory) {
		f.BuildEntity.Error = value
	}
}

func WithBuildsEnvironmentID(value uuid.UUID) BuildOption {
	return func(f *BuildFactory) {
		f.BuildEntity.EnvironmentID = value
	}
}

func WithBuildsEnvironmentSourceID(value uuid.UUID) BuildOption {
	return func(f *BuildFactory) {
		f.BuildEntity.EnvironmentSourceID = value
	}
}

func WithBuildsChangeID(value uuid.UUID) BuildOption {
	return func(f *BuildFactory) {
		f.BuildEntity.ChangeID = value
	}
}
