package factories

import (
	"context"
	"database/sql"
	"deploycrate-ce/internal/storage"
	"deploycrate-ce/models"
	"fmt"
	"time"

	"github.com/google/uuid"
)

// Factory declarations below are generated by Andurel.

type CaddyRouteBackendFactory struct {
	models.CaddyRouteBackendEntity
}

type CaddyRouteBackendOption func(*CaddyRouteBackendFactory)

func BuildCaddyRouteBackend(caddyRouteID uuid.UUID, instanceID uuid.UUID, opts ...CaddyRouteBackendOption) models.CaddyRouteBackendEntity {
	f := &CaddyRouteBackendFactory{
		CaddyRouteBackendEntity: models.CaddyRouteBackendEntity{
			Weight:       randomInt(1, 1000, 100),
			RemovedAt:    sql.NullTime{Time: time.Now(), Valid: true},
			CaddyRouteID: caddyRouteID,
			InstanceID:   instanceID,
		},
	}

	for _, opt := range opts {
		opt(f)
	}

	return f.CaddyRouteBackendEntity
}

func CreateCaddyRouteBackend(ctx context.Context, exec storage.Executor, caddyRouteID uuid.UUID, instanceID uuid.UUID, opts ...CaddyRouteBackendOption) (models.CaddyRouteBackendEntity, error) {
	built := BuildCaddyRouteBackend(caddyRouteID, instanceID, opts...)

	entity := models.CaddyRouteBackendEntity{
		ID:           built.ID,
		CreatedAt:    time.Now(),
		UpdatedAt:    time.Now(),
		Weight:       built.Weight,
		RemovedAt:    built.RemovedAt,
		CaddyRouteID: built.CaddyRouteID,
		InstanceID:   built.InstanceID,
	}

	if err := exec.NewInsert().Model(&entity).Returning("*").Scan(ctx); err != nil {
		return models.CaddyRouteBackendEntity{}, err
	}

	return entity, nil
}

func CreateCaddyRouteBackends(ctx context.Context, exec storage.Executor, caddyRouteID uuid.UUID, instanceID uuid.UUID, count int, opts ...CaddyRouteBackendOption) ([]models.CaddyRouteBackendEntity, error) {
	caddyroutebackends := make([]models.CaddyRouteBackendEntity, 0, count)

	for i := range count {
		entity, err := CreateCaddyRouteBackend(ctx, exec, caddyRouteID, instanceID, opts...)
		if err != nil {
			return nil, fmt.Errorf("failed to create caddyroutebackend %d: %w", i+1, err)
		}
		caddyroutebackends = append(caddyroutebackends, entity)
	}

	return caddyroutebackends, nil
}

func WithCaddyRouteBackendsWeight(value int32) CaddyRouteBackendOption {
	return func(f *CaddyRouteBackendFactory) {
		f.CaddyRouteBackendEntity.Weight = value
	}
}

func WithCaddyRouteBackendsRemovedAt(value sql.NullTime) CaddyRouteBackendOption {
	return func(f *CaddyRouteBackendFactory) {
		f.CaddyRouteBackendEntity.RemovedAt = value
	}
}

func WithCaddyRouteBackendsCaddyRouteID(value uuid.UUID) CaddyRouteBackendOption {
	return func(f *CaddyRouteBackendFactory) {
		f.CaddyRouteBackendEntity.CaddyRouteID = value
	}
}

func WithCaddyRouteBackendsInstanceID(value uuid.UUID) CaddyRouteBackendOption {
	return func(f *CaddyRouteBackendFactory) {
		f.CaddyRouteBackendEntity.InstanceID = value
	}
}
