package factories

import (
	"context"
	"database/sql"
	"deploycrate-ce/internal/storage"
	"deploycrate-ce/models"
	"fmt"
	"time"

	"github.com/go-faker/faker/v4"
	"github.com/google/uuid"
)

// Factory declarations below are generated by Andurel.

type CaddyRouteFactory struct {
	models.CaddyRouteEntity
}

type CaddyRouteOption func(*CaddyRouteFactory)

func BuildCaddyRoute(environmentTargetID uuid.UUID, environmentDomainID uuid.UUID, releaseID uuid.UUID, externalID string, opts ...CaddyRouteOption) models.CaddyRouteEntity {
	f := &CaddyRouteFactory{
		CaddyRouteEntity: models.CaddyRouteEntity{
			EnvironmentTargetID: environmentTargetID,
			EnvironmentDomainID: environmentDomainID,
			ReleaseID:           releaseID,
			ExternalID:          externalID,
			State:               faker.Word(),
			AppliedAt:           sql.NullTime{Time: time.Now(), Valid: true},
			ObservedAt:          sql.NullTime{Time: time.Now(), Valid: true},
			RemovedAt:           sql.NullTime{Time: time.Now(), Valid: true},
		},
	}

	for _, opt := range opts {
		opt(f)
	}

	return f.CaddyRouteEntity
}

func CreateCaddyRoute(ctx context.Context, exec storage.Executor, environmentTargetID uuid.UUID, environmentDomainID uuid.UUID, releaseID uuid.UUID, externalID string, opts ...CaddyRouteOption) (models.CaddyRouteEntity, error) {
	built := BuildCaddyRoute(environmentTargetID, environmentDomainID, releaseID, externalID, opts...)

	entity := models.CaddyRouteEntity{
		ID:                  uuid.New(),
		CreatedAt:           time.Now(),
		UpdatedAt:           time.Now(),
		EnvironmentTargetID: built.EnvironmentTargetID,
		EnvironmentDomainID: built.EnvironmentDomainID,
		ReleaseID:           built.ReleaseID,
		ExternalID:          built.ExternalID,
		State:               built.State,
		AppliedAt:           built.AppliedAt,
		ObservedAt:          built.ObservedAt,
		RemovedAt:           built.RemovedAt,
	}

	if err := exec.NewInsert().Model(&entity).Returning("*").Scan(ctx); err != nil {
		return models.CaddyRouteEntity{}, err
	}

	return entity, nil
}

func CreateCaddyRoutes(ctx context.Context, exec storage.Executor, environmentTargetID uuid.UUID, environmentDomainID uuid.UUID, releaseID uuid.UUID, externalID string, count int, opts ...CaddyRouteOption) ([]models.CaddyRouteEntity, error) {
	caddyroutes := make([]models.CaddyRouteEntity, 0, count)

	for i := range count {
		entity, err := CreateCaddyRoute(ctx, exec, environmentTargetID, environmentDomainID, releaseID, externalID, opts...)
		if err != nil {
			return nil, fmt.Errorf("failed to create caddyroute %d: %w", i+1, err)
		}
		caddyroutes = append(caddyroutes, entity)
	}

	return caddyroutes, nil
}

func WithCaddyRoutesEnvironmentTargetID(value uuid.UUID) CaddyRouteOption {
	return func(f *CaddyRouteFactory) {
		f.CaddyRouteEntity.EnvironmentTargetID = value
	}
}

func WithCaddyRoutesEnvironmentDomainID(value uuid.UUID) CaddyRouteOption {
	return func(f *CaddyRouteFactory) {
		f.CaddyRouteEntity.EnvironmentDomainID = value
	}
}

func WithCaddyRoutesReleaseID(value uuid.UUID) CaddyRouteOption {
	return func(f *CaddyRouteFactory) {
		f.CaddyRouteEntity.ReleaseID = value
	}
}

func WithCaddyRoutesExternalID(value string) CaddyRouteOption {
	return func(f *CaddyRouteFactory) {
		f.CaddyRouteEntity.ExternalID = value
	}
}

func WithCaddyRoutesState(value string) CaddyRouteOption {
	return func(f *CaddyRouteFactory) {
		f.CaddyRouteEntity.State = value
	}
}

func WithCaddyRoutesAppliedAt(value sql.NullTime) CaddyRouteOption {
	return func(f *CaddyRouteFactory) {
		f.CaddyRouteEntity.AppliedAt = value
	}
}

func WithCaddyRoutesObservedAt(value sql.NullTime) CaddyRouteOption {
	return func(f *CaddyRouteFactory) {
		f.CaddyRouteEntity.ObservedAt = value
	}
}

func WithCaddyRoutesRemovedAt(value sql.NullTime) CaddyRouteOption {
	return func(f *CaddyRouteFactory) {
		f.CaddyRouteEntity.RemovedAt = value
	}
}
