package factories

import (
	"context"
	"database/sql"
	"deploycrate-ce/internal/storage"
	"deploycrate-ce/models"
	"encoding/json"
	"fmt"
	"time"

	"github.com/go-faker/faker/v4"
	"github.com/google/uuid"
)

// Factory declarations below are generated by Andurel.

type ChangeTaskAttemptFactory struct {
	models.ChangeTaskAttemptEntity
}

type ChangeTaskAttemptOption func(*ChangeTaskAttemptFactory)

func BuildChangeTaskAttempt(changeTaskID uuid.UUID, opts ...ChangeTaskAttemptOption) models.ChangeTaskAttemptEntity {
	f := &ChangeTaskAttemptFactory{
		ChangeTaskAttemptEntity: models.ChangeTaskAttemptEntity{
			ChangeTaskID:    changeTaskID,
			Attempt:         randomInt(1, 1000, 100),
			Status:          faker.Word(),
			StartedAt:       time.Time{},
			LastHeartbeatAt: sql.NullTime{Time: time.Now(), Valid: true},
			FinishedAt:      sql.NullTime{Time: time.Now(), Valid: true},
			Result:          json.RawMessage{},
			Error:           sql.NullString{String: faker.Word(), Valid: true},
		},
	}

	for _, opt := range opts {
		opt(f)
	}

	return f.ChangeTaskAttemptEntity
}

func CreateChangeTaskAttempt(ctx context.Context, exec storage.Executor, changeTaskID uuid.UUID, opts ...ChangeTaskAttemptOption) (models.ChangeTaskAttemptEntity, error) {
	built := BuildChangeTaskAttempt(changeTaskID, opts...)

	entity := models.ChangeTaskAttemptEntity{
		ID:              uuid.New(),
		CreatedAt:       time.Now(),
		UpdatedAt:       time.Now(),
		ChangeTaskID:    built.ChangeTaskID,
		Attempt:         built.Attempt,
		Status:          built.Status,
		StartedAt:       built.StartedAt,
		LastHeartbeatAt: built.LastHeartbeatAt,
		FinishedAt:      built.FinishedAt,
		Result:          built.Result,
		Error:           built.Error,
	}

	if err := exec.NewInsert().Model(&entity).Returning("*").Scan(ctx); err != nil {
		return models.ChangeTaskAttemptEntity{}, err
	}

	return entity, nil
}

func CreateChangeTaskAttempts(ctx context.Context, exec storage.Executor, changeTaskID uuid.UUID, count int, opts ...ChangeTaskAttemptOption) ([]models.ChangeTaskAttemptEntity, error) {
	changetaskattempts := make([]models.ChangeTaskAttemptEntity, 0, count)

	for i := range count {
		entity, err := CreateChangeTaskAttempt(ctx, exec, changeTaskID, opts...)
		if err != nil {
			return nil, fmt.Errorf("failed to create changetaskattempt %d: %w", i+1, err)
		}
		changetaskattempts = append(changetaskattempts, entity)
	}

	return changetaskattempts, nil
}

func WithChangeTaskAttemptsChangeTaskID(value uuid.UUID) ChangeTaskAttemptOption {
	return func(f *ChangeTaskAttemptFactory) {
		f.ChangeTaskAttemptEntity.ChangeTaskID = value
	}
}

func WithChangeTaskAttemptsAttempt(value int32) ChangeTaskAttemptOption {
	return func(f *ChangeTaskAttemptFactory) {
		f.ChangeTaskAttemptEntity.Attempt = value
	}
}

func WithChangeTaskAttemptsStatus(value string) ChangeTaskAttemptOption {
	return func(f *ChangeTaskAttemptFactory) {
		f.ChangeTaskAttemptEntity.Status = value
	}
}

func WithChangeTaskAttemptsStartedAt(value time.Time) ChangeTaskAttemptOption {
	return func(f *ChangeTaskAttemptFactory) {
		f.ChangeTaskAttemptEntity.StartedAt = value
	}
}

func WithChangeTaskAttemptsLastHeartbeatAt(value sql.NullTime) ChangeTaskAttemptOption {
	return func(f *ChangeTaskAttemptFactory) {
		f.ChangeTaskAttemptEntity.LastHeartbeatAt = value
	}
}

func WithChangeTaskAttemptsFinishedAt(value sql.NullTime) ChangeTaskAttemptOption {
	return func(f *ChangeTaskAttemptFactory) {
		f.ChangeTaskAttemptEntity.FinishedAt = value
	}
}

func WithChangeTaskAttemptsResult(value json.RawMessage) ChangeTaskAttemptOption {
	return func(f *ChangeTaskAttemptFactory) {
		f.ChangeTaskAttemptEntity.Result = value
	}
}

func WithChangeTaskAttemptsError(value sql.NullString) ChangeTaskAttemptOption {
	return func(f *ChangeTaskAttemptFactory) {
		f.ChangeTaskAttemptEntity.Error = value
	}
}
