package factories

import (
	"context"
	"deploycrate-ce/internal/storage"
	"deploycrate-ce/models"
	"encoding/json"
	"fmt"
	"time"

	"github.com/go-faker/faker/v4"
	"github.com/google/uuid"
)

// Factory declarations below are generated by Andurel.

type ChangeItemFactory struct {
	models.ChangeItemEntity
}

type ChangeItemOption func(*ChangeItemFactory)

func BuildChangeItem(subjectID uuid.UUID, changeID uuid.UUID, opts ...ChangeItemOption) models.ChangeItemEntity {
	f := &ChangeItemFactory{
		ChangeItemEntity: models.ChangeItemEntity{
			Action:         faker.Word(),
			SubjectType:    faker.Word(),
			SubjectID:      subjectID,
			PreviousValue:  json.RawMessage{},
			RequestedValue: json.RawMessage{},
			ChangeID:       changeID,
		},
	}

	for _, opt := range opts {
		opt(f)
	}

	return f.ChangeItemEntity
}

func CreateChangeItem(ctx context.Context, exec storage.Executor, subjectID uuid.UUID, changeID uuid.UUID, opts ...ChangeItemOption) (models.ChangeItemEntity, error) {
	built := BuildChangeItem(subjectID, changeID, opts...)

	entity := models.ChangeItemEntity{
		ID:             built.ID,
		CreatedAt:      time.Now(),
		UpdatedAt:      time.Now(),
		Action:         built.Action,
		SubjectType:    built.SubjectType,
		SubjectID:      built.SubjectID,
		PreviousValue:  built.PreviousValue,
		RequestedValue: built.RequestedValue,
		ChangeID:       built.ChangeID,
	}

	if err := exec.NewInsert().Model(&entity).Returning("*").Scan(ctx); err != nil {
		return models.ChangeItemEntity{}, err
	}

	return entity, nil
}

func CreateChangeItems(ctx context.Context, exec storage.Executor, subjectID uuid.UUID, changeID uuid.UUID, count int, opts ...ChangeItemOption) ([]models.ChangeItemEntity, error) {
	changeitems := make([]models.ChangeItemEntity, 0, count)

	for i := range count {
		entity, err := CreateChangeItem(ctx, exec, subjectID, changeID, opts...)
		if err != nil {
			return nil, fmt.Errorf("failed to create changeitem %d: %w", i+1, err)
		}
		changeitems = append(changeitems, entity)
	}

	return changeitems, nil
}

func WithChangeItemsAction(value string) ChangeItemOption {
	return func(f *ChangeItemFactory) {
		f.ChangeItemEntity.Action = value
	}
}

func WithChangeItemsSubjectType(value string) ChangeItemOption {
	return func(f *ChangeItemFactory) {
		f.ChangeItemEntity.SubjectType = value
	}
}

func WithChangeItemsSubjectID(value uuid.UUID) ChangeItemOption {
	return func(f *ChangeItemFactory) {
		f.ChangeItemEntity.SubjectID = value
	}
}

func WithChangeItemsPreviousValue(value json.RawMessage) ChangeItemOption {
	return func(f *ChangeItemFactory) {
		f.ChangeItemEntity.PreviousValue = value
	}
}

func WithChangeItemsRequestedValue(value json.RawMessage) ChangeItemOption {
	return func(f *ChangeItemFactory) {
		f.ChangeItemEntity.RequestedValue = value
	}
}

func WithChangeItemsChangeID(value uuid.UUID) ChangeItemOption {
	return func(f *ChangeItemFactory) {
		f.ChangeItemEntity.ChangeID = value
	}
}
