package factories

import (
	"context"
	"database/sql"
	"deploycrate-ce/internal/storage"
	"deploycrate-ce/models"
	"encoding/json"
	"fmt"
	"time"

	"github.com/go-faker/faker/v4"
	"github.com/google/uuid"
)

// Factory declarations below are generated by Andurel.

type ChangeLogFactory struct {
	models.ChangeLogEntity
}

type ChangeLogOption func(*ChangeLogFactory)

func BuildChangeLog(changeID uuid.UUID, changeTaskID *uuid.UUID, changeTaskAttemptID *uuid.UUID, opts ...ChangeLogOption) models.ChangeLogEntity {
	f := &ChangeLogFactory{
		ChangeLogEntity: models.ChangeLogEntity{
			ChangeID:            changeID,
			ChangeTaskID:        changeTaskID,
			ChangeTaskAttemptID: changeTaskAttemptID,
			OccurredAt:          time.Time{},
			Level:               faker.Word(),
			Step:                sql.NullString{String: faker.Word(), Valid: true},
			Message:             faker.Word(),
			Metadata:            json.RawMessage{},
		},
	}

	for _, opt := range opts {
		opt(f)
	}

	return f.ChangeLogEntity
}

func CreateChangeLog(ctx context.Context, exec storage.Executor, changeID uuid.UUID, changeTaskID *uuid.UUID, changeTaskAttemptID *uuid.UUID, opts ...ChangeLogOption) (models.ChangeLogEntity, error) {
	built := BuildChangeLog(changeID, changeTaskID, changeTaskAttemptID, opts...)

	entity := models.ChangeLogEntity{
		ID:                  built.ID,
		CreatedAt:           time.Now(),
		UpdatedAt:           time.Now(),
		ChangeID:            built.ChangeID,
		ChangeTaskID:        built.ChangeTaskID,
		ChangeTaskAttemptID: built.ChangeTaskAttemptID,
		OccurredAt:          built.OccurredAt,
		Level:               built.Level,
		Step:                built.Step,
		Message:             built.Message,
		Metadata:            built.Metadata,
	}

	if err := exec.NewInsert().Model(&entity).Returning("*").Scan(ctx); err != nil {
		return models.ChangeLogEntity{}, err
	}

	return entity, nil
}

func CreateChangeLogs(ctx context.Context, exec storage.Executor, changeID uuid.UUID, changeTaskID *uuid.UUID, changeTaskAttemptID *uuid.UUID, count int, opts ...ChangeLogOption) ([]models.ChangeLogEntity, error) {
	changelogs := make([]models.ChangeLogEntity, 0, count)

	for i := range count {
		entity, err := CreateChangeLog(ctx, exec, changeID, changeTaskID, changeTaskAttemptID, opts...)
		if err != nil {
			return nil, fmt.Errorf("failed to create changelog %d: %w", i+1, err)
		}
		changelogs = append(changelogs, entity)
	}

	return changelogs, nil
}

func WithChangeLogsChangeID(value uuid.UUID) ChangeLogOption {
	return func(f *ChangeLogFactory) {
		f.ChangeLogEntity.ChangeID = value
	}
}

func WithChangeLogsChangeTaskID(value *uuid.UUID) ChangeLogOption {
	return func(f *ChangeLogFactory) {
		f.ChangeLogEntity.ChangeTaskID = value
	}
}

func WithChangeLogsChangeTaskAttemptID(value *uuid.UUID) ChangeLogOption {
	return func(f *ChangeLogFactory) {
		f.ChangeLogEntity.ChangeTaskAttemptID = value
	}
}

func WithChangeLogsOccurredAt(value time.Time) ChangeLogOption {
	return func(f *ChangeLogFactory) {
		f.ChangeLogEntity.OccurredAt = value
	}
}

func WithChangeLogsLevel(value string) ChangeLogOption {
	return func(f *ChangeLogFactory) {
		f.ChangeLogEntity.Level = value
	}
}

func WithChangeLogsStep(value sql.NullString) ChangeLogOption {
	return func(f *ChangeLogFactory) {
		f.ChangeLogEntity.Step = value
	}
}

func WithChangeLogsMessage(value string) ChangeLogOption {
	return func(f *ChangeLogFactory) {
		f.ChangeLogEntity.Message = value
	}
}

func WithChangeLogsMetadata(value json.RawMessage) ChangeLogOption {
	return func(f *ChangeLogFactory) {
		f.ChangeLogEntity.Metadata = value
	}
}
