package factories

import (
	"context"
	"database/sql"
	"deploycrate-ce/internal/storage"
	"deploycrate-ce/models"
	"encoding/json"
	"fmt"
	"time"

	"github.com/go-faker/faker/v4"
	"github.com/google/uuid"
)

// Factory declarations below are generated by Andurel.

type ChangeFactory struct {
	models.ChangeEntity
}

type ChangeOption func(*ChangeFactory)

func BuildChange(environmentID uuid.UUID, actorID *uuid.UUID, correctsChangeID *uuid.UUID, correlationID uuid.UUID, opts ...ChangeOption) models.ChangeEntity {
	f := &ChangeFactory{
		ChangeEntity: models.ChangeEntity{
			EnvironmentID:     environmentID,
			Sequence:          randomInt64(1, 1000, 100),
			Kind:              faker.Word(),
			TriggerType:       faker.Word(),
			ActorType:         faker.Word(),
			ActorID:           actorID,
			CorrectsChangeID:  correctsChangeID,
			CauseSystem:       sql.NullString{String: faker.Word(), Valid: true},
			CauseReference:    sql.NullString{String: faker.Word(), Valid: true},
			CorrelationID:     correlationID,
			CorrectionContext: json.RawMessage{},
			Summary:           faker.Word(),
			Status:            faker.Word(),
			RequestedAt:       time.Time{},
			CommittedAt:       sql.NullTime{Time: time.Now(), Valid: true},
			StartedAt:         sql.NullTime{Time: time.Now(), Valid: true},
			FinishedAt:        sql.NullTime{Time: time.Now(), Valid: true},
			CancelledAt:       sql.NullTime{Time: time.Now(), Valid: true},
			Error:             sql.NullString{String: faker.Word(), Valid: true},
		},
	}

	for _, opt := range opts {
		opt(f)
	}

	return f.ChangeEntity
}

func CreateChange(ctx context.Context, exec storage.Executor, environmentID uuid.UUID, actorID *uuid.UUID, correctsChangeID *uuid.UUID, correlationID uuid.UUID, opts ...ChangeOption) (models.ChangeEntity, error) {
	built := BuildChange(environmentID, actorID, correctsChangeID, correlationID, opts...)

	entity := models.ChangeEntity{
		ID:                uuid.New(),
		CreatedAt:         time.Now(),
		UpdatedAt:         time.Now(),
		EnvironmentID:     built.EnvironmentID,
		Sequence:          built.Sequence,
		Kind:              built.Kind,
		TriggerType:       built.TriggerType,
		ActorType:         built.ActorType,
		ActorID:           built.ActorID,
		CorrectsChangeID:  built.CorrectsChangeID,
		CauseSystem:       built.CauseSystem,
		CauseReference:    built.CauseReference,
		CorrelationID:     built.CorrelationID,
		CorrectionContext: built.CorrectionContext,
		Summary:           built.Summary,
		Status:            built.Status,
		RequestedAt:       built.RequestedAt,
		CommittedAt:       built.CommittedAt,
		StartedAt:         built.StartedAt,
		FinishedAt:        built.FinishedAt,
		CancelledAt:       built.CancelledAt,
		Error:             built.Error,
	}

	if err := exec.NewInsert().Model(&entity).Returning("*").Scan(ctx); err != nil {
		return models.ChangeEntity{}, err
	}

	return entity, nil
}

func CreateChanges(ctx context.Context, exec storage.Executor, environmentID uuid.UUID, actorID *uuid.UUID, correctsChangeID *uuid.UUID, correlationID uuid.UUID, count int, opts ...ChangeOption) ([]models.ChangeEntity, error) {
	changes := make([]models.ChangeEntity, 0, count)

	for i := range count {
		entity, err := CreateChange(ctx, exec, environmentID, actorID, correctsChangeID, correlationID, opts...)
		if err != nil {
			return nil, fmt.Errorf("failed to create change %d: %w", i+1, err)
		}
		changes = append(changes, entity)
	}

	return changes, nil
}

func WithChangesEnvironmentID(value uuid.UUID) ChangeOption {
	return func(f *ChangeFactory) {
		f.ChangeEntity.EnvironmentID = value
	}
}

func WithChangesSequence(value int64) ChangeOption {
	return func(f *ChangeFactory) {
		f.ChangeEntity.Sequence = value
	}
}

func WithChangesKind(value string) ChangeOption {
	return func(f *ChangeFactory) {
		f.ChangeEntity.Kind = value
	}
}

func WithChangesTriggerType(value string) ChangeOption {
	return func(f *ChangeFactory) {
		f.ChangeEntity.TriggerType = value
	}
}

func WithChangesActorType(value string) ChangeOption {
	return func(f *ChangeFactory) {
		f.ChangeEntity.ActorType = value
	}
}

func WithChangesActorID(value *uuid.UUID) ChangeOption {
	return func(f *ChangeFactory) {
		f.ChangeEntity.ActorID = value
	}
}

func WithChangesCorrectsChangeID(value *uuid.UUID) ChangeOption {
	return func(f *ChangeFactory) {
		f.ChangeEntity.CorrectsChangeID = value
	}
}

func WithChangesCauseSystem(value sql.NullString) ChangeOption {
	return func(f *ChangeFactory) {
		f.ChangeEntity.CauseSystem = value
	}
}

func WithChangesCauseReference(value sql.NullString) ChangeOption {
	return func(f *ChangeFactory) {
		f.ChangeEntity.CauseReference = value
	}
}

func WithChangesCorrelationID(value uuid.UUID) ChangeOption {
	return func(f *ChangeFactory) {
		f.ChangeEntity.CorrelationID = value
	}
}

func WithChangesCorrectionContext(value json.RawMessage) ChangeOption {
	return func(f *ChangeFactory) {
		f.ChangeEntity.CorrectionContext = value
	}
}

func WithChangesSummary(value string) ChangeOption {
	return func(f *ChangeFactory) {
		f.ChangeEntity.Summary = value
	}
}

func WithChangesStatus(value string) ChangeOption {
	return func(f *ChangeFactory) {
		f.ChangeEntity.Status = value
	}
}

func WithChangesRequestedAt(value time.Time) ChangeOption {
	return func(f *ChangeFactory) {
		f.ChangeEntity.RequestedAt = value
	}
}

func WithChangesCommittedAt(value sql.NullTime) ChangeOption {
	return func(f *ChangeFactory) {
		f.ChangeEntity.CommittedAt = value
	}
}

func WithChangesStartedAt(value sql.NullTime) ChangeOption {
	return func(f *ChangeFactory) {
		f.ChangeEntity.StartedAt = value
	}
}

func WithChangesFinishedAt(value sql.NullTime) ChangeOption {
	return func(f *ChangeFactory) {
		f.ChangeEntity.FinishedAt = value
	}
}

func WithChangesCancelledAt(value sql.NullTime) ChangeOption {
	return func(f *ChangeFactory) {
		f.ChangeEntity.CancelledAt = value
	}
}

func WithChangesError(value sql.NullString) ChangeOption {
	return func(f *ChangeFactory) {
		f.ChangeEntity.Error = value
	}
}
