package factories

import (
	"context"
	"deploycrate-ce/internal/storage"
	"deploycrate-ce/models"
	"fmt"
	"time"

	"github.com/google/uuid"
)

// Factory declarations below are generated by Andurel.

type ChangeReleaseFactory struct {
	models.ChangeReleaseEntity
}

type ChangeReleaseOption func(*ChangeReleaseFactory)

func BuildChangeRelease(changeID uuid.UUID, releaseID uuid.UUID, opts ...ChangeReleaseOption) models.ChangeReleaseEntity {
	f := &ChangeReleaseFactory{
		ChangeReleaseEntity: models.ChangeReleaseEntity{
			ChangeID:  changeID,
			ReleaseID: releaseID,
		},
	}

	for _, opt := range opts {
		opt(f)
	}

	return f.ChangeReleaseEntity
}

func CreateChangeRelease(ctx context.Context, exec storage.Executor, changeID uuid.UUID, releaseID uuid.UUID, opts ...ChangeReleaseOption) (models.ChangeReleaseEntity, error) {
	built := BuildChangeRelease(changeID, releaseID, opts...)

	entity := models.ChangeReleaseEntity{
		ID:        built.ID,
		CreatedAt: time.Now(),
		UpdatedAt: time.Now(),
		ChangeID:  built.ChangeID,
		ReleaseID: built.ReleaseID,
	}

	if err := exec.NewInsert().Model(&entity).Returning("*").Scan(ctx); err != nil {
		return models.ChangeReleaseEntity{}, err
	}

	return entity, nil
}

func CreateChangeReleases(ctx context.Context, exec storage.Executor, changeID uuid.UUID, releaseID uuid.UUID, count int, opts ...ChangeReleaseOption) ([]models.ChangeReleaseEntity, error) {
	changereleases := make([]models.ChangeReleaseEntity, 0, count)

	for i := range count {
		entity, err := CreateChangeRelease(ctx, exec, changeID, releaseID, opts...)
		if err != nil {
			return nil, fmt.Errorf("failed to create changerelease %d: %w", i+1, err)
		}
		changereleases = append(changereleases, entity)
	}

	return changereleases, nil
}

func WithChangeReleasesChangeID(value uuid.UUID) ChangeReleaseOption {
	return func(f *ChangeReleaseFactory) {
		f.ChangeReleaseEntity.ChangeID = value
	}
}

func WithChangeReleasesReleaseID(value uuid.UUID) ChangeReleaseOption {
	return func(f *ChangeReleaseFactory) {
		f.ChangeReleaseEntity.ReleaseID = value
	}
}
