package factories

import (
	"context"
	"deploycrate-ce/internal/storage"
	"deploycrate-ce/models"
	"encoding/json"
	"fmt"
	"time"

	"github.com/go-faker/faker/v4"
	"github.com/google/uuid"
)

// Factory declarations below are generated by Andurel.

type ChangeTaskFactory struct {
	models.ChangeTaskEntity
}

type ChangeTaskOption func(*ChangeTaskFactory)

func BuildChangeTask(changeID uuid.UUID, parentTaskID *uuid.UUID, serverID *uuid.UUID, environmentTargetID *uuid.UUID, subjectID uuid.UUID, opts ...ChangeTaskOption) models.ChangeTaskEntity {
	f := &ChangeTaskFactory{
		ChangeTaskEntity: models.ChangeTaskEntity{
			ChangeID:            changeID,
			ParentTaskID:        parentTaskID,
			ServerID:            serverID,
			EnvironmentTargetID: environmentTargetID,
			Kind:                faker.Word(),
			SubjectType:         faker.Word(),
			SubjectID:           subjectID,
			IdempotencyKey:      faker.Word(),
			Input:               json.RawMessage{},
			Status:              faker.Word(),
			AttemptCount:        randomInt(1, 1000, 100),
			AvailableAt:         time.Time{},
		},
	}

	for _, opt := range opts {
		opt(f)
	}

	return f.ChangeTaskEntity
}

func CreateChangeTask(ctx context.Context, exec storage.Executor, changeID uuid.UUID, parentTaskID *uuid.UUID, serverID *uuid.UUID, environmentTargetID *uuid.UUID, subjectID uuid.UUID, opts ...ChangeTaskOption) (models.ChangeTaskEntity, error) {
	built := BuildChangeTask(changeID, parentTaskID, serverID, environmentTargetID, subjectID, opts...)

	entity := models.ChangeTaskEntity{
		ID:                  uuid.New(),
		CreatedAt:           time.Now(),
		UpdatedAt:           time.Now(),
		ChangeID:            built.ChangeID,
		ParentTaskID:        built.ParentTaskID,
		ServerID:            built.ServerID,
		EnvironmentTargetID: built.EnvironmentTargetID,
		Kind:                built.Kind,
		SubjectType:         built.SubjectType,
		SubjectID:           built.SubjectID,
		IdempotencyKey:      built.IdempotencyKey,
		Input:               built.Input,
		Status:              built.Status,
		AttemptCount:        built.AttemptCount,
		AvailableAt:         built.AvailableAt,
	}

	if err := exec.NewInsert().Model(&entity).Returning("*").Scan(ctx); err != nil {
		return models.ChangeTaskEntity{}, err
	}

	return entity, nil
}

func CreateChangeTasks(ctx context.Context, exec storage.Executor, changeID uuid.UUID, parentTaskID *uuid.UUID, serverID *uuid.UUID, environmentTargetID *uuid.UUID, subjectID uuid.UUID, count int, opts ...ChangeTaskOption) ([]models.ChangeTaskEntity, error) {
	changetasks := make([]models.ChangeTaskEntity, 0, count)

	for i := range count {
		entity, err := CreateChangeTask(ctx, exec, changeID, parentTaskID, serverID, environmentTargetID, subjectID, opts...)
		if err != nil {
			return nil, fmt.Errorf("failed to create changetask %d: %w", i+1, err)
		}
		changetasks = append(changetasks, entity)
	}

	return changetasks, nil
}

func WithChangeTasksChangeID(value uuid.UUID) ChangeTaskOption {
	return func(f *ChangeTaskFactory) {
		f.ChangeTaskEntity.ChangeID = value
	}
}

func WithChangeTasksParentTaskID(value *uuid.UUID) ChangeTaskOption {
	return func(f *ChangeTaskFactory) {
		f.ChangeTaskEntity.ParentTaskID = value
	}
}

func WithChangeTasksServerID(value *uuid.UUID) ChangeTaskOption {
	return func(f *ChangeTaskFactory) {
		f.ChangeTaskEntity.ServerID = value
	}
}

func WithChangeTasksEnvironmentTargetID(value *uuid.UUID) ChangeTaskOption {
	return func(f *ChangeTaskFactory) {
		f.ChangeTaskEntity.EnvironmentTargetID = value
	}
}

func WithChangeTasksKind(value string) ChangeTaskOption {
	return func(f *ChangeTaskFactory) {
		f.ChangeTaskEntity.Kind = value
	}
}

func WithChangeTasksSubjectType(value string) ChangeTaskOption {
	return func(f *ChangeTaskFactory) {
		f.ChangeTaskEntity.SubjectType = value
	}
}

func WithChangeTasksSubjectID(value uuid.UUID) ChangeTaskOption {
	return func(f *ChangeTaskFactory) {
		f.ChangeTaskEntity.SubjectID = value
	}
}

func WithChangeTasksIdempotencyKey(value string) ChangeTaskOption {
	return func(f *ChangeTaskFactory) {
		f.ChangeTaskEntity.IdempotencyKey = value
	}
}

func WithChangeTasksInput(value json.RawMessage) ChangeTaskOption {
	return func(f *ChangeTaskFactory) {
		f.ChangeTaskEntity.Input = value
	}
}

func WithChangeTasksStatus(value string) ChangeTaskOption {
	return func(f *ChangeTaskFactory) {
		f.ChangeTaskEntity.Status = value
	}
}

func WithChangeTasksAttemptCount(value int32) ChangeTaskOption {
	return func(f *ChangeTaskFactory) {
		f.ChangeTaskEntity.AttemptCount = value
	}
}

func WithChangeTasksAvailableAt(value time.Time) ChangeTaskOption {
	return func(f *ChangeTaskFactory) {
		f.ChangeTaskEntity.AvailableAt = value
	}
}
