package factories

import (
	"context"
	"deploycrate-ce/internal/storage"
	"deploycrate-ce/models"
	"fmt"
	"time"

	"github.com/go-faker/faker/v4"
	"github.com/google/uuid"
)

// Factory declarations below are generated by Andurel.

type ChangeStateRevisionFactory struct {
	models.ChangeStateRevisionEntity
}

type ChangeStateRevisionOption func(*ChangeStateRevisionFactory)

func BuildChangeStateRevision(
	changeID uuid.UUID,
	environmentStateRevisionID uuid.UUID,
	opts ...ChangeStateRevisionOption,
) models.ChangeStateRevisionEntity {
	f := &ChangeStateRevisionFactory{
		ChangeStateRevisionEntity: models.ChangeStateRevisionEntity{
			Role:                       faker.Word(),
			ChangeID:                   changeID,
			EnvironmentStateRevisionID: environmentStateRevisionID,
		},
	}

	for _, opt := range opts {
		opt(f)
	}

	return f.ChangeStateRevisionEntity
}

func CreateChangeStateRevision(
	ctx context.Context,
	exec storage.Executor,
	changeID uuid.UUID,
	environmentStateRevisionID uuid.UUID,
	opts ...ChangeStateRevisionOption,
) (models.ChangeStateRevisionEntity, error) {
	built := BuildChangeStateRevision(changeID, environmentStateRevisionID, opts...)

	entity := models.ChangeStateRevisionEntity{
		ID:                         built.ID,
		CreatedAt:                  time.Now(),
		UpdatedAt:                  time.Now(),
		Role:                       built.Role,
		ChangeID:                   built.ChangeID,
		EnvironmentStateRevisionID: built.EnvironmentStateRevisionID,
	}

	if err := exec.NewInsert().Model(&entity).Returning("*").Scan(ctx); err != nil {
		return models.ChangeStateRevisionEntity{}, err
	}

	return entity, nil
}

func CreateChangeStateRevisions(
	ctx context.Context,
	exec storage.Executor,
	changeID uuid.UUID,
	environmentStateRevisionID uuid.UUID,
	count int,
	opts ...ChangeStateRevisionOption,
) ([]models.ChangeStateRevisionEntity, error) {
	changestaterevisions := make([]models.ChangeStateRevisionEntity, 0, count)

	for i := range count {
		entity, err := CreateChangeStateRevision(
			ctx,
			exec,
			changeID,
			environmentStateRevisionID,
			opts...)
		if err != nil {
			return nil, fmt.Errorf("failed to create changestaterevision %d: %w", i+1, err)
		}
		changestaterevisions = append(changestaterevisions, entity)
	}

	return changestaterevisions, nil
}

func WithChangeStateRevisionsRole(value string) ChangeStateRevisionOption {
	return func(f *ChangeStateRevisionFactory) {
		f.ChangeStateRevisionEntity.Role = value
	}
}

func WithChangeStateRevisionsChangeID(value uuid.UUID) ChangeStateRevisionOption {
	return func(f *ChangeStateRevisionFactory) {
		f.ChangeStateRevisionEntity.ChangeID = value
	}
}

func WithChangeStateRevisionsEnvironmentStateRevisionID(value uuid.UUID) ChangeStateRevisionOption {
	return func(f *ChangeStateRevisionFactory) {
		f.ChangeStateRevisionEntity.EnvironmentStateRevisionID = value
	}
}
