package factories

import (
	"context"
	"database/sql"
	"deploycrate-ce/internal/storage"
	"deploycrate-ce/models"
	"fmt"
	"github.com/go-faker/faker/v4"
	"github.com/google/uuid"
	"time"
)

// Factory declarations below are generated by Andurel.

type ContainerRegistryFactory struct {
	models.ContainerRegistryEntity
}

type ContainerRegistryOption func(*ContainerRegistryFactory)

func BuildContainerRegistry(credentialID uuid.UUID, opts ...ContainerRegistryOption) models.ContainerRegistryEntity {
	f := &ContainerRegistryFactory{
		ContainerRegistryEntity: models.ContainerRegistryEntity{
			ArchivedAt:   sql.NullTime{Time: time.Now(), Valid: true},
			Name:         faker.Word(),
			Provider:     faker.Word(),
			Endpoint:     faker.Word(),
			CredentialID: credentialID,
		},
	}

	for _, opt := range opts {
		opt(f)
	}

	return f.ContainerRegistryEntity
}

func CreateContainerRegistry(ctx context.Context, exec storage.Executor, credentialID uuid.UUID, opts ...ContainerRegistryOption) (models.ContainerRegistryEntity, error) {
	built := BuildContainerRegistry(credentialID, opts...)

	entity := models.ContainerRegistryEntity{
		ID:           uuid.New(),
		CreatedAt:    time.Now(),
		UpdatedAt:    time.Now(),
		ArchivedAt:   built.ArchivedAt,
		Name:         built.Name,
		Provider:     built.Provider,
		Endpoint:     built.Endpoint,
		CredentialID: built.CredentialID,
	}

	if err := exec.NewInsert().Model(&entity).Returning("*").Scan(ctx); err != nil {
		return models.ContainerRegistryEntity{}, err
	}

	return entity, nil
}

func CreateContainerRegistrys(ctx context.Context, exec storage.Executor, credentialID uuid.UUID, count int, opts ...ContainerRegistryOption) ([]models.ContainerRegistryEntity, error) {
	containerregistrys := make([]models.ContainerRegistryEntity, 0, count)

	for i := range count {
		entity, err := CreateContainerRegistry(ctx, exec, credentialID, opts...)
		if err != nil {
			return nil, fmt.Errorf("failed to create containerregistry %d: %w", i+1, err)
		}
		containerregistrys = append(containerregistrys, entity)
	}

	return containerregistrys, nil
}

func WithContainerRegistriesArchivedAt(value sql.NullTime) ContainerRegistryOption {
	return func(f *ContainerRegistryFactory) {
		f.ContainerRegistryEntity.ArchivedAt = value
	}
}

func WithContainerRegistriesName(value string) ContainerRegistryOption {
	return func(f *ContainerRegistryFactory) {
		f.ContainerRegistryEntity.Name = value
	}
}

func WithContainerRegistriesProvider(value string) ContainerRegistryOption {
	return func(f *ContainerRegistryFactory) {
		f.ContainerRegistryEntity.Provider = value
	}
}

func WithContainerRegistriesEndpoint(value string) ContainerRegistryOption {
	return func(f *ContainerRegistryFactory) {
		f.ContainerRegistryEntity.Endpoint = value
	}
}

func WithContainerRegistriesCredentialID(value uuid.UUID) ContainerRegistryOption {
	return func(f *ContainerRegistryFactory) {
		f.ContainerRegistryEntity.CredentialID = value
	}
}
