package factories

import (
	"context"
	"database/sql"
	"deploycrate-ce/internal/storage"
	"deploycrate-ce/models"
	"encoding/json"
	"fmt"
	"time"

	"github.com/go-faker/faker/v4"
	"github.com/google/uuid"
)

// Factory declarations below are generated by Andurel.

type CredentialFactory struct {
	models.CredentialEntity
}

type CredentialOption func(*CredentialFactory)

func BuildCredential(opts ...CredentialOption) models.CredentialEntity {
	f := &CredentialFactory{
		CredentialEntity: models.CredentialEntity{
			Name:       faker.Word(),
			Provider:   faker.Word(),
			Metadata:   json.RawMessage{},
			EncPayload: []byte{},
			VerifiedAt: sql.NullTime{Time: time.Now(), Valid: true},
			LastUsedAt: sql.NullTime{Time: time.Now(), Valid: true},
			ArchivedAt: sql.NullTime{Time: time.Now(), Valid: true},
		},
	}

	for _, opt := range opts {
		opt(f)
	}

	return f.CredentialEntity
}

func CreateCredential(
	ctx context.Context,
	exec storage.Executor,
	opts ...CredentialOption,
) (models.CredentialEntity, error) {
	built := BuildCredential(opts...)

	entity := models.CredentialEntity{
		ID:         uuid.New(),
		CreatedAt:  time.Now(),
		UpdatedAt:  time.Now(),
		Name:       built.Name,
		Provider:   built.Provider,
		Metadata:   built.Metadata,
		EncPayload: built.EncPayload,
		VerifiedAt: built.VerifiedAt,
		LastUsedAt: built.LastUsedAt,
		ArchivedAt: built.ArchivedAt,
	}

	if err := exec.NewInsert().Model(&entity).Returning("*").Scan(ctx); err != nil {
		return models.CredentialEntity{}, err
	}

	return entity, nil
}

func CreateCredentials(
	ctx context.Context,
	exec storage.Executor,
	count int,
	opts ...CredentialOption,
) ([]models.CredentialEntity, error) {
	credentials := make([]models.CredentialEntity, 0, count)

	for i := range count {
		entity, err := CreateCredential(ctx, exec, opts...)
		if err != nil {
			return nil, fmt.Errorf("failed to create credential %d: %w", i+1, err)
		}
		credentials = append(credentials, entity)
	}

	return credentials, nil
}

func WithCredentialsName(value string) CredentialOption {
	return func(f *CredentialFactory) {
		f.CredentialEntity.Name = value
	}
}

func WithCredentialsProvider(value string) CredentialOption {
	return func(f *CredentialFactory) {
		f.CredentialEntity.Provider = value
	}
}

func WithCredentialsMetadata(value json.RawMessage) CredentialOption {
	return func(f *CredentialFactory) {
		f.CredentialEntity.Metadata = value
	}
}

func WithCredentialsEncPayload(value []byte) CredentialOption {
	return func(f *CredentialFactory) {
		f.CredentialEntity.EncPayload = value
	}
}

func WithCredentialsVerifiedAt(value sql.NullTime) CredentialOption {
	return func(f *CredentialFactory) {
		f.CredentialEntity.VerifiedAt = value
	}
}

func WithCredentialsLastUsedAt(value sql.NullTime) CredentialOption {
	return func(f *CredentialFactory) {
		f.CredentialEntity.LastUsedAt = value
	}
}

func WithCredentialsArchivedAt(value sql.NullTime) CredentialOption {
	return func(f *CredentialFactory) {
		f.CredentialEntity.ArchivedAt = value
	}
}
