package factories

import (
	"context"
	"database/sql"
	"deploycrate-ce/internal/storage"
	"deploycrate-ce/models"
	"encoding/json"
	"fmt"
	"time"

	"github.com/go-faker/faker/v4"
	"github.com/google/uuid"
)

// Factory declarations below are generated by Andurel.

type DeploymentEventFactory struct {
	models.DeploymentEventEntity
}

type DeploymentEventOption func(*DeploymentEventFactory)

func BuildDeploymentEvent(
	deploymentID uuid.UUID,
	changeTaskAttemptID *uuid.UUID,
	opts ...DeploymentEventOption,
) models.DeploymentEventEntity {
	f := &DeploymentEventFactory{
		DeploymentEventEntity: models.DeploymentEventEntity{
			Sequence:            randomInt64(1, 1000, 100),
			EventType:           faker.Word(),
			Status:              sql.NullString{String: faker.Word(), Valid: true},
			Step:                sql.NullString{String: faker.Word(), Valid: true},
			Message:             faker.Word(),
			Metadata:            json.RawMessage{},
			Error:               sql.NullString{String: faker.Word(), Valid: true},
			OccurredAt:          time.Time{},
			DeploymentID:        deploymentID,
			ChangeTaskAttemptID: changeTaskAttemptID,
		},
	}

	for _, opt := range opts {
		opt(f)
	}

	return f.DeploymentEventEntity
}

func CreateDeploymentEvent(
	ctx context.Context,
	exec storage.Executor,
	deploymentID uuid.UUID,
	changeTaskAttemptID *uuid.UUID,
	opts ...DeploymentEventOption,
) (models.DeploymentEventEntity, error) {
	built := BuildDeploymentEvent(deploymentID, changeTaskAttemptID, opts...)

	entity := models.DeploymentEventEntity{
		ID:                  uuid.New(),
		CreatedAt:           time.Now(),
		UpdatedAt:           time.Now(),
		Sequence:            built.Sequence,
		EventType:           built.EventType,
		Status:              built.Status,
		Step:                built.Step,
		Message:             built.Message,
		Metadata:            built.Metadata,
		Error:               built.Error,
		OccurredAt:          built.OccurredAt,
		DeploymentID:        built.DeploymentID,
		ChangeTaskAttemptID: built.ChangeTaskAttemptID,
	}

	if err := exec.NewInsert().Model(&entity).Returning("*").Scan(ctx); err != nil {
		return models.DeploymentEventEntity{}, err
	}

	return entity, nil
}

func CreateDeploymentEvents(
	ctx context.Context,
	exec storage.Executor,
	deploymentID uuid.UUID,
	changeTaskAttemptID *uuid.UUID,
	count int,
	opts ...DeploymentEventOption,
) ([]models.DeploymentEventEntity, error) {
	deploymentevents := make([]models.DeploymentEventEntity, 0, count)

	for i := range count {
		entity, err := CreateDeploymentEvent(ctx, exec, deploymentID, changeTaskAttemptID, opts...)
		if err != nil {
			return nil, fmt.Errorf("failed to create deploymentevent %d: %w", i+1, err)
		}
		deploymentevents = append(deploymentevents, entity)
	}

	return deploymentevents, nil
}

func WithDeploymentEventsSequence(value int64) DeploymentEventOption {
	return func(f *DeploymentEventFactory) {
		f.DeploymentEventEntity.Sequence = value
	}
}

func WithDeploymentEventsEventType(value string) DeploymentEventOption {
	return func(f *DeploymentEventFactory) {
		f.DeploymentEventEntity.EventType = value
	}
}

func WithDeploymentEventsStatus(value sql.NullString) DeploymentEventOption {
	return func(f *DeploymentEventFactory) {
		f.DeploymentEventEntity.Status = value
	}
}

func WithDeploymentEventsStep(value sql.NullString) DeploymentEventOption {
	return func(f *DeploymentEventFactory) {
		f.DeploymentEventEntity.Step = value
	}
}

func WithDeploymentEventsMessage(value string) DeploymentEventOption {
	return func(f *DeploymentEventFactory) {
		f.DeploymentEventEntity.Message = value
	}
}

func WithDeploymentEventsMetadata(value json.RawMessage) DeploymentEventOption {
	return func(f *DeploymentEventFactory) {
		f.DeploymentEventEntity.Metadata = value
	}
}

func WithDeploymentEventsError(value sql.NullString) DeploymentEventOption {
	return func(f *DeploymentEventFactory) {
		f.DeploymentEventEntity.Error = value
	}
}

func WithDeploymentEventsOccurredAt(value time.Time) DeploymentEventOption {
	return func(f *DeploymentEventFactory) {
		f.DeploymentEventEntity.OccurredAt = value
	}
}

func WithDeploymentEventsDeploymentID(value uuid.UUID) DeploymentEventOption {
	return func(f *DeploymentEventFactory) {
		f.DeploymentEventEntity.DeploymentID = value
	}
}

func WithDeploymentEventsChangeTaskAttemptID(value *uuid.UUID) DeploymentEventOption {
	return func(f *DeploymentEventFactory) {
		f.DeploymentEventEntity.ChangeTaskAttemptID = value
	}
}
