package factories

import (
	"context"
	"database/sql"
	"deploycrate-ce/internal/storage"
	"deploycrate-ce/models"
	"encoding/json"
	"fmt"
	"time"

	"github.com/go-faker/faker/v4"
	"github.com/google/uuid"
)

// Factory declarations below are generated by Andurel.

type DeploymentFactory struct {
	models.DeploymentEntity
}

type DeploymentOption func(*DeploymentFactory)

func BuildDeployment(changeID uuid.UUID, releaseID uuid.UUID, environmentTargetID uuid.UUID, opts ...DeploymentOption) models.DeploymentEntity {
	f := &DeploymentFactory{
		DeploymentEntity: models.DeploymentEntity{
			Attempt:              randomInt(1, 1000, 100),
			Strategy:             json.RawMessage{},
			ProcessConfiguration: json.RawMessage{},
			RuntimeConfiguration: json.RawMessage{},
			Status:               faker.Word(),
			CurrentStep:          sql.NullString{String: faker.Word(), Valid: true},
			StartedAt:            sql.NullTime{Time: time.Now(), Valid: true},
			FinishedAt:           sql.NullTime{Time: time.Now(), Valid: true},
			Error:                sql.NullString{String: faker.Word(), Valid: true},
			ChangeID:             changeID,
			ReleaseID:            releaseID,
			EnvironmentTargetID:  environmentTargetID,
		},
	}

	for _, opt := range opts {
		opt(f)
	}

	return f.DeploymentEntity
}

func CreateDeployment(ctx context.Context, exec storage.Executor, changeID uuid.UUID, releaseID uuid.UUID, environmentTargetID uuid.UUID, opts ...DeploymentOption) (models.DeploymentEntity, error) {
	built := BuildDeployment(changeID, releaseID, environmentTargetID, opts...)

	entity := models.DeploymentEntity{
		ID:                   uuid.New(),
		CreatedAt:            time.Now(),
		UpdatedAt:            time.Now(),
		Attempt:              built.Attempt,
		Strategy:             built.Strategy,
		ProcessConfiguration: built.ProcessConfiguration,
		RuntimeConfiguration: built.RuntimeConfiguration,
		Status:               built.Status,
		CurrentStep:          built.CurrentStep,
		StartedAt:            built.StartedAt,
		FinishedAt:           built.FinishedAt,
		Error:                built.Error,
		ChangeID:             built.ChangeID,
		ReleaseID:            built.ReleaseID,
		EnvironmentTargetID:  built.EnvironmentTargetID,
	}

	if err := exec.NewInsert().Model(&entity).Returning("*").Scan(ctx); err != nil {
		return models.DeploymentEntity{}, err
	}

	return entity, nil
}

func CreateDeployments(ctx context.Context, exec storage.Executor, changeID uuid.UUID, releaseID uuid.UUID, environmentTargetID uuid.UUID, count int, opts ...DeploymentOption) ([]models.DeploymentEntity, error) {
	deployments := make([]models.DeploymentEntity, 0, count)

	for i := range count {
		entity, err := CreateDeployment(ctx, exec, changeID, releaseID, environmentTargetID, opts...)
		if err != nil {
			return nil, fmt.Errorf("failed to create deployment %d: %w", i+1, err)
		}
		deployments = append(deployments, entity)
	}

	return deployments, nil
}

func WithDeploymentsAttempt(value int32) DeploymentOption {
	return func(f *DeploymentFactory) {
		f.DeploymentEntity.Attempt = value
	}
}

func WithDeploymentsStrategy(value json.RawMessage) DeploymentOption {
	return func(f *DeploymentFactory) {
		f.DeploymentEntity.Strategy = value
	}
}

func WithDeploymentsProcessConfiguration(value json.RawMessage) DeploymentOption {
	return func(f *DeploymentFactory) {
		f.DeploymentEntity.ProcessConfiguration = value
	}
}

func WithDeploymentsRuntimeConfiguration(value json.RawMessage) DeploymentOption {
	return func(f *DeploymentFactory) {
		f.DeploymentEntity.ProcessConfiguration = value
		f.DeploymentEntity.RuntimeConfiguration = value
	}
}

func WithDeploymentsStatus(value string) DeploymentOption {
	return func(f *DeploymentFactory) {
		f.DeploymentEntity.Status = value
	}
}

func WithDeploymentsCurrentStep(value sql.NullString) DeploymentOption {
	return func(f *DeploymentFactory) {
		f.DeploymentEntity.CurrentStep = value
	}
}

func WithDeploymentsStartedAt(value sql.NullTime) DeploymentOption {
	return func(f *DeploymentFactory) {
		f.DeploymentEntity.StartedAt = value
	}
}

func WithDeploymentsFinishedAt(value sql.NullTime) DeploymentOption {
	return func(f *DeploymentFactory) {
		f.DeploymentEntity.FinishedAt = value
	}
}

func WithDeploymentsError(value sql.NullString) DeploymentOption {
	return func(f *DeploymentFactory) {
		f.DeploymentEntity.Error = value
	}
}

func WithDeploymentsChangeID(value uuid.UUID) DeploymentOption {
	return func(f *DeploymentFactory) {
		f.DeploymentEntity.ChangeID = value
	}
}

func WithDeploymentsReleaseID(value uuid.UUID) DeploymentOption {
	return func(f *DeploymentFactory) {
		f.DeploymentEntity.ReleaseID = value
	}
}

func WithDeploymentsEnvironmentTargetID(value uuid.UUID) DeploymentOption {
	return func(f *DeploymentFactory) {
		f.DeploymentEntity.EnvironmentTargetID = value
	}
}
