package factories

import (
	"context"
	"database/sql"
	"deploycrate-ce/internal/storage"
	"deploycrate-ce/models"
	"encoding/json"
	"fmt"
	"time"

	"github.com/go-faker/faker/v4"
	"github.com/google/uuid"
)

// Factory declarations below are generated by Andurel.

type EnvironmentResourceFactory struct {
	models.EnvironmentResourceEntity
}

type EnvironmentResourceOption func(*EnvironmentResourceFactory)

func BuildEnvironmentResource(
	environmentID uuid.UUID,
	resourceID uuid.UUID,
	resourceEndpointID uuid.UUID,
	resourceCredentialID *uuid.UUID,
	opts ...EnvironmentResourceOption,
) models.EnvironmentResourceEntity {
	f := &EnvironmentResourceFactory{
		EnvironmentResourceEntity: models.EnvironmentResourceEntity{
			Alias:                faker.Word(),
			Configuration:        json.RawMessage{},
			ArchivedAt:           sql.NullTime{Time: time.Now(), Valid: true},
			EnvironmentID:        environmentID,
			ResourceID:           resourceID,
			ResourceEndpointID:   resourceEndpointID,
			ResourceCredentialID: resourceCredentialID,
		},
	}

	for _, opt := range opts {
		opt(f)
	}

	return f.EnvironmentResourceEntity
}

func CreateEnvironmentResource(
	ctx context.Context,
	exec storage.Executor,
	environmentID uuid.UUID,
	resourceID uuid.UUID,
	resourceEndpointID uuid.UUID,
	resourceCredentialID *uuid.UUID,
	opts ...EnvironmentResourceOption,
) (models.EnvironmentResourceEntity, error) {
	built := BuildEnvironmentResource(
		environmentID,
		resourceID,
		resourceEndpointID,
		resourceCredentialID,
		opts...)

	entity := models.EnvironmentResourceEntity{
		ID:                   uuid.New(),
		CreatedAt:            time.Now(),
		UpdatedAt:            time.Now(),
		Alias:                built.Alias,
		Configuration:        built.Configuration,
		ArchivedAt:           built.ArchivedAt,
		EnvironmentID:        built.EnvironmentID,
		ResourceID:           built.ResourceID,
		ResourceEndpointID:   built.ResourceEndpointID,
		ResourceCredentialID: built.ResourceCredentialID,
	}

	if err := exec.NewInsert().Model(&entity).Returning("*").Scan(ctx); err != nil {
		return models.EnvironmentResourceEntity{}, err
	}

	return entity, nil
}

func CreateEnvironmentResources(
	ctx context.Context,
	exec storage.Executor,
	environmentID uuid.UUID,
	resourceID uuid.UUID,
	resourceEndpointID uuid.UUID,
	resourceCredentialID *uuid.UUID,
	count int,
	opts ...EnvironmentResourceOption,
) ([]models.EnvironmentResourceEntity, error) {
	environmentresources := make([]models.EnvironmentResourceEntity, 0, count)

	for i := range count {
		entity, err := CreateEnvironmentResource(
			ctx,
			exec,
			environmentID,
			resourceID,
			resourceEndpointID,
			resourceCredentialID,
			opts...)
		if err != nil {
			return nil, fmt.Errorf("failed to create environmentresource %d: %w", i+1, err)
		}
		environmentresources = append(environmentresources, entity)
	}

	return environmentresources, nil
}

func WithEnvironmentResourcesAlias(value string) EnvironmentResourceOption {
	return func(f *EnvironmentResourceFactory) {
		f.EnvironmentResourceEntity.Alias = value
	}
}

func WithEnvironmentResourcesConfiguration(value json.RawMessage) EnvironmentResourceOption {
	return func(f *EnvironmentResourceFactory) {
		f.EnvironmentResourceEntity.Configuration = value
	}
}

func WithEnvironmentResourcesArchivedAt(value sql.NullTime) EnvironmentResourceOption {
	return func(f *EnvironmentResourceFactory) {
		f.EnvironmentResourceEntity.ArchivedAt = value
	}
}

func WithEnvironmentResourcesEnvironmentID(value uuid.UUID) EnvironmentResourceOption {
	return func(f *EnvironmentResourceFactory) {
		f.EnvironmentResourceEntity.EnvironmentID = value
	}
}

func WithEnvironmentResourcesResourceID(value uuid.UUID) EnvironmentResourceOption {
	return func(f *EnvironmentResourceFactory) {
		f.EnvironmentResourceEntity.ResourceID = value
	}
}

func WithEnvironmentResourcesResourceEndpointID(value uuid.UUID) EnvironmentResourceOption {
	return func(f *EnvironmentResourceFactory) {
		f.EnvironmentResourceEntity.ResourceEndpointID = value
	}
}

func WithEnvironmentResourcesResourceCredentialID(value *uuid.UUID) EnvironmentResourceOption {
	return func(f *EnvironmentResourceFactory) {
		f.EnvironmentResourceEntity.ResourceCredentialID = value
	}
}
