package factories

import (
	"context"
	"database/sql"
	"deploycrate-ce/internal/storage"
	"deploycrate-ce/models"
	"fmt"
	"time"

	"github.com/go-faker/faker/v4"
	"github.com/google/uuid"
)

// Factory declarations below are generated by Andurel.

type EnvironmentSecretFactory struct {
	models.EnvironmentSecretEntity
}

type EnvironmentSecretOption func(*EnvironmentSecretFactory)

func BuildEnvironmentSecret(sourceID uuid.UUID, environmentID uuid.UUID, opts ...EnvironmentSecretOption) models.EnvironmentSecretEntity {
	f := &EnvironmentSecretFactory{
		EnvironmentSecretEntity: models.EnvironmentSecretEntity{
			Key:           faker.Word(),
			EncValue:      []byte{},
			Digest:        []byte{},
			SourceType:    faker.Word(),
			SourceID:      sourceID,
			ArchivedAt:    sql.NullTime{Time: time.Now(), Valid: true},
			EnvironmentID: environmentID,
		},
	}

	for _, opt := range opts {
		opt(f)
	}

	return f.EnvironmentSecretEntity
}

func CreateEnvironmentSecret(ctx context.Context, exec storage.Executor, sourceID uuid.UUID, environmentID uuid.UUID, opts ...EnvironmentSecretOption) (models.EnvironmentSecretEntity, error) {
	built := BuildEnvironmentSecret(sourceID, environmentID, opts...)

	entity := models.EnvironmentSecretEntity{
		ID:            uuid.New(),
		CreatedAt:     time.Now(),
		UpdatedAt:     time.Now(),
		Key:           built.Key,
		EncValue:      built.EncValue,
		Digest:        built.Digest,
		SourceType:    built.SourceType,
		SourceID:      built.SourceID,
		ArchivedAt:    built.ArchivedAt,
		EnvironmentID: built.EnvironmentID,
	}

	if err := exec.NewInsert().Model(&entity).Returning("*").Scan(ctx); err != nil {
		return models.EnvironmentSecretEntity{}, err
	}

	return entity, nil
}

func CreateEnvironmentSecrets(ctx context.Context, exec storage.Executor, sourceID uuid.UUID, environmentID uuid.UUID, count int, opts ...EnvironmentSecretOption) ([]models.EnvironmentSecretEntity, error) {
	environmentsecrets := make([]models.EnvironmentSecretEntity, 0, count)

	for i := range count {
		entity, err := CreateEnvironmentSecret(ctx, exec, sourceID, environmentID, opts...)
		if err != nil {
			return nil, fmt.Errorf("failed to create environmentsecret %d: %w", i+1, err)
		}
		environmentsecrets = append(environmentsecrets, entity)
	}

	return environmentsecrets, nil
}

func WithEnvironmentSecretsKey(value string) EnvironmentSecretOption {
	return func(f *EnvironmentSecretFactory) {
		f.EnvironmentSecretEntity.Key = value
	}
}

func WithEnvironmentSecretsEncValue(value []byte) EnvironmentSecretOption {
	return func(f *EnvironmentSecretFactory) {
		f.EnvironmentSecretEntity.EncValue = value
	}
}

func WithEnvironmentSecretsDigest(value []byte) EnvironmentSecretOption {
	return func(f *EnvironmentSecretFactory) {
		f.EnvironmentSecretEntity.Digest = value
	}
}

func WithEnvironmentSecretsSourceType(value string) EnvironmentSecretOption {
	return func(f *EnvironmentSecretFactory) {
		f.EnvironmentSecretEntity.SourceType = value
	}
}

func WithEnvironmentSecretsSourceID(value uuid.UUID) EnvironmentSecretOption {
	return func(f *EnvironmentSecretFactory) {
		f.EnvironmentSecretEntity.SourceID = value
	}
}

func WithEnvironmentSecretsArchivedAt(value sql.NullTime) EnvironmentSecretOption {
	return func(f *EnvironmentSecretFactory) {
		f.EnvironmentSecretEntity.ArchivedAt = value
	}
}

func WithEnvironmentSecretsEnvironmentID(value uuid.UUID) EnvironmentSecretOption {
	return func(f *EnvironmentSecretFactory) {
		f.EnvironmentSecretEntity.EnvironmentID = value
	}
}
