package factories

import (
	"context"
	"database/sql"
	"deploycrate-ce/internal/storage"
	"deploycrate-ce/models"
	"fmt"
	"time"

	"github.com/go-faker/faker/v4"
	"github.com/google/uuid"
)

// Factory declarations below are generated by Andurel.

type EnvironmentDomainFactory struct {
	models.EnvironmentDomainEntity
}

type EnvironmentDomainOption func(*EnvironmentDomainFactory)

func BuildEnvironmentDomain(environmentID uuid.UUID, opts ...EnvironmentDomainOption) models.EnvironmentDomainEntity {
	f := &EnvironmentDomainFactory{
		EnvironmentDomainEntity: models.EnvironmentDomainEntity{
			Hostname:      faker.Word(),
			IsPrimary:     randomBool(),
			ArchivedAt:    sql.NullTime{Time: time.Now(), Valid: true},
			EnvironmentID: environmentID,
		},
	}

	for _, opt := range opts {
		opt(f)
	}

	return f.EnvironmentDomainEntity
}

func CreateEnvironmentDomain(ctx context.Context, exec storage.Executor, environmentID uuid.UUID, opts ...EnvironmentDomainOption) (models.EnvironmentDomainEntity, error) {
	built := BuildEnvironmentDomain(environmentID, opts...)

	entity := models.EnvironmentDomainEntity{
		ID:            uuid.New(),
		CreatedAt:     time.Now(),
		UpdatedAt:     time.Now(),
		Hostname:      built.Hostname,
		IsPrimary:     built.IsPrimary,
		ArchivedAt:    built.ArchivedAt,
		EnvironmentID: built.EnvironmentID,
	}

	if err := exec.NewInsert().Model(&entity).Returning("*").Scan(ctx); err != nil {
		return models.EnvironmentDomainEntity{}, err
	}

	return entity, nil
}

func CreateEnvironmentDomains(ctx context.Context, exec storage.Executor, environmentID uuid.UUID, count int, opts ...EnvironmentDomainOption) ([]models.EnvironmentDomainEntity, error) {
	environmentdomains := make([]models.EnvironmentDomainEntity, 0, count)

	for i := range count {
		entity, err := CreateEnvironmentDomain(ctx, exec, environmentID, opts...)
		if err != nil {
			return nil, fmt.Errorf("failed to create environmentdomain %d: %w", i+1, err)
		}
		environmentdomains = append(environmentdomains, entity)
	}

	return environmentdomains, nil
}

func WithEnvironmentDomainsHostname(value string) EnvironmentDomainOption {
	return func(f *EnvironmentDomainFactory) {
		f.EnvironmentDomainEntity.Hostname = value
	}
}

func WithEnvironmentDomainsIsPrimary(value bool) EnvironmentDomainOption {
	return func(f *EnvironmentDomainFactory) {
		f.EnvironmentDomainEntity.IsPrimary = value
	}
}

func WithEnvironmentDomainsArchivedAt(value sql.NullTime) EnvironmentDomainOption {
	return func(f *EnvironmentDomainFactory) {
		f.EnvironmentDomainEntity.ArchivedAt = value
	}
}

func WithEnvironmentDomainsEnvironmentID(value uuid.UUID) EnvironmentDomainOption {
	return func(f *EnvironmentDomainFactory) {
		f.EnvironmentDomainEntity.EnvironmentID = value
	}
}
