package factories

import (
	"context"
	"database/sql"
	"deploycrate-ce/internal/storage"
	"deploycrate-ce/models"
	"encoding/json"
	"fmt"
	"time"

	"github.com/go-faker/faker/v4"
	"github.com/google/uuid"
)

// Factory declarations below are generated by Andurel.

type EnvironmentTargetStateFactory struct {
	models.EnvironmentTargetStateEntity
}

type EnvironmentTargetStateOption func(*EnvironmentTargetStateFactory)

func BuildEnvironmentTargetState(environmentTargetID uuid.UUID, desiredRevisionID *uuid.UUID, applyingRevisionID *uuid.UUID, appliedRevisionID *uuid.UUID, opts ...EnvironmentTargetStateOption) models.EnvironmentTargetStateEntity {
	f := &EnvironmentTargetStateFactory{
		EnvironmentTargetStateEntity: models.EnvironmentTargetStateEntity{
			ObservedState:       json.RawMessage{},
			State:               faker.Word(),
			ObservedAt:          sql.NullTime{Time: time.Now(), Valid: true},
			EnvironmentTargetID: environmentTargetID,
			DesiredRevisionID:   desiredRevisionID,
			ApplyingRevisionID:  applyingRevisionID,
			AppliedRevisionID:   appliedRevisionID,
		},
	}

	for _, opt := range opts {
		opt(f)
	}

	return f.EnvironmentTargetStateEntity
}

func CreateEnvironmentTargetState(ctx context.Context, exec storage.Executor, environmentTargetID uuid.UUID, desiredRevisionID *uuid.UUID, applyingRevisionID *uuid.UUID, appliedRevisionID *uuid.UUID, opts ...EnvironmentTargetStateOption) (models.EnvironmentTargetStateEntity, error) {
	built := BuildEnvironmentTargetState(environmentTargetID, desiredRevisionID, applyingRevisionID, appliedRevisionID, opts...)

	entity := models.EnvironmentTargetStateEntity{
		ID:                  built.ID,
		CreatedAt:           time.Now(),
		UpdatedAt:           time.Now(),
		ObservedState:       built.ObservedState,
		State:               built.State,
		ObservedAt:          built.ObservedAt,
		EnvironmentTargetID: built.EnvironmentTargetID,
		DesiredRevisionID:   built.DesiredRevisionID,
		ApplyingRevisionID:  built.ApplyingRevisionID,
		AppliedRevisionID:   built.AppliedRevisionID,
	}

	if err := exec.NewInsert().Model(&entity).Returning("*").Scan(ctx); err != nil {
		return models.EnvironmentTargetStateEntity{}, err
	}

	return entity, nil
}

func CreateEnvironmentTargetStates(ctx context.Context, exec storage.Executor, environmentTargetID uuid.UUID, desiredRevisionID *uuid.UUID, applyingRevisionID *uuid.UUID, appliedRevisionID *uuid.UUID, count int, opts ...EnvironmentTargetStateOption) ([]models.EnvironmentTargetStateEntity, error) {
	environmenttargetstates := make([]models.EnvironmentTargetStateEntity, 0, count)

	for i := range count {
		entity, err := CreateEnvironmentTargetState(ctx, exec, environmentTargetID, desiredRevisionID, applyingRevisionID, appliedRevisionID, opts...)
		if err != nil {
			return nil, fmt.Errorf("failed to create environmenttargetstate %d: %w", i+1, err)
		}
		environmenttargetstates = append(environmenttargetstates, entity)
	}

	return environmenttargetstates, nil
}

func WithEnvironmentTargetStatesObservedState(value json.RawMessage) EnvironmentTargetStateOption {
	return func(f *EnvironmentTargetStateFactory) {
		f.EnvironmentTargetStateEntity.ObservedState = value
	}
}

func WithEnvironmentTargetStatesState(value string) EnvironmentTargetStateOption {
	return func(f *EnvironmentTargetStateFactory) {
		f.EnvironmentTargetStateEntity.State = value
	}
}

func WithEnvironmentTargetStatesObservedAt(value sql.NullTime) EnvironmentTargetStateOption {
	return func(f *EnvironmentTargetStateFactory) {
		f.EnvironmentTargetStateEntity.ObservedAt = value
	}
}

func WithEnvironmentTargetStatesEnvironmentTargetID(value uuid.UUID) EnvironmentTargetStateOption {
	return func(f *EnvironmentTargetStateFactory) {
		f.EnvironmentTargetStateEntity.EnvironmentTargetID = value
	}
}

func WithEnvironmentTargetStatesDesiredRevisionID(value *uuid.UUID) EnvironmentTargetStateOption {
	return func(f *EnvironmentTargetStateFactory) {
		f.EnvironmentTargetStateEntity.DesiredRevisionID = value
	}
}

func WithEnvironmentTargetStatesApplyingRevisionID(value *uuid.UUID) EnvironmentTargetStateOption {
	return func(f *EnvironmentTargetStateFactory) {
		f.EnvironmentTargetStateEntity.ApplyingRevisionID = value
	}
}

func WithEnvironmentTargetStatesAppliedRevisionID(value *uuid.UUID) EnvironmentTargetStateOption {
	return func(f *EnvironmentTargetStateFactory) {
		f.EnvironmentTargetStateEntity.AppliedRevisionID = value
	}
}
