package factories

import (
	"context"
	"database/sql"
	"deploycrate-ce/internal/storage"
	"deploycrate-ce/models"
	"fmt"
	"time"

	"github.com/go-faker/faker/v4"
	"github.com/google/uuid"
)

// Factory declarations below are generated by Andurel.

type EnvironmentFactory struct {
	models.EnvironmentEntity
}

type EnvironmentOption func(*EnvironmentFactory)

func BuildEnvironment(applicationID uuid.UUID, opts ...EnvironmentOption) models.EnvironmentEntity {
	f := &EnvironmentFactory{
		EnvironmentEntity: models.EnvironmentEntity{
			Name:                  faker.Word(),
			Slug:                  faker.Word(),
			Kind:                  faker.Word(),
			APITokenPrefix:        sql.NullString{String: faker.Word(), Valid: true},
			APITokenDigest:        []byte{},
			AccessMode:            models.EnvironmentAccessPublic,
			BasicAuthUsername:     "",
			BasicAuthPasswordHash: "",
			ArchivedAt:            sql.NullTime{Time: time.Now(), Valid: true},
			ApplicationID:         applicationID,
		},
	}

	for _, opt := range opts {
		opt(f)
	}

	return f.EnvironmentEntity
}

func CreateEnvironment(
	ctx context.Context,
	exec storage.Executor,
	applicationID uuid.UUID,
	opts ...EnvironmentOption,
) (models.EnvironmentEntity, error) {
	built := BuildEnvironment(applicationID, opts...)

	entity := models.EnvironmentEntity{
		ID:                    uuid.New(),
		CreatedAt:             time.Now(),
		UpdatedAt:             time.Now(),
		Name:                  built.Name,
		Slug:                  built.Slug,
		Kind:                  built.Kind,
		APITokenPrefix:        built.APITokenPrefix,
		APITokenDigest:        built.APITokenDigest,
		AccessMode:            built.AccessMode,
		BasicAuthUsername:     built.BasicAuthUsername,
		BasicAuthPasswordHash: built.BasicAuthPasswordHash,
		ArchivedAt:            built.ArchivedAt,
		ApplicationID:         built.ApplicationID,
	}

	if err := exec.NewInsert().Model(&entity).Returning("*").Scan(ctx); err != nil {
		return models.EnvironmentEntity{}, err
	}

	return entity, nil
}

func CreateEnvironments(
	ctx context.Context,
	exec storage.Executor,
	applicationID uuid.UUID,
	count int,
	opts ...EnvironmentOption,
) ([]models.EnvironmentEntity, error) {
	environments := make([]models.EnvironmentEntity, 0, count)

	for i := range count {
		entity, err := CreateEnvironment(ctx, exec, applicationID, opts...)
		if err != nil {
			return nil, fmt.Errorf("failed to create environment %d: %w", i+1, err)
		}
		environments = append(environments, entity)
	}

	return environments, nil
}

func WithEnvironmentsName(value string) EnvironmentOption {
	return func(f *EnvironmentFactory) {
		f.EnvironmentEntity.Name = value
	}
}

func WithEnvironmentsSlug(value string) EnvironmentOption {
	return func(f *EnvironmentFactory) {
		f.EnvironmentEntity.Slug = value
	}
}

func WithEnvironmentsKind(value string) EnvironmentOption {
	return func(f *EnvironmentFactory) {
		f.EnvironmentEntity.Kind = value
	}
}

func WithEnvironmentsAPITokenPrefix(value sql.NullString) EnvironmentOption {
	return func(f *EnvironmentFactory) {
		f.EnvironmentEntity.APITokenPrefix = value
	}
}

func WithEnvironmentsAPITokenDigest(value []byte) EnvironmentOption {
	return func(f *EnvironmentFactory) {
		f.EnvironmentEntity.APITokenDigest = value
	}
}

func WithEnvironmentsAccessMode(value models.EnvironmentAccessModeEnum) EnvironmentOption {
	return func(f *EnvironmentFactory) {
		f.EnvironmentEntity.AccessMode = value
	}
}

func WithEnvironmentsBasicAuthUsername(value string) EnvironmentOption {
	return func(f *EnvironmentFactory) {
		f.EnvironmentEntity.BasicAuthUsername = value
	}
}

func WithEnvironmentsBasicAuthPasswordHash(value string) EnvironmentOption {
	return func(f *EnvironmentFactory) {
		f.EnvironmentEntity.BasicAuthPasswordHash = value
	}
}

func WithEnvironmentsArchivedAt(value sql.NullTime) EnvironmentOption {
	return func(f *EnvironmentFactory) {
		f.EnvironmentEntity.ArchivedAt = value
	}
}

func WithEnvironmentsApplicationID(value uuid.UUID) EnvironmentOption {
	return func(f *EnvironmentFactory) {
		f.EnvironmentEntity.ApplicationID = value
	}
}
