package factories

import (
	"context"
	"database/sql"
	"deploycrate-ce/internal/storage"
	"deploycrate-ce/models"
	"encoding/json"
	"fmt"
	"time"

	"github.com/go-faker/faker/v4"
	"github.com/google/uuid"
)

// Factory declarations below are generated by Andurel.

type EnvironmentSourceFactory struct {
	models.EnvironmentSourceEntity
}

type EnvironmentSourceOption func(*EnvironmentSourceFactory)

func BuildEnvironmentSource(environmentID uuid.UUID, credentialID *uuid.UUID, opts ...EnvironmentSourceOption) models.EnvironmentSourceEntity {
	f := &EnvironmentSourceFactory{
		EnvironmentSourceEntity: models.EnvironmentSourceEntity{
			EnvironmentID: environmentID,
			CredentialID:  credentialID,
			Kind:          faker.Word(),
			Provider:      faker.Word(),
			Repository:    faker.Word(),
			Reference:     faker.Word(),
			Settings:      json.RawMessage{},
			ArchivedAt:    sql.NullTime{Time: time.Now(), Valid: true},
		},
	}

	for _, opt := range opts {
		opt(f)
	}

	return f.EnvironmentSourceEntity
}

func CreateEnvironmentSource(ctx context.Context, exec storage.Executor, environmentID uuid.UUID, credentialID *uuid.UUID, opts ...EnvironmentSourceOption) (models.EnvironmentSourceEntity, error) {
	built := BuildEnvironmentSource(environmentID, credentialID, opts...)

	entity := models.EnvironmentSourceEntity{
		ID:            uuid.New(),
		CreatedAt:     time.Now(),
		UpdatedAt:     time.Now(),
		EnvironmentID: built.EnvironmentID,
		CredentialID:  built.CredentialID,
		Kind:          built.Kind,
		Provider:      built.Provider,
		Repository:    built.Repository,
		Reference:     built.Reference,
		Settings:      built.Settings,
		ArchivedAt:    built.ArchivedAt,
	}

	if err := exec.NewInsert().Model(&entity).Returning("*").Scan(ctx); err != nil {
		return models.EnvironmentSourceEntity{}, err
	}

	return entity, nil
}

func CreateEnvironmentSources(ctx context.Context, exec storage.Executor, environmentID uuid.UUID, credentialID *uuid.UUID, count int, opts ...EnvironmentSourceOption) ([]models.EnvironmentSourceEntity, error) {
	environmentsources := make([]models.EnvironmentSourceEntity, 0, count)

	for i := range count {
		entity, err := CreateEnvironmentSource(ctx, exec, environmentID, credentialID, opts...)
		if err != nil {
			return nil, fmt.Errorf("failed to create environmentsource %d: %w", i+1, err)
		}
		environmentsources = append(environmentsources, entity)
	}

	return environmentsources, nil
}

func WithEnvironmentSourcesEnvironmentID(value uuid.UUID) EnvironmentSourceOption {
	return func(f *EnvironmentSourceFactory) {
		f.EnvironmentSourceEntity.EnvironmentID = value
	}
}

func WithEnvironmentSourcesCredentialID(value *uuid.UUID) EnvironmentSourceOption {
	return func(f *EnvironmentSourceFactory) {
		f.EnvironmentSourceEntity.CredentialID = value
	}
}

func WithEnvironmentSourcesKind(value string) EnvironmentSourceOption {
	return func(f *EnvironmentSourceFactory) {
		f.EnvironmentSourceEntity.Kind = value
	}
}

func WithEnvironmentSourcesProvider(value string) EnvironmentSourceOption {
	return func(f *EnvironmentSourceFactory) {
		f.EnvironmentSourceEntity.Provider = value
	}
}

func WithEnvironmentSourcesRepository(value string) EnvironmentSourceOption {
	return func(f *EnvironmentSourceFactory) {
		f.EnvironmentSourceEntity.Repository = value
	}
}

func WithEnvironmentSourcesReference(value string) EnvironmentSourceOption {
	return func(f *EnvironmentSourceFactory) {
		f.EnvironmentSourceEntity.Reference = value
	}
}

func WithEnvironmentSourcesSettings(value json.RawMessage) EnvironmentSourceOption {
	return func(f *EnvironmentSourceFactory) {
		f.EnvironmentSourceEntity.Settings = value
	}
}

func WithEnvironmentSourcesArchivedAt(value sql.NullTime) EnvironmentSourceOption {
	return func(f *EnvironmentSourceFactory) {
		f.EnvironmentSourceEntity.ArchivedAt = value
	}
}
