package factories

import (
	"context"
	"deploycrate-ce/internal/storage"
	"deploycrate-ce/models"
	"encoding/json"
	"fmt"
	"time"

	"github.com/google/uuid"
)

// Factory declarations below are generated by Andurel.

type EnvironmentStateRevisionFactory struct {
	models.EnvironmentStateRevisionEntity
}

type EnvironmentStateRevisionOption func(*EnvironmentStateRevisionFactory)

func BuildEnvironmentStateRevision(environmentID uuid.UUID, changeID uuid.UUID, opts ...EnvironmentStateRevisionOption) models.EnvironmentStateRevisionEntity {
	f := &EnvironmentStateRevisionFactory{
		EnvironmentStateRevisionEntity: models.EnvironmentStateRevisionEntity{
			EnvironmentID: environmentID,
			ChangeID:      changeID,
			State:         json.RawMessage{},
		},
	}

	for _, opt := range opts {
		opt(f)
	}

	return f.EnvironmentStateRevisionEntity
}

func CreateEnvironmentStateRevision(ctx context.Context, exec storage.Executor, environmentID uuid.UUID, changeID uuid.UUID, opts ...EnvironmentStateRevisionOption) (models.EnvironmentStateRevisionEntity, error) {
	built := BuildEnvironmentStateRevision(environmentID, changeID, opts...)

	entity := models.EnvironmentStateRevisionEntity{
		ID:            uuid.New(),
		CreatedAt:     time.Now(),
		UpdatedAt:     time.Now(),
		EnvironmentID: built.EnvironmentID,
		ChangeID:      built.ChangeID,
		State:         built.State,
	}

	if err := exec.NewInsert().Model(&entity).Returning("*").Scan(ctx); err != nil {
		return models.EnvironmentStateRevisionEntity{}, err
	}

	return entity, nil
}

func CreateEnvironmentStateRevisions(ctx context.Context, exec storage.Executor, environmentID uuid.UUID, changeID uuid.UUID, count int, opts ...EnvironmentStateRevisionOption) ([]models.EnvironmentStateRevisionEntity, error) {
	environmentstaterevisions := make([]models.EnvironmentStateRevisionEntity, 0, count)

	for i := range count {
		entity, err := CreateEnvironmentStateRevision(ctx, exec, environmentID, changeID, opts...)
		if err != nil {
			return nil, fmt.Errorf("failed to create environmentstaterevision %d: %w", i+1, err)
		}
		environmentstaterevisions = append(environmentstaterevisions, entity)
	}

	return environmentstaterevisions, nil
}

func WithEnvironmentStateRevisionsEnvironmentID(value uuid.UUID) EnvironmentStateRevisionOption {
	return func(f *EnvironmentStateRevisionFactory) {
		f.EnvironmentStateRevisionEntity.EnvironmentID = value
	}
}

func WithEnvironmentStateRevisionsChangeID(value uuid.UUID) EnvironmentStateRevisionOption {
	return func(f *EnvironmentStateRevisionFactory) {
		f.EnvironmentStateRevisionEntity.ChangeID = value
	}
}

func WithEnvironmentStateRevisionsState(value json.RawMessage) EnvironmentStateRevisionOption {
	return func(f *EnvironmentStateRevisionFactory) {
		f.EnvironmentStateRevisionEntity.State = value
	}
}
