package factories

import (
	"context"
	"database/sql"
	"deploycrate-ce/internal/storage"
	"deploycrate-ce/models"
	"encoding/json"
	"fmt"
	"time"

	"github.com/go-faker/faker/v4"
	"github.com/google/uuid"
)

// Factory declarations below are generated by Andurel.

type EnvironmentDependencyFactory struct {
	models.EnvironmentDependencyEntity
}

type EnvironmentDependencyOption func(*EnvironmentDependencyFactory)

func BuildEnvironmentDependency(environmentID uuid.UUID, resourceID uuid.UUID, resourceEndpointID uuid.UUID, privateNetworkID *uuid.UUID, opts ...EnvironmentDependencyOption) models.EnvironmentDependencyEntity {
	f := &EnvironmentDependencyFactory{
		EnvironmentDependencyEntity: models.EnvironmentDependencyEntity{
			EnvironmentID:      environmentID,
			ResourceID:         resourceID,
			ResourceEndpointID: resourceEndpointID,
			PrivateNetworkID:   privateNetworkID,
			Alias:              faker.Word(),
			Required:           randomBool(),
			SecretMapping:      json.RawMessage{},
			Settings:           json.RawMessage{},
			ArchivedAt:         sql.NullTime{Time: time.Now(), Valid: true},
		},
	}

	for _, opt := range opts {
		opt(f)
	}

	return f.EnvironmentDependencyEntity
}

func CreateEnvironmentDependency(ctx context.Context, exec storage.Executor, environmentID uuid.UUID, resourceID uuid.UUID, resourceEndpointID uuid.UUID, privateNetworkID *uuid.UUID, opts ...EnvironmentDependencyOption) (models.EnvironmentDependencyEntity, error) {
	built := BuildEnvironmentDependency(environmentID, resourceID, resourceEndpointID, privateNetworkID, opts...)

	entity := models.EnvironmentDependencyEntity{
		ID:                 uuid.New(),
		CreatedAt:          time.Now(),
		UpdatedAt:          time.Now(),
		EnvironmentID:      built.EnvironmentID,
		ResourceID:         built.ResourceID,
		ResourceEndpointID: built.ResourceEndpointID,
		PrivateNetworkID:   built.PrivateNetworkID,
		Alias:              built.Alias,
		Required:           built.Required,
		SecretMapping:      built.SecretMapping,
		Settings:           built.Settings,
		ArchivedAt:         built.ArchivedAt,
	}

	if err := exec.NewInsert().Model(&entity).Returning("*").Scan(ctx); err != nil {
		return models.EnvironmentDependencyEntity{}, err
	}

	return entity, nil
}

func CreateEnvironmentDependencies(ctx context.Context, exec storage.Executor, environmentID uuid.UUID, resourceID uuid.UUID, resourceEndpointID uuid.UUID, privateNetworkID *uuid.UUID, count int, opts ...EnvironmentDependencyOption) ([]models.EnvironmentDependencyEntity, error) {
	environmentDependencies := make([]models.EnvironmentDependencyEntity, 0, count)

	for i := range count {
		entity, err := CreateEnvironmentDependency(ctx, exec, environmentID, resourceID, resourceEndpointID, privateNetworkID, opts...)
		if err != nil {
			return nil, fmt.Errorf("failed to create environmentdependency %d: %w", i+1, err)
		}
		environmentDependencies = append(environmentDependencies, entity)
	}

	return environmentDependencies, nil
}

func WithEnvironmentDependenciesEnvironmentID(value uuid.UUID) EnvironmentDependencyOption {
	return func(f *EnvironmentDependencyFactory) {
		f.EnvironmentDependencyEntity.EnvironmentID = value
	}
}

func WithEnvironmentDependenciesResourceID(value uuid.UUID) EnvironmentDependencyOption {
	return func(f *EnvironmentDependencyFactory) {
		f.EnvironmentDependencyEntity.ResourceID = value
	}
}

func WithEnvironmentDependenciesResourceEndpointID(value uuid.UUID) EnvironmentDependencyOption {
	return func(f *EnvironmentDependencyFactory) {
		f.EnvironmentDependencyEntity.ResourceEndpointID = value
	}
}

func WithEnvironmentDependenciesPrivateNetworkID(value *uuid.UUID) EnvironmentDependencyOption {
	return func(f *EnvironmentDependencyFactory) {
		f.EnvironmentDependencyEntity.PrivateNetworkID = value
	}
}

func WithEnvironmentDependenciesAlias(value string) EnvironmentDependencyOption {
	return func(f *EnvironmentDependencyFactory) {
		f.EnvironmentDependencyEntity.Alias = value
	}
}

func WithEnvironmentDependenciesRequired(value bool) EnvironmentDependencyOption {
	return func(f *EnvironmentDependencyFactory) {
		f.EnvironmentDependencyEntity.Required = value
	}
}

func WithEnvironmentDependenciesSecretMapping(value json.RawMessage) EnvironmentDependencyOption {
	return func(f *EnvironmentDependencyFactory) {
		f.EnvironmentDependencyEntity.SecretMapping = value
	}
}

func WithEnvironmentDependenciesSettings(value json.RawMessage) EnvironmentDependencyOption {
	return func(f *EnvironmentDependencyFactory) {
		f.EnvironmentDependencyEntity.Settings = value
	}
}

func WithEnvironmentDependenciesArchivedAt(value sql.NullTime) EnvironmentDependencyOption {
	return func(f *EnvironmentDependencyFactory) {
		f.EnvironmentDependencyEntity.ArchivedAt = value
	}
}
