package factories

import (
	"context"
	"database/sql"
	"deploycrate-ce/internal/storage"
	"deploycrate-ce/models"
	"encoding/json"
	"fmt"
	"time"

	"github.com/go-faker/faker/v4"
	"github.com/google/uuid"
)

// Factory declarations below are generated by Andurel.

type EnvironmentTargetNetworkFactory struct {
	models.EnvironmentTargetNetworkEntity
}

type EnvironmentTargetNetworkOption func(*EnvironmentTargetNetworkFactory)

func BuildEnvironmentTargetNetwork(environmentTargetID uuid.UUID, privateNetworkID uuid.UUID, externalID sql.NullString, opts ...EnvironmentTargetNetworkOption) models.EnvironmentTargetNetworkEntity {
	f := &EnvironmentTargetNetworkFactory{
		EnvironmentTargetNetworkEntity: models.EnvironmentTargetNetworkEntity{
			EnvironmentTargetID: environmentTargetID,
			PrivateNetworkID:    privateNetworkID,
			Address:             faker.Word(),
			Driver:              faker.Word(),
			ExternalID:          externalID,
			Configuration:       json.RawMessage{},
			State:               faker.Word(),
			AppliedAt:           sql.NullTime{Time: time.Now(), Valid: true},
			ObservedAt:          sql.NullTime{Time: time.Now(), Valid: true},
			Error:               sql.NullString{String: faker.Word(), Valid: true},
			RemovedAt:           sql.NullTime{Time: time.Now(), Valid: true},
		},
	}

	for _, opt := range opts {
		opt(f)
	}

	return f.EnvironmentTargetNetworkEntity
}

func CreateEnvironmentTargetNetwork(ctx context.Context, exec storage.Executor, environmentTargetID uuid.UUID, privateNetworkID uuid.UUID, externalID sql.NullString, opts ...EnvironmentTargetNetworkOption) (models.EnvironmentTargetNetworkEntity, error) {
	built := BuildEnvironmentTargetNetwork(environmentTargetID, privateNetworkID, externalID, opts...)

	entity := models.EnvironmentTargetNetworkEntity{
		ID:                  built.ID,
		CreatedAt:           time.Now(),
		UpdatedAt:           time.Now(),
		EnvironmentTargetID: built.EnvironmentTargetID,
		PrivateNetworkID:    built.PrivateNetworkID,
		Address:             built.Address,
		Driver:              built.Driver,
		ExternalID:          built.ExternalID,
		Configuration:       built.Configuration,
		State:               built.State,
		AppliedAt:           built.AppliedAt,
		ObservedAt:          built.ObservedAt,
		Error:               built.Error,
		RemovedAt:           built.RemovedAt,
	}

	if err := exec.NewInsert().Model(&entity).Returning("*").Scan(ctx); err != nil {
		return models.EnvironmentTargetNetworkEntity{}, err
	}

	return entity, nil
}

func CreateEnvironmentTargetNetworks(ctx context.Context, exec storage.Executor, environmentTargetID uuid.UUID, privateNetworkID uuid.UUID, externalID sql.NullString, count int, opts ...EnvironmentTargetNetworkOption) ([]models.EnvironmentTargetNetworkEntity, error) {
	environmenttargetnetworks := make([]models.EnvironmentTargetNetworkEntity, 0, count)

	for i := range count {
		entity, err := CreateEnvironmentTargetNetwork(ctx, exec, environmentTargetID, privateNetworkID, externalID, opts...)
		if err != nil {
			return nil, fmt.Errorf("failed to create environmenttargetnetwork %d: %w", i+1, err)
		}
		environmenttargetnetworks = append(environmenttargetnetworks, entity)
	}

	return environmenttargetnetworks, nil
}

func WithEnvironmentTargetNetworksEnvironmentTargetID(value uuid.UUID) EnvironmentTargetNetworkOption {
	return func(f *EnvironmentTargetNetworkFactory) {
		f.EnvironmentTargetNetworkEntity.EnvironmentTargetID = value
	}
}

func WithEnvironmentTargetNetworksPrivateNetworkID(value uuid.UUID) EnvironmentTargetNetworkOption {
	return func(f *EnvironmentTargetNetworkFactory) {
		f.EnvironmentTargetNetworkEntity.PrivateNetworkID = value
	}
}

func WithEnvironmentTargetNetworksAddress(value string) EnvironmentTargetNetworkOption {
	return func(f *EnvironmentTargetNetworkFactory) {
		f.EnvironmentTargetNetworkEntity.Address = value
	}
}

func WithEnvironmentTargetNetworksDriver(value string) EnvironmentTargetNetworkOption {
	return func(f *EnvironmentTargetNetworkFactory) {
		f.EnvironmentTargetNetworkEntity.Driver = value
	}
}

func WithEnvironmentTargetNetworksExternalID(value sql.NullString) EnvironmentTargetNetworkOption {
	return func(f *EnvironmentTargetNetworkFactory) {
		f.EnvironmentTargetNetworkEntity.ExternalID = value
	}
}

func WithEnvironmentTargetNetworksConfiguration(value json.RawMessage) EnvironmentTargetNetworkOption {
	return func(f *EnvironmentTargetNetworkFactory) {
		f.EnvironmentTargetNetworkEntity.Configuration = value
	}
}

func WithEnvironmentTargetNetworksState(value string) EnvironmentTargetNetworkOption {
	return func(f *EnvironmentTargetNetworkFactory) {
		f.EnvironmentTargetNetworkEntity.State = value
	}
}

func WithEnvironmentTargetNetworksAppliedAt(value sql.NullTime) EnvironmentTargetNetworkOption {
	return func(f *EnvironmentTargetNetworkFactory) {
		f.EnvironmentTargetNetworkEntity.AppliedAt = value
	}
}

func WithEnvironmentTargetNetworksObservedAt(value sql.NullTime) EnvironmentTargetNetworkOption {
	return func(f *EnvironmentTargetNetworkFactory) {
		f.EnvironmentTargetNetworkEntity.ObservedAt = value
	}
}

func WithEnvironmentTargetNetworksError(value sql.NullString) EnvironmentTargetNetworkOption {
	return func(f *EnvironmentTargetNetworkFactory) {
		f.EnvironmentTargetNetworkEntity.Error = value
	}
}

func WithEnvironmentTargetNetworksRemovedAt(value sql.NullTime) EnvironmentTargetNetworkOption {
	return func(f *EnvironmentTargetNetworkFactory) {
		f.EnvironmentTargetNetworkEntity.RemovedAt = value
	}
}
