package factories

import (
	"context"
	"database/sql"
	"deploycrate-ce/internal/storage"
	"deploycrate-ce/models"
	"encoding/json"
	"fmt"
	"time"

	"github.com/go-faker/faker/v4"
	"github.com/google/uuid"
)

// Factory declarations below are generated by Andurel.

type EnvironmentBuildConfigurationFactory struct {
	models.EnvironmentBuildConfigurationEntity
}

type EnvironmentBuildConfigurationOption func(*EnvironmentBuildConfigurationFactory)

func BuildEnvironmentBuildConfiguration(environmentID uuid.UUID, opts ...EnvironmentBuildConfigurationOption) models.EnvironmentBuildConfigurationEntity {
	f := &EnvironmentBuildConfigurationFactory{
		EnvironmentBuildConfigurationEntity: models.EnvironmentBuildConfigurationEntity{
			EnvironmentID:    environmentID,
			Method:           faker.Word(),
			ContextPath:      faker.Word(),
			DockerfilePath:   sql.NullString{String: faker.Word(), Valid: true},
			BuilderReference: sql.NullString{String: faker.Word(), Valid: true},
			Settings:         json.RawMessage{},
		},
	}

	for _, opt := range opts {
		opt(f)
	}

	return f.EnvironmentBuildConfigurationEntity
}

func CreateEnvironmentBuildConfiguration(ctx context.Context, exec storage.Executor, environmentID uuid.UUID, opts ...EnvironmentBuildConfigurationOption) (models.EnvironmentBuildConfigurationEntity, error) {
	built := BuildEnvironmentBuildConfiguration(environmentID, opts...)

	entity := models.EnvironmentBuildConfigurationEntity{
		ID:               built.ID,
		CreatedAt:        time.Now(),
		UpdatedAt:        time.Now(),
		EnvironmentID:    built.EnvironmentID,
		Method:           built.Method,
		ContextPath:      built.ContextPath,
		DockerfilePath:   built.DockerfilePath,
		BuilderReference: built.BuilderReference,
		Settings:         built.Settings,
	}

	if err := exec.NewInsert().Model(&entity).Returning("*").Scan(ctx); err != nil {
		return models.EnvironmentBuildConfigurationEntity{}, err
	}

	return entity, nil
}

func CreateEnvironmentBuildConfigurations(ctx context.Context, exec storage.Executor, environmentID uuid.UUID, count int, opts ...EnvironmentBuildConfigurationOption) ([]models.EnvironmentBuildConfigurationEntity, error) {
	environmentbuildconfigurations := make([]models.EnvironmentBuildConfigurationEntity, 0, count)

	for i := range count {
		entity, err := CreateEnvironmentBuildConfiguration(ctx, exec, environmentID, opts...)
		if err != nil {
			return nil, fmt.Errorf("failed to create environmentbuildconfiguration %d: %w", i+1, err)
		}
		environmentbuildconfigurations = append(environmentbuildconfigurations, entity)
	}

	return environmentbuildconfigurations, nil
}

func WithEnvironmentBuildConfigurationsEnvironmentID(value uuid.UUID) EnvironmentBuildConfigurationOption {
	return func(f *EnvironmentBuildConfigurationFactory) {
		f.EnvironmentBuildConfigurationEntity.EnvironmentID = value
	}
}

func WithEnvironmentBuildConfigurationsMethod(value string) EnvironmentBuildConfigurationOption {
	return func(f *EnvironmentBuildConfigurationFactory) {
		f.EnvironmentBuildConfigurationEntity.Method = value
	}
}

func WithEnvironmentBuildConfigurationsContextPath(value string) EnvironmentBuildConfigurationOption {
	return func(f *EnvironmentBuildConfigurationFactory) {
		f.EnvironmentBuildConfigurationEntity.ContextPath = value
	}
}

func WithEnvironmentBuildConfigurationsDockerfilePath(value sql.NullString) EnvironmentBuildConfigurationOption {
	return func(f *EnvironmentBuildConfigurationFactory) {
		f.EnvironmentBuildConfigurationEntity.DockerfilePath = value
	}
}

func WithEnvironmentBuildConfigurationsBuilderReference(value sql.NullString) EnvironmentBuildConfigurationOption {
	return func(f *EnvironmentBuildConfigurationFactory) {
		f.EnvironmentBuildConfigurationEntity.BuilderReference = value
	}
}

func WithEnvironmentBuildConfigurationsSettings(value json.RawMessage) EnvironmentBuildConfigurationOption {
	return func(f *EnvironmentBuildConfigurationFactory) {
		f.EnvironmentBuildConfigurationEntity.Settings = value
	}
}
