package factories

import (
	"context"
	"database/sql"
	"deploycrate-ce/internal/storage"
	"deploycrate-ce/models"
	"fmt"
	"time"

	"github.com/go-faker/faker/v4"
	"github.com/google/uuid"
)

// Factory declarations below are generated by Andurel.

type EnvironmentHealthCheckFactory struct {
	models.EnvironmentHealthCheckEntity
}

type EnvironmentHealthCheckOption func(*EnvironmentHealthCheckFactory)

func BuildEnvironmentHealthCheck(environmentID uuid.UUID, dependencyID *uuid.UUID, opts ...EnvironmentHealthCheckOption) models.EnvironmentHealthCheckEntity {
	f := &EnvironmentHealthCheckFactory{
		EnvironmentHealthCheckEntity: models.EnvironmentHealthCheckEntity{
			EnvironmentID:   environmentID,
			DependencyID:    dependencyID,
			Name:            faker.Word(),
			Url:             faker.Word(),
			Method:          faker.Word(),
			ExpectedStatus:  randomInt(1, 1000, 100),
			TimeoutSeconds:  randomInt(1, 1000, 100),
			IntervalSeconds: randomInt(1, 1000, 100),
			Enabled:         randomBool(),
			ArchivedAt:      sql.NullTime{Time: time.Now(), Valid: true},
		},
	}

	for _, opt := range opts {
		opt(f)
	}

	return f.EnvironmentHealthCheckEntity
}

func CreateEnvironmentHealthCheck(ctx context.Context, exec storage.Executor, environmentID uuid.UUID, dependencyID *uuid.UUID, opts ...EnvironmentHealthCheckOption) (models.EnvironmentHealthCheckEntity, error) {
	built := BuildEnvironmentHealthCheck(environmentID, dependencyID, opts...)

	entity := models.EnvironmentHealthCheckEntity{
		ID:              uuid.New(),
		CreatedAt:       time.Now(),
		UpdatedAt:       time.Now(),
		EnvironmentID:   built.EnvironmentID,
		DependencyID:    built.DependencyID,
		Name:            built.Name,
		Url:             built.Url,
		Method:          built.Method,
		ExpectedStatus:  built.ExpectedStatus,
		TimeoutSeconds:  built.TimeoutSeconds,
		IntervalSeconds: built.IntervalSeconds,
		Enabled:         built.Enabled,
		ArchivedAt:      built.ArchivedAt,
	}

	if err := exec.NewInsert().Model(&entity).Returning("*").Scan(ctx); err != nil {
		return models.EnvironmentHealthCheckEntity{}, err
	}

	return entity, nil
}

func CreateEnvironmentHealthChecks(ctx context.Context, exec storage.Executor, environmentID uuid.UUID, dependencyID *uuid.UUID, count int, opts ...EnvironmentHealthCheckOption) ([]models.EnvironmentHealthCheckEntity, error) {
	environmenthealthchecks := make([]models.EnvironmentHealthCheckEntity, 0, count)

	for i := range count {
		entity, err := CreateEnvironmentHealthCheck(ctx, exec, environmentID, dependencyID, opts...)
		if err != nil {
			return nil, fmt.Errorf("failed to create environmenthealthcheck %d: %w", i+1, err)
		}
		environmenthealthchecks = append(environmenthealthchecks, entity)
	}

	return environmenthealthchecks, nil
}

func WithEnvironmentHealthChecksEnvironmentID(value uuid.UUID) EnvironmentHealthCheckOption {
	return func(f *EnvironmentHealthCheckFactory) {
		f.EnvironmentHealthCheckEntity.EnvironmentID = value
	}
}

func WithEnvironmentHealthChecksDependencyID(value *uuid.UUID) EnvironmentHealthCheckOption {
	return func(f *EnvironmentHealthCheckFactory) {
		f.EnvironmentHealthCheckEntity.DependencyID = value
	}
}

func WithEnvironmentHealthChecksName(value string) EnvironmentHealthCheckOption {
	return func(f *EnvironmentHealthCheckFactory) {
		f.EnvironmentHealthCheckEntity.Name = value
	}
}

func WithEnvironmentHealthChecksUrl(value string) EnvironmentHealthCheckOption {
	return func(f *EnvironmentHealthCheckFactory) {
		f.EnvironmentHealthCheckEntity.Url = value
	}
}

func WithEnvironmentHealthChecksMethod(value string) EnvironmentHealthCheckOption {
	return func(f *EnvironmentHealthCheckFactory) {
		f.EnvironmentHealthCheckEntity.Method = value
	}
}

func WithEnvironmentHealthChecksExpectedStatus(value int32) EnvironmentHealthCheckOption {
	return func(f *EnvironmentHealthCheckFactory) {
		f.EnvironmentHealthCheckEntity.ExpectedStatus = value
	}
}

func WithEnvironmentHealthChecksTimeoutSeconds(value int32) EnvironmentHealthCheckOption {
	return func(f *EnvironmentHealthCheckFactory) {
		f.EnvironmentHealthCheckEntity.TimeoutSeconds = value
	}
}

func WithEnvironmentHealthChecksIntervalSeconds(value int32) EnvironmentHealthCheckOption {
	return func(f *EnvironmentHealthCheckFactory) {
		f.EnvironmentHealthCheckEntity.IntervalSeconds = value
	}
}

func WithEnvironmentHealthChecksEnabled(value bool) EnvironmentHealthCheckOption {
	return func(f *EnvironmentHealthCheckFactory) {
		f.EnvironmentHealthCheckEntity.Enabled = value
	}
}

func WithEnvironmentHealthChecksArchivedAt(value sql.NullTime) EnvironmentHealthCheckOption {
	return func(f *EnvironmentHealthCheckFactory) {
		f.EnvironmentHealthCheckEntity.ArchivedAt = value
	}
}
