package factories

import (
	"context"
	"database/sql"
	"deploycrate-ce/internal/storage"
	"deploycrate-ce/models"
	"fmt"
	"time"

	"github.com/go-faker/faker/v4"
	"github.com/google/uuid"
)

// Factory declarations below are generated by Andurel.

type EnvironmentNetworkFactory struct {
	models.EnvironmentNetworkEntity
}

type EnvironmentNetworkOption func(*EnvironmentNetworkFactory)

func BuildEnvironmentNetwork(
	environmentID uuid.UUID,
	privateNetworkID uuid.UUID,
	opts ...EnvironmentNetworkOption,
) models.EnvironmentNetworkEntity {
	f := &EnvironmentNetworkFactory{
		EnvironmentNetworkEntity: models.EnvironmentNetworkEntity{
			Role:             faker.Word(),
			RemovedAt:        sql.NullTime{Time: time.Now(), Valid: true},
			EnvironmentID:    environmentID,
			PrivateNetworkID: privateNetworkID,
		},
	}

	for _, opt := range opts {
		opt(f)
	}

	return f.EnvironmentNetworkEntity
}

func CreateEnvironmentNetwork(
	ctx context.Context,
	exec storage.Executor,
	environmentID uuid.UUID,
	privateNetworkID uuid.UUID,
	opts ...EnvironmentNetworkOption,
) (models.EnvironmentNetworkEntity, error) {
	built := BuildEnvironmentNetwork(environmentID, privateNetworkID, opts...)

	entity := models.EnvironmentNetworkEntity{
		ID:               built.ID,
		CreatedAt:        time.Now(),
		UpdatedAt:        time.Now(),
		Role:             built.Role,
		RemovedAt:        built.RemovedAt,
		EnvironmentID:    built.EnvironmentID,
		PrivateNetworkID: built.PrivateNetworkID,
	}

	if err := exec.NewInsert().Model(&entity).Returning("*").Scan(ctx); err != nil {
		return models.EnvironmentNetworkEntity{}, err
	}

	return entity, nil
}

func CreateEnvironmentNetworks(
	ctx context.Context,
	exec storage.Executor,
	environmentID uuid.UUID,
	privateNetworkID uuid.UUID,
	count int,
	opts ...EnvironmentNetworkOption,
) ([]models.EnvironmentNetworkEntity, error) {
	environmentnetworks := make([]models.EnvironmentNetworkEntity, 0, count)

	for i := range count {
		entity, err := CreateEnvironmentNetwork(ctx, exec, environmentID, privateNetworkID, opts...)
		if err != nil {
			return nil, fmt.Errorf("failed to create environmentnetwork %d: %w", i+1, err)
		}
		environmentnetworks = append(environmentnetworks, entity)
	}

	return environmentnetworks, nil
}

func WithEnvironmentNetworksRole(value string) EnvironmentNetworkOption {
	return func(f *EnvironmentNetworkFactory) {
		f.EnvironmentNetworkEntity.Role = value
	}
}

func WithEnvironmentNetworksRemovedAt(value sql.NullTime) EnvironmentNetworkOption {
	return func(f *EnvironmentNetworkFactory) {
		f.EnvironmentNetworkEntity.RemovedAt = value
	}
}

func WithEnvironmentNetworksEnvironmentID(value uuid.UUID) EnvironmentNetworkOption {
	return func(f *EnvironmentNetworkFactory) {
		f.EnvironmentNetworkEntity.EnvironmentID = value
	}
}

func WithEnvironmentNetworksPrivateNetworkID(value uuid.UUID) EnvironmentNetworkOption {
	return func(f *EnvironmentNetworkFactory) {
		f.EnvironmentNetworkEntity.PrivateNetworkID = value
	}
}
