package factories

import (
	"context"
	"database/sql"
	"deploycrate-ce/internal/storage"
	"deploycrate-ce/models"
	"fmt"
	"time"

	"github.com/google/uuid"
)

// Factory declarations below are generated by Andurel.

type EnvironmentTargetFactory struct {
	models.EnvironmentTargetEntity
}

type EnvironmentTargetOption func(*EnvironmentTargetFactory)

func BuildEnvironmentTarget(environmentID uuid.UUID, serverID uuid.UUID, opts ...EnvironmentTargetOption) models.EnvironmentTargetEntity {
	f := &EnvironmentTargetFactory{
		EnvironmentTargetEntity: models.EnvironmentTargetEntity{
			EnvironmentID: environmentID,
			ServerID:      serverID,
			AttachedAt:    time.Time{},
			DetachedAt:    sql.NullTime{Time: time.Now(), Valid: true},
		},
	}

	for _, opt := range opts {
		opt(f)
	}

	return f.EnvironmentTargetEntity
}

func CreateEnvironmentTarget(ctx context.Context, exec storage.Executor, environmentID uuid.UUID, serverID uuid.UUID, opts ...EnvironmentTargetOption) (models.EnvironmentTargetEntity, error) {
	built := BuildEnvironmentTarget(environmentID, serverID, opts...)

	entity := models.EnvironmentTargetEntity{
		ID:            uuid.New(),
		CreatedAt:     time.Now(),
		UpdatedAt:     time.Now(),
		EnvironmentID: built.EnvironmentID,
		ServerID:      built.ServerID,
		AttachedAt:    built.AttachedAt,
		DetachedAt:    built.DetachedAt,
	}

	if err := exec.NewInsert().Model(&entity).Returning("*").Scan(ctx); err != nil {
		return models.EnvironmentTargetEntity{}, err
	}

	return entity, nil
}

func CreateEnvironmentTargets(ctx context.Context, exec storage.Executor, environmentID uuid.UUID, serverID uuid.UUID, count int, opts ...EnvironmentTargetOption) ([]models.EnvironmentTargetEntity, error) {
	environmenttargets := make([]models.EnvironmentTargetEntity, 0, count)

	for i := range count {
		entity, err := CreateEnvironmentTarget(ctx, exec, environmentID, serverID, opts...)
		if err != nil {
			return nil, fmt.Errorf("failed to create environmenttarget %d: %w", i+1, err)
		}
		environmenttargets = append(environmenttargets, entity)
	}

	return environmenttargets, nil
}

func WithEnvironmentTargetsEnvironmentID(value uuid.UUID) EnvironmentTargetOption {
	return func(f *EnvironmentTargetFactory) {
		f.EnvironmentTargetEntity.EnvironmentID = value
	}
}

func WithEnvironmentTargetsServerID(value uuid.UUID) EnvironmentTargetOption {
	return func(f *EnvironmentTargetFactory) {
		f.EnvironmentTargetEntity.ServerID = value
	}
}

func WithEnvironmentTargetsAttachedAt(value time.Time) EnvironmentTargetOption {
	return func(f *EnvironmentTargetFactory) {
		f.EnvironmentTargetEntity.AttachedAt = value
	}
}

func WithEnvironmentTargetsDetachedAt(value sql.NullTime) EnvironmentTargetOption {
	return func(f *EnvironmentTargetFactory) {
		f.EnvironmentTargetEntity.DetachedAt = value
	}
}
