package factories

import (
	"context"
	"database/sql"
	"deploycrate-ce/internal/storage"
	"deploycrate-ce/models"
	"encoding/json"
	"fmt"
	"time"

	"github.com/go-faker/faker/v4"
	"github.com/google/uuid"
)

// Factory declarations below are generated by Andurel.

type EnvironmentRuntimeConfigurationFactory struct {
	models.EnvironmentRuntimeConfigurationEntity
}

type EnvironmentRuntimeConfigurationOption func(*EnvironmentRuntimeConfigurationFactory)

func BuildEnvironmentRuntimeConfiguration(environmentID uuid.UUID, opts ...EnvironmentRuntimeConfigurationOption) models.EnvironmentRuntimeConfigurationEntity {
	f := &EnvironmentRuntimeConfigurationFactory{
		EnvironmentRuntimeConfigurationEntity: models.EnvironmentRuntimeConfigurationEntity{
			EnvironmentID:  environmentID,
			Runtime:        faker.Word(),
			Command:        sql.NullString{String: faker.Word(), Valid: true},
			Arguments:      json.RawMessage{},
			Replicas:       randomInt(1, 1000, 100),
			Ports:          json.RawMessage{},
			ResourceLimits: json.RawMessage{},
			RestartPolicy:  faker.Word(),
			Settings:       json.RawMessage{},
		},
	}

	for _, opt := range opts {
		opt(f)
	}

	return f.EnvironmentRuntimeConfigurationEntity
}

func CreateEnvironmentRuntimeConfiguration(ctx context.Context, exec storage.Executor, environmentID uuid.UUID, opts ...EnvironmentRuntimeConfigurationOption) (models.EnvironmentRuntimeConfigurationEntity, error) {
	built := BuildEnvironmentRuntimeConfiguration(environmentID, opts...)

	entity := models.EnvironmentRuntimeConfigurationEntity{
		ID:             built.ID,
		CreatedAt:      time.Now(),
		UpdatedAt:      time.Now(),
		EnvironmentID:  built.EnvironmentID,
		Runtime:        built.Runtime,
		Command:        built.Command,
		Arguments:      built.Arguments,
		Replicas:       built.Replicas,
		Ports:          built.Ports,
		ResourceLimits: built.ResourceLimits,
		RestartPolicy:  built.RestartPolicy,
		Settings:       built.Settings,
	}

	if err := exec.NewInsert().Model(&entity).Returning("*").Scan(ctx); err != nil {
		return models.EnvironmentRuntimeConfigurationEntity{}, err
	}

	return entity, nil
}

func CreateEnvironmentRuntimeConfigurations(ctx context.Context, exec storage.Executor, environmentID uuid.UUID, count int, opts ...EnvironmentRuntimeConfigurationOption) ([]models.EnvironmentRuntimeConfigurationEntity, error) {
	environmentruntimeconfigurations := make([]models.EnvironmentRuntimeConfigurationEntity, 0, count)

	for i := range count {
		entity, err := CreateEnvironmentRuntimeConfiguration(ctx, exec, environmentID, opts...)
		if err != nil {
			return nil, fmt.Errorf("failed to create environmentruntimeconfiguration %d: %w", i+1, err)
		}
		environmentruntimeconfigurations = append(environmentruntimeconfigurations, entity)
	}

	return environmentruntimeconfigurations, nil
}

func WithEnvironmentRuntimeConfigurationsEnvironmentID(value uuid.UUID) EnvironmentRuntimeConfigurationOption {
	return func(f *EnvironmentRuntimeConfigurationFactory) {
		f.EnvironmentRuntimeConfigurationEntity.EnvironmentID = value
	}
}

func WithEnvironmentRuntimeConfigurationsRuntime(value string) EnvironmentRuntimeConfigurationOption {
	return func(f *EnvironmentRuntimeConfigurationFactory) {
		f.EnvironmentRuntimeConfigurationEntity.Runtime = value
	}
}

func WithEnvironmentRuntimeConfigurationsCommand(value sql.NullString) EnvironmentRuntimeConfigurationOption {
	return func(f *EnvironmentRuntimeConfigurationFactory) {
		f.EnvironmentRuntimeConfigurationEntity.Command = value
	}
}

func WithEnvironmentRuntimeConfigurationsArguments(value json.RawMessage) EnvironmentRuntimeConfigurationOption {
	return func(f *EnvironmentRuntimeConfigurationFactory) {
		f.EnvironmentRuntimeConfigurationEntity.Arguments = value
	}
}

func WithEnvironmentRuntimeConfigurationsReplicas(value int32) EnvironmentRuntimeConfigurationOption {
	return func(f *EnvironmentRuntimeConfigurationFactory) {
		f.EnvironmentRuntimeConfigurationEntity.Replicas = value
	}
}

func WithEnvironmentRuntimeConfigurationsPorts(value json.RawMessage) EnvironmentRuntimeConfigurationOption {
	return func(f *EnvironmentRuntimeConfigurationFactory) {
		f.EnvironmentRuntimeConfigurationEntity.Ports = value
	}
}

func WithEnvironmentRuntimeConfigurationsResourceLimits(value json.RawMessage) EnvironmentRuntimeConfigurationOption {
	return func(f *EnvironmentRuntimeConfigurationFactory) {
		f.EnvironmentRuntimeConfigurationEntity.ResourceLimits = value
	}
}

func WithEnvironmentRuntimeConfigurationsRestartPolicy(value string) EnvironmentRuntimeConfigurationOption {
	return func(f *EnvironmentRuntimeConfigurationFactory) {
		f.EnvironmentRuntimeConfigurationEntity.RestartPolicy = value
	}
}

func WithEnvironmentRuntimeConfigurationsSettings(value json.RawMessage) EnvironmentRuntimeConfigurationOption {
	return func(f *EnvironmentRuntimeConfigurationFactory) {
		f.EnvironmentRuntimeConfigurationEntity.Settings = value
	}
}
