package factories

import (
	"context"
	"database/sql"
	"deploycrate-ce/internal/storage"
	"deploycrate-ce/models"
	"fmt"
	"time"

	"github.com/go-faker/faker/v4"
	"github.com/google/uuid"
)

// Factory declarations below are generated by Andurel.

type EnvironmentHealthCheckStatusFactory struct {
	models.EnvironmentHealthCheckStatusEntity
}

type EnvironmentHealthCheckStatusOption func(*EnvironmentHealthCheckStatusFactory)

func BuildEnvironmentHealthCheckStatus(healthCheckID uuid.UUID, environmentTargetID *uuid.UUID, instanceID *uuid.UUID, releaseID *uuid.UUID, opts ...EnvironmentHealthCheckStatusOption) models.EnvironmentHealthCheckStatusEntity {
	f := &EnvironmentHealthCheckStatusFactory{
		EnvironmentHealthCheckStatusEntity: models.EnvironmentHealthCheckStatusEntity{
			HealthCheckID:       healthCheckID,
			EnvironmentTargetID: environmentTargetID,
			InstanceID:          instanceID,
			ReleaseID:           releaseID,
			State:               faker.Word(),
			StatusCode:          sql.NullInt32{Int32: randomInt(1, 1000, 100), Valid: true},
			DurationMs:          randomInt(1, 1000, 100),
			Error:               sql.NullString{String: faker.Word(), Valid: true},
			ObservedAt:          time.Time{},
		},
	}

	for _, opt := range opts {
		opt(f)
	}

	return f.EnvironmentHealthCheckStatusEntity
}

func CreateEnvironmentHealthCheckStatus(ctx context.Context, exec storage.Executor, healthCheckID uuid.UUID, environmentTargetID *uuid.UUID, instanceID *uuid.UUID, releaseID *uuid.UUID, opts ...EnvironmentHealthCheckStatusOption) (models.EnvironmentHealthCheckStatusEntity, error) {
	built := BuildEnvironmentHealthCheckStatus(healthCheckID, environmentTargetID, instanceID, releaseID, opts...)

	entity := models.EnvironmentHealthCheckStatusEntity{
		ID:                  built.ID,
		CreatedAt:           time.Now(),
		UpdatedAt:           time.Now(),
		HealthCheckID:       built.HealthCheckID,
		EnvironmentTargetID: built.EnvironmentTargetID,
		InstanceID:          built.InstanceID,
		ReleaseID:           built.ReleaseID,
		State:               built.State,
		StatusCode:          built.StatusCode,
		DurationMs:          built.DurationMs,
		Error:               built.Error,
		ObservedAt:          built.ObservedAt,
	}

	if err := exec.NewInsert().Model(&entity).Returning("*").Scan(ctx); err != nil {
		return models.EnvironmentHealthCheckStatusEntity{}, err
	}

	return entity, nil
}

func CreateEnvironmentHealthCheckStatuses(ctx context.Context, exec storage.Executor, healthCheckID uuid.UUID, environmentTargetID *uuid.UUID, instanceID *uuid.UUID, releaseID *uuid.UUID, count int, opts ...EnvironmentHealthCheckStatusOption) ([]models.EnvironmentHealthCheckStatusEntity, error) {
	environmentHealthCheckStatuses := make([]models.EnvironmentHealthCheckStatusEntity, 0, count)

	for i := range count {
		entity, err := CreateEnvironmentHealthCheckStatus(ctx, exec, healthCheckID, environmentTargetID, instanceID, releaseID, opts...)
		if err != nil {
			return nil, fmt.Errorf("failed to create environmenthealthcheckstatus %d: %w", i+1, err)
		}
		environmentHealthCheckStatuses = append(environmentHealthCheckStatuses, entity)
	}

	return environmentHealthCheckStatuses, nil
}

func WithEnvironmentHealthCheckStatusesHealthCheckID(value uuid.UUID) EnvironmentHealthCheckStatusOption {
	return func(f *EnvironmentHealthCheckStatusFactory) {
		f.EnvironmentHealthCheckStatusEntity.HealthCheckID = value
	}
}

func WithEnvironmentHealthCheckStatusesEnvironmentTargetID(value *uuid.UUID) EnvironmentHealthCheckStatusOption {
	return func(f *EnvironmentHealthCheckStatusFactory) {
		f.EnvironmentHealthCheckStatusEntity.EnvironmentTargetID = value
	}
}

func WithEnvironmentHealthCheckStatusesInstanceID(value *uuid.UUID) EnvironmentHealthCheckStatusOption {
	return func(f *EnvironmentHealthCheckStatusFactory) {
		f.EnvironmentHealthCheckStatusEntity.InstanceID = value
	}
}

func WithEnvironmentHealthCheckStatusesReleaseID(value *uuid.UUID) EnvironmentHealthCheckStatusOption {
	return func(f *EnvironmentHealthCheckStatusFactory) {
		f.EnvironmentHealthCheckStatusEntity.ReleaseID = value
	}
}

func WithEnvironmentHealthCheckStatusesState(value string) EnvironmentHealthCheckStatusOption {
	return func(f *EnvironmentHealthCheckStatusFactory) {
		f.EnvironmentHealthCheckStatusEntity.State = value
	}
}

func WithEnvironmentHealthCheckStatusesStatusCode(value sql.NullInt32) EnvironmentHealthCheckStatusOption {
	return func(f *EnvironmentHealthCheckStatusFactory) {
		f.EnvironmentHealthCheckStatusEntity.StatusCode = value
	}
}

func WithEnvironmentHealthCheckStatusesDurationMs(value int32) EnvironmentHealthCheckStatusOption {
	return func(f *EnvironmentHealthCheckStatusFactory) {
		f.EnvironmentHealthCheckStatusEntity.DurationMs = value
	}
}

func WithEnvironmentHealthCheckStatusesError(value sql.NullString) EnvironmentHealthCheckStatusOption {
	return func(f *EnvironmentHealthCheckStatusFactory) {
		f.EnvironmentHealthCheckStatusEntity.Error = value
	}
}

func WithEnvironmentHealthCheckStatusesObservedAt(value time.Time) EnvironmentHealthCheckStatusOption {
	return func(f *EnvironmentHealthCheckStatusFactory) {
		f.EnvironmentHealthCheckStatusEntity.ObservedAt = value
	}
}
