package factories

import (
	"context"
	"database/sql"
	"deploycrate-ce/internal/storage"
	"deploycrate-ce/models"
	"encoding/json"
	"fmt"
	"time"

	"github.com/go-faker/faker/v4"
	"github.com/google/uuid"
)

// Factory declarations below are generated by Andurel.

type GitHubWebhookDeliveryFactory struct {
	models.GitHubWebhookDeliveryEntity
}

type GitHubWebhookDeliveryOption func(*GitHubWebhookDeliveryFactory)

func BuildGitHubWebhookDelivery(
	deliveryID string,
	installationExternalID sql.NullInt64,
	repositoryExternalID sql.NullInt64,
	opts ...GitHubWebhookDeliveryOption,
) models.GitHubWebhookDeliveryEntity {
	f := &GitHubWebhookDeliveryFactory{
		GitHubWebhookDeliveryEntity: models.GitHubWebhookDeliveryEntity{
			DeliveryID:             deliveryID,
			Event:                  faker.Word(),
			Action:                 sql.NullString{String: faker.Word(), Valid: true},
			InstallationExternalID: installationExternalID,
			RepositoryExternalID:   repositoryExternalID,
			BodyDigest:             []byte{},
			Payload:                json.RawMessage{},
			ReceivedAt:             time.Time{},
			ProcessedAt:            sql.NullTime{Time: time.Now(), Valid: true},
			Status:                 faker.Word(),
			Error:                  sql.NullString{String: faker.Word(), Valid: true},
		},
	}

	for _, opt := range opts {
		opt(f)
	}

	return f.GitHubWebhookDeliveryEntity
}

func CreateGitHubWebhookDelivery(
	ctx context.Context,
	exec storage.Executor,
	deliveryID string,
	installationExternalID sql.NullInt64,
	repositoryExternalID sql.NullInt64,
	opts ...GitHubWebhookDeliveryOption,
) (models.GitHubWebhookDeliveryEntity, error) {
	built := BuildGitHubWebhookDelivery(
		deliveryID,
		installationExternalID,
		repositoryExternalID,
		opts...)

	entity := models.GitHubWebhookDeliveryEntity{
		ID:                     uuid.New(),
		CreatedAt:              time.Now(),
		UpdatedAt:              time.Now(),
		DeliveryID:             built.DeliveryID,
		Event:                  built.Event,
		Action:                 built.Action,
		InstallationExternalID: built.InstallationExternalID,
		RepositoryExternalID:   built.RepositoryExternalID,
		BodyDigest:             built.BodyDigest,
		Payload:                built.Payload,
		ReceivedAt:             built.ReceivedAt,
		ProcessedAt:            built.ProcessedAt,
		Status:                 built.Status,
		Error:                  built.Error,
	}

	if err := exec.NewInsert().Model(&entity).Returning("*").Scan(ctx); err != nil {
		return models.GitHubWebhookDeliveryEntity{}, err
	}

	return entity, nil
}

func CreateGitHubWebhookDeliverys(
	ctx context.Context,
	exec storage.Executor,
	deliveryID string,
	installationExternalID sql.NullInt64,
	repositoryExternalID sql.NullInt64,
	count int,
	opts ...GitHubWebhookDeliveryOption,
) ([]models.GitHubWebhookDeliveryEntity, error) {
	githubwebhookdeliverys := make([]models.GitHubWebhookDeliveryEntity, 0, count)

	for i := range count {
		entity, err := CreateGitHubWebhookDelivery(
			ctx,
			exec,
			deliveryID,
			installationExternalID,
			repositoryExternalID,
			opts...)
		if err != nil {
			return nil, fmt.Errorf("failed to create githubwebhookdelivery %d: %w", i+1, err)
		}
		githubwebhookdeliverys = append(githubwebhookdeliverys, entity)
	}

	return githubwebhookdeliverys, nil
}

func WithGithubWebhookDeliveriesDeliveryID(value string) GitHubWebhookDeliveryOption {
	return func(f *GitHubWebhookDeliveryFactory) {
		f.GitHubWebhookDeliveryEntity.DeliveryID = value
	}
}

func WithGithubWebhookDeliveriesEvent(value string) GitHubWebhookDeliveryOption {
	return func(f *GitHubWebhookDeliveryFactory) {
		f.GitHubWebhookDeliveryEntity.Event = value
	}
}

func WithGithubWebhookDeliveriesAction(value sql.NullString) GitHubWebhookDeliveryOption {
	return func(f *GitHubWebhookDeliveryFactory) {
		f.GitHubWebhookDeliveryEntity.Action = value
	}
}

func WithGithubWebhookDeliveriesInstallationExternalID(
	value sql.NullInt64,
) GitHubWebhookDeliveryOption {
	return func(f *GitHubWebhookDeliveryFactory) {
		f.GitHubWebhookDeliveryEntity.InstallationExternalID = value
	}
}

func WithGithubWebhookDeliveriesRepositoryExternalID(
	value sql.NullInt64,
) GitHubWebhookDeliveryOption {
	return func(f *GitHubWebhookDeliveryFactory) {
		f.GitHubWebhookDeliveryEntity.RepositoryExternalID = value
	}
}

func WithGithubWebhookDeliveriesBodyDigest(value []byte) GitHubWebhookDeliveryOption {
	return func(f *GitHubWebhookDeliveryFactory) {
		f.GitHubWebhookDeliveryEntity.BodyDigest = value
	}
}

func WithGithubWebhookDeliveriesPayload(value json.RawMessage) GitHubWebhookDeliveryOption {
	return func(f *GitHubWebhookDeliveryFactory) {
		f.GitHubWebhookDeliveryEntity.Payload = value
	}
}

func WithGithubWebhookDeliveriesReceivedAt(value time.Time) GitHubWebhookDeliveryOption {
	return func(f *GitHubWebhookDeliveryFactory) {
		f.GitHubWebhookDeliveryEntity.ReceivedAt = value
	}
}

func WithGithubWebhookDeliveriesProcessedAt(value sql.NullTime) GitHubWebhookDeliveryOption {
	return func(f *GitHubWebhookDeliveryFactory) {
		f.GitHubWebhookDeliveryEntity.ProcessedAt = value
	}
}

func WithGithubWebhookDeliveriesStatus(value string) GitHubWebhookDeliveryOption {
	return func(f *GitHubWebhookDeliveryFactory) {
		f.GitHubWebhookDeliveryEntity.Status = value
	}
}

func WithGithubWebhookDeliveriesError(value sql.NullString) GitHubWebhookDeliveryOption {
	return func(f *GitHubWebhookDeliveryFactory) {
		f.GitHubWebhookDeliveryEntity.Error = value
	}
}
