package factories

import (
	"context"
	"database/sql"
	"deploycrate-ce/internal/storage"
	"deploycrate-ce/models"
	"fmt"
	"time"

	"github.com/go-faker/faker/v4"
	"github.com/google/uuid"
)

// Factory declarations below are generated by Andurel.

type GitHubRepositoryFactory struct {
	models.GitHubRepositoryEntity
}

type GitHubRepositoryOption func(*GitHubRepositoryFactory)

func BuildGitHubRepository(
	gitHubInstallationID uuid.UUID,
	externalID int64,
	nodeID string,
	opts ...GitHubRepositoryOption,
) models.GitHubRepositoryEntity {
	f := &GitHubRepositoryFactory{
		GitHubRepositoryEntity: models.GitHubRepositoryEntity{
			RemovedAt:            sql.NullTime{Time: time.Now(), Valid: true},
			GitHubInstallationID: gitHubInstallationID,
			ExternalID:           externalID,
			NodeID:               nodeID,
			OwnerLogin:           faker.Word(),
			Name:                 faker.Word(),
			FullName:             faker.Word(),
			DefaultBranch:        faker.Word(),
			Visibility:           faker.Word(),
			HTMLURL:              faker.Word(),
			LastSyncedAt:         time.Time{},
		},
	}

	for _, opt := range opts {
		opt(f)
	}

	return f.GitHubRepositoryEntity
}

func CreateGitHubRepository(
	ctx context.Context,
	exec storage.Executor,
	gitHubInstallationID uuid.UUID,
	externalID int64,
	nodeID string,
	opts ...GitHubRepositoryOption,
) (models.GitHubRepositoryEntity, error) {
	built := BuildGitHubRepository(gitHubInstallationID, externalID, nodeID, opts...)

	entity := models.GitHubRepositoryEntity{
		ID:                   uuid.New(),
		CreatedAt:            time.Now(),
		UpdatedAt:            time.Now(),
		RemovedAt:            built.RemovedAt,
		GitHubInstallationID: built.GitHubInstallationID,
		ExternalID:           built.ExternalID,
		NodeID:               built.NodeID,
		OwnerLogin:           built.OwnerLogin,
		Name:                 built.Name,
		FullName:             built.FullName,
		DefaultBranch:        built.DefaultBranch,
		Visibility:           built.Visibility,
		HTMLURL:              built.HTMLURL,
		LastSyncedAt:         built.LastSyncedAt,
	}

	if err := exec.NewInsert().Model(&entity).Returning("*").Scan(ctx); err != nil {
		return models.GitHubRepositoryEntity{}, err
	}

	return entity, nil
}

func CreateGitHubRepositorys(
	ctx context.Context,
	exec storage.Executor,
	gitHubInstallationID uuid.UUID,
	externalID int64,
	nodeID string,
	count int,
	opts ...GitHubRepositoryOption,
) ([]models.GitHubRepositoryEntity, error) {
	githubrepositorys := make([]models.GitHubRepositoryEntity, 0, count)

	for i := range count {
		entity, err := CreateGitHubRepository(
			ctx,
			exec,
			gitHubInstallationID,
			externalID,
			nodeID,
			opts...)
		if err != nil {
			return nil, fmt.Errorf("failed to create githubrepository %d: %w", i+1, err)
		}
		githubrepositorys = append(githubrepositorys, entity)
	}

	return githubrepositorys, nil
}

func WithGithubRepositoriesRemovedAt(value sql.NullTime) GitHubRepositoryOption {
	return func(f *GitHubRepositoryFactory) {
		f.GitHubRepositoryEntity.RemovedAt = value
	}
}

func WithGithubRepositoriesGitHubInstallationID(value uuid.UUID) GitHubRepositoryOption {
	return func(f *GitHubRepositoryFactory) {
		f.GitHubRepositoryEntity.GitHubInstallationID = value
	}
}

func WithGithubRepositoriesExternalID(value int64) GitHubRepositoryOption {
	return func(f *GitHubRepositoryFactory) {
		f.GitHubRepositoryEntity.ExternalID = value
	}
}

func WithGithubRepositoriesNodeID(value string) GitHubRepositoryOption {
	return func(f *GitHubRepositoryFactory) {
		f.GitHubRepositoryEntity.NodeID = value
	}
}

func WithGithubRepositoriesOwnerLogin(value string) GitHubRepositoryOption {
	return func(f *GitHubRepositoryFactory) {
		f.GitHubRepositoryEntity.OwnerLogin = value
	}
}

func WithGithubRepositoriesName(value string) GitHubRepositoryOption {
	return func(f *GitHubRepositoryFactory) {
		f.GitHubRepositoryEntity.Name = value
	}
}

func WithGithubRepositoriesFullName(value string) GitHubRepositoryOption {
	return func(f *GitHubRepositoryFactory) {
		f.GitHubRepositoryEntity.FullName = value
	}
}

func WithGithubRepositoriesDefaultBranch(value string) GitHubRepositoryOption {
	return func(f *GitHubRepositoryFactory) {
		f.GitHubRepositoryEntity.DefaultBranch = value
	}
}

func WithGithubRepositoriesVisibility(value string) GitHubRepositoryOption {
	return func(f *GitHubRepositoryFactory) {
		f.GitHubRepositoryEntity.Visibility = value
	}
}

func WithGithubRepositoriesHTMLURL(value string) GitHubRepositoryOption {
	return func(f *GitHubRepositoryFactory) {
		f.GitHubRepositoryEntity.HTMLURL = value
	}
}

func WithGithubRepositoriesLastSyncedAt(value time.Time) GitHubRepositoryOption {
	return func(f *GitHubRepositoryFactory) {
		f.GitHubRepositoryEntity.LastSyncedAt = value
	}
}
