package factories

import (
	"context"
	"deploycrate-ce/internal/storage"
	"deploycrate-ce/models"
	"fmt"
	"time"

	"github.com/google/uuid"
)

// Factory declarations below are generated by Andurel.

type GitHubEnvironmentSourceFactory struct {
	models.GitHubEnvironmentSourceEntity
}

type GitHubEnvironmentSourceOption func(*GitHubEnvironmentSourceFactory)

func BuildGitHubEnvironmentSource(environmentSourceID uuid.UUID, gitHubRepositoryID uuid.UUID, opts ...GitHubEnvironmentSourceOption) models.GitHubEnvironmentSourceEntity {
	f := &GitHubEnvironmentSourceFactory{
		GitHubEnvironmentSourceEntity: models.GitHubEnvironmentSourceEntity{
			EnvironmentSourceID: environmentSourceID,
			GitHubRepositoryID:  gitHubRepositoryID,
		},
	}

	for _, opt := range opts {
		opt(f)
	}

	return f.GitHubEnvironmentSourceEntity
}

func CreateGitHubEnvironmentSource(ctx context.Context, exec storage.Executor, environmentSourceID uuid.UUID, gitHubRepositoryID uuid.UUID, opts ...GitHubEnvironmentSourceOption) (models.GitHubEnvironmentSourceEntity, error) {
	built := BuildGitHubEnvironmentSource(environmentSourceID, gitHubRepositoryID, opts...)

	entity := models.GitHubEnvironmentSourceEntity{
		CreatedAt:           time.Now(),
		UpdatedAt:           time.Now(),
		EnvironmentSourceID: built.EnvironmentSourceID,
		GitHubRepositoryID:  built.GitHubRepositoryID,
	}

	if err := exec.NewInsert().Model(&entity).Returning("*").Scan(ctx); err != nil {
		return models.GitHubEnvironmentSourceEntity{}, err
	}

	return entity, nil
}

func CreateGitHubEnvironmentSources(ctx context.Context, exec storage.Executor, environmentSourceID uuid.UUID, gitHubRepositoryID uuid.UUID, count int, opts ...GitHubEnvironmentSourceOption) ([]models.GitHubEnvironmentSourceEntity, error) {
	githubenvironmentsources := make([]models.GitHubEnvironmentSourceEntity, 0, count)

	for i := range count {
		entity, err := CreateGitHubEnvironmentSource(ctx, exec, environmentSourceID, gitHubRepositoryID, opts...)
		if err != nil {
			return nil, fmt.Errorf("failed to create githubenvironmentsource %d: %w", i+1, err)
		}
		githubenvironmentsources = append(githubenvironmentsources, entity)
	}

	return githubenvironmentsources, nil
}

func WithGithubEnvironmentSourcesEnvironmentSourceID(value uuid.UUID) GitHubEnvironmentSourceOption {
	return func(f *GitHubEnvironmentSourceFactory) {
		f.GitHubEnvironmentSourceEntity.EnvironmentSourceID = value
	}
}

func WithGithubEnvironmentSourcesGitHubRepositoryID(value uuid.UUID) GitHubEnvironmentSourceOption {
	return func(f *GitHubEnvironmentSourceFactory) {
		f.GitHubEnvironmentSourceEntity.GitHubRepositoryID = value
	}
}
