package factories

import (
	"context"
	"database/sql"
	"deploycrate-ce/internal/storage"
	"deploycrate-ce/models"
	"encoding/json"
	"fmt"
	"time"

	"github.com/go-faker/faker/v4"
	"github.com/google/uuid"
)

// Factory declarations below are generated by Andurel.

type GitHubAppFactory struct {
	models.GitHubAppEntity
}

type GitHubAppOption func(*GitHubAppFactory)

func BuildGitHubApp(
	credentialID uuid.UUID,
	instanceID uuid.UUID,
	externalID int64,
	clientID string,
	ownerID int64,
	opts ...GitHubAppOption,
) models.GitHubAppEntity {
	f := &GitHubAppFactory{
		GitHubAppEntity: models.GitHubAppEntity{
			ArchivedAt:   sql.NullTime{Time: time.Now(), Valid: true},
			CredentialID: credentialID,
			InstanceID:   instanceID,
			ExternalID:   externalID,
			ClientID:     clientID,
			Slug:         faker.Word(),
			Name:         faker.Word(),
			OwnerID:      ownerID,
			OwnerLogin:   faker.Word(),
			OwnerType:    faker.Word(),
			HTMLURL:      faker.Word(),
			Permissions:  json.RawMessage{},
			Events:       json.RawMessage{},
			VerifiedAt:   sql.NullTime{Time: time.Now(), Valid: true},
		},
	}

	for _, opt := range opts {
		opt(f)
	}

	return f.GitHubAppEntity
}

func CreateGitHubApp(
	ctx context.Context,
	exec storage.Executor,
	credentialID uuid.UUID,
	instanceID uuid.UUID,
	externalID int64,
	clientID string,
	ownerID int64,
	opts ...GitHubAppOption,
) (models.GitHubAppEntity, error) {
	built := BuildGitHubApp(credentialID, instanceID, externalID, clientID, ownerID, opts...)

	entity := models.GitHubAppEntity{
		ID:           uuid.New(),
		CreatedAt:    time.Now(),
		UpdatedAt:    time.Now(),
		ArchivedAt:   built.ArchivedAt,
		CredentialID: built.CredentialID,
		InstanceID:   built.InstanceID,
		ExternalID:   built.ExternalID,
		ClientID:     built.ClientID,
		Slug:         built.Slug,
		Name:         built.Name,
		OwnerID:      built.OwnerID,
		OwnerLogin:   built.OwnerLogin,
		OwnerType:    built.OwnerType,
		HTMLURL:      built.HTMLURL,
		Permissions:  built.Permissions,
		Events:       built.Events,
		VerifiedAt:   built.VerifiedAt,
	}

	if err := exec.NewInsert().Model(&entity).Returning("*").Scan(ctx); err != nil {
		return models.GitHubAppEntity{}, err
	}

	return entity, nil
}

func CreateGitHubApps(
	ctx context.Context,
	exec storage.Executor,
	credentialID uuid.UUID,
	instanceID uuid.UUID,
	externalID int64,
	clientID string,
	ownerID int64,
	count int,
	opts ...GitHubAppOption,
) ([]models.GitHubAppEntity, error) {
	githubapps := make([]models.GitHubAppEntity, 0, count)

	for i := range count {
		entity, err := CreateGitHubApp(
			ctx,
			exec,
			credentialID,
			instanceID,
			externalID,
			clientID,
			ownerID,
			opts...)
		if err != nil {
			return nil, fmt.Errorf("failed to create githubapp %d: %w", i+1, err)
		}
		githubapps = append(githubapps, entity)
	}

	return githubapps, nil
}

func WithGithubAppsArchivedAt(value sql.NullTime) GitHubAppOption {
	return func(f *GitHubAppFactory) {
		f.GitHubAppEntity.ArchivedAt = value
	}
}

func WithGithubAppsCredentialID(value uuid.UUID) GitHubAppOption {
	return func(f *GitHubAppFactory) {
		f.GitHubAppEntity.CredentialID = value
	}
}

func WithGithubAppsInstanceID(value uuid.UUID) GitHubAppOption {
	return func(f *GitHubAppFactory) {
		f.GitHubAppEntity.InstanceID = value
	}
}

func WithGithubAppsExternalID(value int64) GitHubAppOption {
	return func(f *GitHubAppFactory) {
		f.GitHubAppEntity.ExternalID = value
	}
}

func WithGithubAppsClientID(value string) GitHubAppOption {
	return func(f *GitHubAppFactory) {
		f.GitHubAppEntity.ClientID = value
	}
}

func WithGithubAppsSlug(value string) GitHubAppOption {
	return func(f *GitHubAppFactory) {
		f.GitHubAppEntity.Slug = value
	}
}

func WithGithubAppsName(value string) GitHubAppOption {
	return func(f *GitHubAppFactory) {
		f.GitHubAppEntity.Name = value
	}
}

func WithGithubAppsOwnerID(value int64) GitHubAppOption {
	return func(f *GitHubAppFactory) {
		f.GitHubAppEntity.OwnerID = value
	}
}

func WithGithubAppsOwnerLogin(value string) GitHubAppOption {
	return func(f *GitHubAppFactory) {
		f.GitHubAppEntity.OwnerLogin = value
	}
}

func WithGithubAppsOwnerType(value string) GitHubAppOption {
	return func(f *GitHubAppFactory) {
		f.GitHubAppEntity.OwnerType = value
	}
}

func WithGithubAppsHTMLURL(value string) GitHubAppOption {
	return func(f *GitHubAppFactory) {
		f.GitHubAppEntity.HTMLURL = value
	}
}

func WithGithubAppsPermissions(value json.RawMessage) GitHubAppOption {
	return func(f *GitHubAppFactory) {
		f.GitHubAppEntity.Permissions = value
	}
}

func WithGithubAppsEvents(value json.RawMessage) GitHubAppOption {
	return func(f *GitHubAppFactory) {
		f.GitHubAppEntity.Events = value
	}
}

func WithGithubAppsVerifiedAt(value sql.NullTime) GitHubAppOption {
	return func(f *GitHubAppFactory) {
		f.GitHubAppEntity.VerifiedAt = value
	}
}
