package factories

import (
	"context"
	"database/sql"
	"deploycrate-ce/internal/storage"
	"deploycrate-ce/models"
	"encoding/json"
	"fmt"
	"time"

	"github.com/go-faker/faker/v4"
	"github.com/google/uuid"
)

// Factory declarations below are generated by Andurel.

type GitHubInstallationFactory struct {
	models.GitHubInstallationEntity
}

type GitHubInstallationOption func(*GitHubInstallationFactory)

func BuildGitHubInstallation(
	gitHubAppID uuid.UUID,
	externalID int64,
	accountID int64,
	opts ...GitHubInstallationOption,
) models.GitHubInstallationEntity {
	f := &GitHubInstallationFactory{
		GitHubInstallationEntity: models.GitHubInstallationEntity{
			ArchivedAt:          sql.NullTime{Time: time.Now(), Valid: true},
			GitHubAppID:         gitHubAppID,
			ExternalID:          externalID,
			AccountID:           accountID,
			AccountLogin:        faker.Word(),
			AccountType:         faker.Word(),
			RepositorySelection: faker.Word(),
			Permissions:         json.RawMessage{},
			Events:              json.RawMessage{},
			SuspendedAt:         sql.NullTime{Time: time.Now(), Valid: true},
			LastSyncedAt:        sql.NullTime{Time: time.Now(), Valid: true},
		},
	}

	for _, opt := range opts {
		opt(f)
	}

	return f.GitHubInstallationEntity
}

func CreateGitHubInstallation(
	ctx context.Context,
	exec storage.Executor,
	gitHubAppID uuid.UUID,
	externalID int64,
	accountID int64,
	opts ...GitHubInstallationOption,
) (models.GitHubInstallationEntity, error) {
	built := BuildGitHubInstallation(gitHubAppID, externalID, accountID, opts...)

	entity := models.GitHubInstallationEntity{
		ID:                  uuid.New(),
		CreatedAt:           time.Now(),
		UpdatedAt:           time.Now(),
		ArchivedAt:          built.ArchivedAt,
		GitHubAppID:         built.GitHubAppID,
		ExternalID:          built.ExternalID,
		AccountID:           built.AccountID,
		AccountLogin:        built.AccountLogin,
		AccountType:         built.AccountType,
		RepositorySelection: built.RepositorySelection,
		Permissions:         built.Permissions,
		Events:              built.Events,
		SuspendedAt:         built.SuspendedAt,
		LastSyncedAt:        built.LastSyncedAt,
	}

	if err := exec.NewInsert().Model(&entity).Returning("*").Scan(ctx); err != nil {
		return models.GitHubInstallationEntity{}, err
	}

	return entity, nil
}

func CreateGitHubInstallations(
	ctx context.Context,
	exec storage.Executor,
	gitHubAppID uuid.UUID,
	externalID int64,
	accountID int64,
	count int,
	opts ...GitHubInstallationOption,
) ([]models.GitHubInstallationEntity, error) {
	githubinstallations := make([]models.GitHubInstallationEntity, 0, count)

	for i := range count {
		entity, err := CreateGitHubInstallation(
			ctx,
			exec,
			gitHubAppID,
			externalID,
			accountID,
			opts...)
		if err != nil {
			return nil, fmt.Errorf("failed to create githubinstallation %d: %w", i+1, err)
		}
		githubinstallations = append(githubinstallations, entity)
	}

	return githubinstallations, nil
}

func WithGithubInstallationsArchivedAt(value sql.NullTime) GitHubInstallationOption {
	return func(f *GitHubInstallationFactory) {
		f.GitHubInstallationEntity.ArchivedAt = value
	}
}

func WithGithubInstallationsGitHubAppID(value uuid.UUID) GitHubInstallationOption {
	return func(f *GitHubInstallationFactory) {
		f.GitHubInstallationEntity.GitHubAppID = value
	}
}

func WithGithubInstallationsExternalID(value int64) GitHubInstallationOption {
	return func(f *GitHubInstallationFactory) {
		f.GitHubInstallationEntity.ExternalID = value
	}
}

func WithGithubInstallationsAccountID(value int64) GitHubInstallationOption {
	return func(f *GitHubInstallationFactory) {
		f.GitHubInstallationEntity.AccountID = value
	}
}

func WithGithubInstallationsAccountLogin(value string) GitHubInstallationOption {
	return func(f *GitHubInstallationFactory) {
		f.GitHubInstallationEntity.AccountLogin = value
	}
}

func WithGithubInstallationsAccountType(value string) GitHubInstallationOption {
	return func(f *GitHubInstallationFactory) {
		f.GitHubInstallationEntity.AccountType = value
	}
}

func WithGithubInstallationsRepositorySelection(value string) GitHubInstallationOption {
	return func(f *GitHubInstallationFactory) {
		f.GitHubInstallationEntity.RepositorySelection = value
	}
}

func WithGithubInstallationsPermissions(value json.RawMessage) GitHubInstallationOption {
	return func(f *GitHubInstallationFactory) {
		f.GitHubInstallationEntity.Permissions = value
	}
}

func WithGithubInstallationsEvents(value json.RawMessage) GitHubInstallationOption {
	return func(f *GitHubInstallationFactory) {
		f.GitHubInstallationEntity.Events = value
	}
}

func WithGithubInstallationsSuspendedAt(value sql.NullTime) GitHubInstallationOption {
	return func(f *GitHubInstallationFactory) {
		f.GitHubInstallationEntity.SuspendedAt = value
	}
}

func WithGithubInstallationsLastSyncedAt(value sql.NullTime) GitHubInstallationOption {
	return func(f *GitHubInstallationFactory) {
		f.GitHubInstallationEntity.LastSyncedAt = value
	}
}
