package factories

import (
	"context"
	"database/sql"
	"deploycrate-ce/internal/storage"
	"deploycrate-ce/models"
	"fmt"
	"time"

	"github.com/go-faker/faker/v4"
	"github.com/google/uuid"
)

// Factory declarations below are generated by Andurel.

type GitHubAppSetupAttemptFactory struct {
	models.GitHubAppSetupAttemptEntity
}

type GitHubAppSetupAttemptOption func(*GitHubAppSetupAttemptFactory)

func BuildGitHubAppSetupAttempt(
	instanceID uuid.UUID,
	userID uuid.UUID,
	opts ...GitHubAppSetupAttemptOption,
) models.GitHubAppSetupAttemptEntity {
	f := &GitHubAppSetupAttemptFactory{
		GitHubAppSetupAttemptEntity: models.GitHubAppSetupAttemptEntity{
			InstanceID:  instanceID,
			UserID:      userID,
			Purpose:     faker.Word(),
			StatePrefix: faker.Word(),
			StateDigest: []byte{},
			OwnerType:   sql.NullString{String: faker.Word(), Valid: true},
			OwnerLogin:  sql.NullString{String: faker.Word(), Valid: true},
			ExpiresAt:   time.Time{},
			CompletedAt: sql.NullTime{Time: time.Now(), Valid: true},
			Error:       sql.NullString{String: faker.Word(), Valid: true},
		},
	}

	for _, opt := range opts {
		opt(f)
	}

	return f.GitHubAppSetupAttemptEntity
}

func CreateGitHubAppSetupAttempt(
	ctx context.Context,
	exec storage.Executor,
	instanceID uuid.UUID,
	userID uuid.UUID,
	opts ...GitHubAppSetupAttemptOption,
) (models.GitHubAppSetupAttemptEntity, error) {
	built := BuildGitHubAppSetupAttempt(instanceID, userID, opts...)

	entity := models.GitHubAppSetupAttemptEntity{
		ID:          uuid.New(),
		CreatedAt:   time.Now(),
		UpdatedAt:   time.Now(),
		InstanceID:  built.InstanceID,
		UserID:      built.UserID,
		Purpose:     built.Purpose,
		StatePrefix: built.StatePrefix,
		StateDigest: built.StateDigest,
		OwnerType:   built.OwnerType,
		OwnerLogin:  built.OwnerLogin,
		ExpiresAt:   built.ExpiresAt,
		CompletedAt: built.CompletedAt,
		Error:       built.Error,
	}

	if err := exec.NewInsert().Model(&entity).Returning("*").Scan(ctx); err != nil {
		return models.GitHubAppSetupAttemptEntity{}, err
	}

	return entity, nil
}

func CreateGitHubAppSetupAttempts(
	ctx context.Context,
	exec storage.Executor,
	instanceID uuid.UUID,
	userID uuid.UUID,
	count int,
	opts ...GitHubAppSetupAttemptOption,
) ([]models.GitHubAppSetupAttemptEntity, error) {
	githubappsetupattempts := make([]models.GitHubAppSetupAttemptEntity, 0, count)

	for i := range count {
		entity, err := CreateGitHubAppSetupAttempt(ctx, exec, instanceID, userID, opts...)
		if err != nil {
			return nil, fmt.Errorf("failed to create githubappsetupattempt %d: %w", i+1, err)
		}
		githubappsetupattempts = append(githubappsetupattempts, entity)
	}

	return githubappsetupattempts, nil
}

func WithGithubAppSetupAttemptsInstanceID(value uuid.UUID) GitHubAppSetupAttemptOption {
	return func(f *GitHubAppSetupAttemptFactory) {
		f.GitHubAppSetupAttemptEntity.InstanceID = value
	}
}

func WithGithubAppSetupAttemptsUserID(value uuid.UUID) GitHubAppSetupAttemptOption {
	return func(f *GitHubAppSetupAttemptFactory) {
		f.GitHubAppSetupAttemptEntity.UserID = value
	}
}

func WithGithubAppSetupAttemptsPurpose(value string) GitHubAppSetupAttemptOption {
	return func(f *GitHubAppSetupAttemptFactory) {
		f.GitHubAppSetupAttemptEntity.Purpose = value
	}
}

func WithGithubAppSetupAttemptsStatePrefix(value string) GitHubAppSetupAttemptOption {
	return func(f *GitHubAppSetupAttemptFactory) {
		f.GitHubAppSetupAttemptEntity.StatePrefix = value
	}
}

func WithGithubAppSetupAttemptsStateDigest(value []byte) GitHubAppSetupAttemptOption {
	return func(f *GitHubAppSetupAttemptFactory) {
		f.GitHubAppSetupAttemptEntity.StateDigest = value
	}
}

func WithGithubAppSetupAttemptsOwnerType(value sql.NullString) GitHubAppSetupAttemptOption {
	return func(f *GitHubAppSetupAttemptFactory) {
		f.GitHubAppSetupAttemptEntity.OwnerType = value
	}
}

func WithGithubAppSetupAttemptsOwnerLogin(value sql.NullString) GitHubAppSetupAttemptOption {
	return func(f *GitHubAppSetupAttemptFactory) {
		f.GitHubAppSetupAttemptEntity.OwnerLogin = value
	}
}

func WithGithubAppSetupAttemptsExpiresAt(value time.Time) GitHubAppSetupAttemptOption {
	return func(f *GitHubAppSetupAttemptFactory) {
		f.GitHubAppSetupAttemptEntity.ExpiresAt = value
	}
}

func WithGithubAppSetupAttemptsCompletedAt(value sql.NullTime) GitHubAppSetupAttemptOption {
	return func(f *GitHubAppSetupAttemptFactory) {
		f.GitHubAppSetupAttemptEntity.CompletedAt = value
	}
}

func WithGithubAppSetupAttemptsError(value sql.NullString) GitHubAppSetupAttemptOption {
	return func(f *GitHubAppSetupAttemptFactory) {
		f.GitHubAppSetupAttemptEntity.Error = value
	}
}
