package factories

import (
	"context"
	"database/sql"
	"deploycrate-ce/internal/storage"
	"deploycrate-ce/models"
	"encoding/json"
	"fmt"
	"time"

	"github.com/go-faker/faker/v4"
	"github.com/google/uuid"
)

// Factory declarations below are generated by Andurel.

type InstanceFactory struct {
	models.InstanceEntity
}

type InstanceOption func(*InstanceFactory)

func BuildInstance(deploymentID uuid.UUID, releaseID uuid.UUID, environmentTargetID uuid.UUID, externalID string, opts ...InstanceOption) models.InstanceEntity {
	f := &InstanceFactory{
		InstanceEntity: models.InstanceEntity{
			DeploymentID:        deploymentID,
			ReleaseID:           releaseID,
			EnvironmentTargetID: environmentTargetID,
			ExternalID:          externalID,
			Slot:                faker.Word(),
			ReplicaKey:          faker.Word(),
			State:               faker.Word(),
			Ports:               json.RawMessage{},
			ObservedAt:          time.Time{},
			RemovedAt:           sql.NullTime{Time: time.Now(), Valid: true},
		},
	}

	for _, opt := range opts {
		opt(f)
	}

	return f.InstanceEntity
}

func CreateInstance(ctx context.Context, exec storage.Executor, deploymentID uuid.UUID, releaseID uuid.UUID, environmentTargetID uuid.UUID, externalID string, opts ...InstanceOption) (models.InstanceEntity, error) {
	built := BuildInstance(deploymentID, releaseID, environmentTargetID, externalID, opts...)

	entity := models.InstanceEntity{
		ID:                  uuid.New(),
		CreatedAt:           time.Now(),
		UpdatedAt:           time.Now(),
		DeploymentID:        built.DeploymentID,
		ReleaseID:           built.ReleaseID,
		EnvironmentTargetID: built.EnvironmentTargetID,
		ExternalID:          built.ExternalID,
		Slot:                built.Slot,
		ReplicaKey:          built.ReplicaKey,
		State:               built.State,
		Ports:               built.Ports,
		ObservedAt:          built.ObservedAt,
		RemovedAt:           built.RemovedAt,
	}

	if err := exec.NewInsert().Model(&entity).Returning("*").Scan(ctx); err != nil {
		return models.InstanceEntity{}, err
	}

	return entity, nil
}

func CreateInstances(ctx context.Context, exec storage.Executor, deploymentID uuid.UUID, releaseID uuid.UUID, environmentTargetID uuid.UUID, externalID string, count int, opts ...InstanceOption) ([]models.InstanceEntity, error) {
	instances := make([]models.InstanceEntity, 0, count)

	for i := range count {
		entity, err := CreateInstance(ctx, exec, deploymentID, releaseID, environmentTargetID, externalID, opts...)
		if err != nil {
			return nil, fmt.Errorf("failed to create instance %d: %w", i+1, err)
		}
		instances = append(instances, entity)
	}

	return instances, nil
}

func WithInstancesDeploymentID(value uuid.UUID) InstanceOption {
	return func(f *InstanceFactory) {
		f.InstanceEntity.DeploymentID = value
	}
}

func WithInstancesReleaseID(value uuid.UUID) InstanceOption {
	return func(f *InstanceFactory) {
		f.InstanceEntity.ReleaseID = value
	}
}

func WithInstancesEnvironmentTargetID(value uuid.UUID) InstanceOption {
	return func(f *InstanceFactory) {
		f.InstanceEntity.EnvironmentTargetID = value
	}
}

func WithInstancesExternalID(value string) InstanceOption {
	return func(f *InstanceFactory) {
		f.InstanceEntity.ExternalID = value
	}
}

func WithInstancesSlot(value string) InstanceOption {
	return func(f *InstanceFactory) {
		f.InstanceEntity.Slot = value
	}
}

func WithInstancesReplicaKey(value string) InstanceOption {
	return func(f *InstanceFactory) {
		f.InstanceEntity.ReplicaKey = value
	}
}

func WithInstancesState(value string) InstanceOption {
	return func(f *InstanceFactory) {
		f.InstanceEntity.State = value
	}
}

func WithInstancesPorts(value json.RawMessage) InstanceOption {
	return func(f *InstanceFactory) {
		f.InstanceEntity.Ports = value
	}
}

func WithInstancesObservedAt(value time.Time) InstanceOption {
	return func(f *InstanceFactory) {
		f.InstanceEntity.ObservedAt = value
	}
}

func WithInstancesRemovedAt(value sql.NullTime) InstanceOption {
	return func(f *InstanceFactory) {
		f.InstanceEntity.RemovedAt = value
	}
}
