package factories

import (
	"context"
	"database/sql"
	"deploycrate-ce/internal/storage"
	"deploycrate-ce/models"
	"encoding/json"
	"fmt"
	"time"

	"github.com/go-faker/faker/v4"
	"github.com/google/uuid"
)

// Factory declarations below are generated by Andurel.

type NetworkAccessRuleApplicationFactory struct {
	models.NetworkAccessRuleApplicationEntity
}

type NetworkAccessRuleApplicationOption func(*NetworkAccessRuleApplicationFactory)

func BuildNetworkAccessRuleApplication(externalID sql.NullString, networkAccessRuleID uuid.UUID, environmentTargetNetworkID int32, opts ...NetworkAccessRuleApplicationOption) models.NetworkAccessRuleApplicationEntity {
	f := &NetworkAccessRuleApplicationFactory{
		NetworkAccessRuleApplicationEntity: models.NetworkAccessRuleApplicationEntity{
			Driver:                     faker.Word(),
			ExternalID:                 externalID,
			Configuration:              json.RawMessage{},
			State:                      faker.Word(),
			AppliedAt:                  sql.NullTime{Time: time.Now(), Valid: true},
			ObservedAt:                 sql.NullTime{Time: time.Now(), Valid: true},
			RemovedAt:                  sql.NullTime{Time: time.Now(), Valid: true},
			Error:                      sql.NullString{String: faker.Word(), Valid: true},
			NetworkAccessRuleID:        networkAccessRuleID,
			EnvironmentTargetNetworkID: environmentTargetNetworkID,
		},
	}

	for _, opt := range opts {
		opt(f)
	}

	return f.NetworkAccessRuleApplicationEntity
}

func CreateNetworkAccessRuleApplication(ctx context.Context, exec storage.Executor, externalID sql.NullString, networkAccessRuleID uuid.UUID, environmentTargetNetworkID int32, opts ...NetworkAccessRuleApplicationOption) (models.NetworkAccessRuleApplicationEntity, error) {
	built := BuildNetworkAccessRuleApplication(externalID, networkAccessRuleID, environmentTargetNetworkID, opts...)

	entity := models.NetworkAccessRuleApplicationEntity{
		ID:                         uuid.New(),
		CreatedAt:                  time.Now(),
		UpdatedAt:                  time.Now(),
		Driver:                     built.Driver,
		ExternalID:                 built.ExternalID,
		Configuration:              built.Configuration,
		State:                      built.State,
		AppliedAt:                  built.AppliedAt,
		ObservedAt:                 built.ObservedAt,
		RemovedAt:                  built.RemovedAt,
		Error:                      built.Error,
		NetworkAccessRuleID:        built.NetworkAccessRuleID,
		EnvironmentTargetNetworkID: built.EnvironmentTargetNetworkID,
	}

	if err := exec.NewInsert().Model(&entity).Returning("*").Scan(ctx); err != nil {
		return models.NetworkAccessRuleApplicationEntity{}, err
	}

	return entity, nil
}

func CreateNetworkAccessRuleApplications(ctx context.Context, exec storage.Executor, externalID sql.NullString, networkAccessRuleID uuid.UUID, environmentTargetNetworkID int32, count int, opts ...NetworkAccessRuleApplicationOption) ([]models.NetworkAccessRuleApplicationEntity, error) {
	networkaccessruleapplications := make([]models.NetworkAccessRuleApplicationEntity, 0, count)

	for i := range count {
		entity, err := CreateNetworkAccessRuleApplication(ctx, exec, externalID, networkAccessRuleID, environmentTargetNetworkID, opts...)
		if err != nil {
			return nil, fmt.Errorf("failed to create networkaccessruleapplication %d: %w", i+1, err)
		}
		networkaccessruleapplications = append(networkaccessruleapplications, entity)
	}

	return networkaccessruleapplications, nil
}

func WithNetworkAccessRuleApplicationsDriver(value string) NetworkAccessRuleApplicationOption {
	return func(f *NetworkAccessRuleApplicationFactory) {
		f.NetworkAccessRuleApplicationEntity.Driver = value
	}
}

func WithNetworkAccessRuleApplicationsExternalID(value sql.NullString) NetworkAccessRuleApplicationOption {
	return func(f *NetworkAccessRuleApplicationFactory) {
		f.NetworkAccessRuleApplicationEntity.ExternalID = value
	}
}

func WithNetworkAccessRuleApplicationsConfiguration(value json.RawMessage) NetworkAccessRuleApplicationOption {
	return func(f *NetworkAccessRuleApplicationFactory) {
		f.NetworkAccessRuleApplicationEntity.Configuration = value
	}
}

func WithNetworkAccessRuleApplicationsState(value string) NetworkAccessRuleApplicationOption {
	return func(f *NetworkAccessRuleApplicationFactory) {
		f.NetworkAccessRuleApplicationEntity.State = value
	}
}

func WithNetworkAccessRuleApplicationsAppliedAt(value sql.NullTime) NetworkAccessRuleApplicationOption {
	return func(f *NetworkAccessRuleApplicationFactory) {
		f.NetworkAccessRuleApplicationEntity.AppliedAt = value
	}
}

func WithNetworkAccessRuleApplicationsObservedAt(value sql.NullTime) NetworkAccessRuleApplicationOption {
	return func(f *NetworkAccessRuleApplicationFactory) {
		f.NetworkAccessRuleApplicationEntity.ObservedAt = value
	}
}

func WithNetworkAccessRuleApplicationsRemovedAt(value sql.NullTime) NetworkAccessRuleApplicationOption {
	return func(f *NetworkAccessRuleApplicationFactory) {
		f.NetworkAccessRuleApplicationEntity.RemovedAt = value
	}
}

func WithNetworkAccessRuleApplicationsError(value sql.NullString) NetworkAccessRuleApplicationOption {
	return func(f *NetworkAccessRuleApplicationFactory) {
		f.NetworkAccessRuleApplicationEntity.Error = value
	}
}

func WithNetworkAccessRuleApplicationsNetworkAccessRuleID(value uuid.UUID) NetworkAccessRuleApplicationOption {
	return func(f *NetworkAccessRuleApplicationFactory) {
		f.NetworkAccessRuleApplicationEntity.NetworkAccessRuleID = value
	}
}

func WithNetworkAccessRuleApplicationsEnvironmentTargetNetworkID(value int32) NetworkAccessRuleApplicationOption {
	return func(f *NetworkAccessRuleApplicationFactory) {
		f.NetworkAccessRuleApplicationEntity.EnvironmentTargetNetworkID = value
	}
}
