package factories

import (
	"context"
	"database/sql"
	"deploycrate-ce/internal/storage"
	"deploycrate-ce/models"
	"fmt"
	"time"

	"github.com/go-faker/faker/v4"
	"github.com/google/uuid"
)

// Factory declarations below are generated by Andurel.

type NetworkAccessRuleFactory struct {
	models.NetworkAccessRuleEntity
}

type NetworkAccessRuleOption func(*NetworkAccessRuleFactory)

func BuildNetworkAccessRule(privateNetworkID uuid.UUID, environmentID uuid.UUID, resourceEndpointID uuid.UUID, dependencyID uuid.UUID, opts ...NetworkAccessRuleOption) models.NetworkAccessRuleEntity {
	f := &NetworkAccessRuleFactory{
		NetworkAccessRuleEntity: models.NetworkAccessRuleEntity{
			PrivateNetworkID:   privateNetworkID,
			EnvironmentID:      environmentID,
			ResourceEndpointID: resourceEndpointID,
			DependencyID:       dependencyID,
			Protocol:           faker.Word(),
			DestinationAddress: faker.Word(),
			DestinationPort:    randomInt(1, 1000, 100),
			Action:             faker.Word(),
			ArchivedAt:         sql.NullTime{Time: time.Now(), Valid: true},
		},
	}

	for _, opt := range opts {
		opt(f)
	}

	return f.NetworkAccessRuleEntity
}

func CreateNetworkAccessRule(ctx context.Context, exec storage.Executor, privateNetworkID uuid.UUID, environmentID uuid.UUID, resourceEndpointID uuid.UUID, dependencyID uuid.UUID, opts ...NetworkAccessRuleOption) (models.NetworkAccessRuleEntity, error) {
	built := BuildNetworkAccessRule(privateNetworkID, environmentID, resourceEndpointID, dependencyID, opts...)

	entity := models.NetworkAccessRuleEntity{
		ID:                 uuid.New(),
		CreatedAt:          time.Now(),
		UpdatedAt:          time.Now(),
		PrivateNetworkID:   built.PrivateNetworkID,
		EnvironmentID:      built.EnvironmentID,
		ResourceEndpointID: built.ResourceEndpointID,
		DependencyID:       built.DependencyID,
		Protocol:           built.Protocol,
		DestinationAddress: built.DestinationAddress,
		DestinationPort:    built.DestinationPort,
		Action:             built.Action,
		ArchivedAt:         built.ArchivedAt,
	}

	if err := exec.NewInsert().Model(&entity).Returning("*").Scan(ctx); err != nil {
		return models.NetworkAccessRuleEntity{}, err
	}

	return entity, nil
}

func CreateNetworkAccessRules(ctx context.Context, exec storage.Executor, privateNetworkID uuid.UUID, environmentID uuid.UUID, resourceEndpointID uuid.UUID, dependencyID uuid.UUID, count int, opts ...NetworkAccessRuleOption) ([]models.NetworkAccessRuleEntity, error) {
	networkaccessrules := make([]models.NetworkAccessRuleEntity, 0, count)

	for i := range count {
		entity, err := CreateNetworkAccessRule(ctx, exec, privateNetworkID, environmentID, resourceEndpointID, dependencyID, opts...)
		if err != nil {
			return nil, fmt.Errorf("failed to create networkaccessrule %d: %w", i+1, err)
		}
		networkaccessrules = append(networkaccessrules, entity)
	}

	return networkaccessrules, nil
}

func WithNetworkAccessRulesPrivateNetworkID(value uuid.UUID) NetworkAccessRuleOption {
	return func(f *NetworkAccessRuleFactory) {
		f.NetworkAccessRuleEntity.PrivateNetworkID = value
	}
}

func WithNetworkAccessRulesEnvironmentID(value uuid.UUID) NetworkAccessRuleOption {
	return func(f *NetworkAccessRuleFactory) {
		f.NetworkAccessRuleEntity.EnvironmentID = value
	}
}

func WithNetworkAccessRulesResourceEndpointID(value uuid.UUID) NetworkAccessRuleOption {
	return func(f *NetworkAccessRuleFactory) {
		f.NetworkAccessRuleEntity.ResourceEndpointID = value
	}
}

func WithNetworkAccessRulesDependencyID(value uuid.UUID) NetworkAccessRuleOption {
	return func(f *NetworkAccessRuleFactory) {
		f.NetworkAccessRuleEntity.DependencyID = value
	}
}

func WithNetworkAccessRulesProtocol(value string) NetworkAccessRuleOption {
	return func(f *NetworkAccessRuleFactory) {
		f.NetworkAccessRuleEntity.Protocol = value
	}
}

func WithNetworkAccessRulesDestinationAddress(value string) NetworkAccessRuleOption {
	return func(f *NetworkAccessRuleFactory) {
		f.NetworkAccessRuleEntity.DestinationAddress = value
	}
}

func WithNetworkAccessRulesDestinationPort(value int32) NetworkAccessRuleOption {
	return func(f *NetworkAccessRuleFactory) {
		f.NetworkAccessRuleEntity.DestinationPort = value
	}
}

func WithNetworkAccessRulesAction(value string) NetworkAccessRuleOption {
	return func(f *NetworkAccessRuleFactory) {
		f.NetworkAccessRuleEntity.Action = value
	}
}

func WithNetworkAccessRulesArchivedAt(value sql.NullTime) NetworkAccessRuleOption {
	return func(f *NetworkAccessRuleFactory) {
		f.NetworkAccessRuleEntity.ArchivedAt = value
	}
}
