package factories

import (
	"context"
	"database/sql"
	"deploycrate-ce/internal/storage"
	"deploycrate-ce/models"
	"fmt"
	"time"

	"github.com/go-faker/faker/v4"
	"github.com/google/uuid"
)

// Factory declarations below are generated by Andurel.

type NetworkAccessRuleFactory struct {
	models.NetworkAccessRuleEntity
}

type NetworkAccessRuleOption func(*NetworkAccessRuleFactory)

func BuildNetworkAccessRule(
	environmentResourceID uuid.UUID,
	opts ...NetworkAccessRuleOption,
) models.NetworkAccessRuleEntity {
	f := &NetworkAccessRuleFactory{
		NetworkAccessRuleEntity: models.NetworkAccessRuleEntity{
			Protocol:              faker.Word(),
			DestinationAddress:    faker.Word(),
			DestinationPort:       randomInt(1, 1000, 100),
			Action:                faker.Word(),
			ArchivedAt:            sql.NullTime{Time: time.Now(), Valid: true},
			EnvironmentResourceID: environmentResourceID,
		},
	}

	for _, opt := range opts {
		opt(f)
	}

	return f.NetworkAccessRuleEntity
}

func CreateNetworkAccessRule(
	ctx context.Context,
	exec storage.Executor,
	environmentResourceID uuid.UUID,
	opts ...NetworkAccessRuleOption,
) (models.NetworkAccessRuleEntity, error) {
	built := BuildNetworkAccessRule(environmentResourceID, opts...)

	entity := models.NetworkAccessRuleEntity{
		ID:                    uuid.New(),
		CreatedAt:             time.Now(),
		UpdatedAt:             time.Now(),
		Protocol:              built.Protocol,
		DestinationAddress:    built.DestinationAddress,
		DestinationPort:       built.DestinationPort,
		Action:                built.Action,
		ArchivedAt:            built.ArchivedAt,
		EnvironmentResourceID: built.EnvironmentResourceID,
	}

	if err := exec.NewInsert().Model(&entity).Returning("*").Scan(ctx); err != nil {
		return models.NetworkAccessRuleEntity{}, err
	}

	return entity, nil
}

func CreateNetworkAccessRules(
	ctx context.Context,
	exec storage.Executor,
	environmentResourceID uuid.UUID,
	count int,
	opts ...NetworkAccessRuleOption,
) ([]models.NetworkAccessRuleEntity, error) {
	networkaccessrules := make([]models.NetworkAccessRuleEntity, 0, count)

	for i := range count {
		entity, err := CreateNetworkAccessRule(ctx, exec, environmentResourceID, opts...)
		if err != nil {
			return nil, fmt.Errorf("failed to create networkaccessrule %d: %w", i+1, err)
		}
		networkaccessrules = append(networkaccessrules, entity)
	}

	return networkaccessrules, nil
}

func WithNetworkAccessRulesProtocol(value string) NetworkAccessRuleOption {
	return func(f *NetworkAccessRuleFactory) {
		f.NetworkAccessRuleEntity.Protocol = value
	}
}

func WithNetworkAccessRulesDestinationAddress(value string) NetworkAccessRuleOption {
	return func(f *NetworkAccessRuleFactory) {
		f.NetworkAccessRuleEntity.DestinationAddress = value
	}
}

func WithNetworkAccessRulesDestinationPort(value int32) NetworkAccessRuleOption {
	return func(f *NetworkAccessRuleFactory) {
		f.NetworkAccessRuleEntity.DestinationPort = value
	}
}

func WithNetworkAccessRulesAction(value string) NetworkAccessRuleOption {
	return func(f *NetworkAccessRuleFactory) {
		f.NetworkAccessRuleEntity.Action = value
	}
}

func WithNetworkAccessRulesArchivedAt(value sql.NullTime) NetworkAccessRuleOption {
	return func(f *NetworkAccessRuleFactory) {
		f.NetworkAccessRuleEntity.ArchivedAt = value
	}
}

func WithNetworkAccessRulesEnvironmentResourceID(value uuid.UUID) NetworkAccessRuleOption {
	return func(f *NetworkAccessRuleFactory) {
		f.NetworkAccessRuleEntity.EnvironmentResourceID = value
	}
}
