package factories

import (
	"context"
	"database/sql"
	"deploycrate-ce/internal/storage"
	"deploycrate-ce/models"
	"encoding/json"
	"fmt"
	"time"

	"github.com/go-faker/faker/v4"
	"github.com/google/uuid"
)

// Factory declarations below are generated by Andurel.

type OutboxEventFactory struct {
	models.OutboxEventEntity
}

type OutboxEventOption func(*OutboxEventFactory)

func BuildOutboxEvent(aggregateID uuid.UUID, correlationID uuid.UUID, causationID uuid.UUID, opts ...OutboxEventOption) models.OutboxEventEntity {
	f := &OutboxEventFactory{
		OutboxEventEntity: models.OutboxEventEntity{
			AggregateType:   faker.Word(),
			AggregateID:     aggregateID,
			EventType:       faker.Word(),
			SchemaVersion:   randomInt(1, 1000, 100),
			CorrelationID:   correlationID,
			CausationID:     causationID,
			Payload:         json.RawMessage{},
			OccurredAt:      time.Time{},
			PublishedAt:     sql.NullTime{Time: time.Now(), Valid: true},
			PublishAttempts: randomInt(1, 1000, 100),
			LastError:       sql.NullString{String: faker.Word(), Valid: true},
		},
	}

	for _, opt := range opts {
		opt(f)
	}

	return f.OutboxEventEntity
}

func CreateOutboxEvent(ctx context.Context, exec storage.Executor, aggregateID uuid.UUID, correlationID uuid.UUID, causationID uuid.UUID, opts ...OutboxEventOption) (models.OutboxEventEntity, error) {
	built := BuildOutboxEvent(aggregateID, correlationID, causationID, opts...)

	entity := models.OutboxEventEntity{
		ID:              uuid.New(),
		CreatedAt:       time.Now(),
		UpdatedAt:       time.Now(),
		AggregateType:   built.AggregateType,
		AggregateID:     built.AggregateID,
		EventType:       built.EventType,
		SchemaVersion:   built.SchemaVersion,
		CorrelationID:   built.CorrelationID,
		CausationID:     built.CausationID,
		Payload:         built.Payload,
		OccurredAt:      built.OccurredAt,
		PublishedAt:     built.PublishedAt,
		PublishAttempts: built.PublishAttempts,
		LastError:       built.LastError,
	}

	if err := exec.NewInsert().Model(&entity).Returning("*").Scan(ctx); err != nil {
		return models.OutboxEventEntity{}, err
	}

	return entity, nil
}

func CreateOutboxEvents(ctx context.Context, exec storage.Executor, aggregateID uuid.UUID, correlationID uuid.UUID, causationID uuid.UUID, count int, opts ...OutboxEventOption) ([]models.OutboxEventEntity, error) {
	outboxevents := make([]models.OutboxEventEntity, 0, count)

	for i := range count {
		entity, err := CreateOutboxEvent(ctx, exec, aggregateID, correlationID, causationID, opts...)
		if err != nil {
			return nil, fmt.Errorf("failed to create outboxevent %d: %w", i+1, err)
		}
		outboxevents = append(outboxevents, entity)
	}

	return outboxevents, nil
}

func WithOutboxEventsAggregateType(value string) OutboxEventOption {
	return func(f *OutboxEventFactory) {
		f.OutboxEventEntity.AggregateType = value
	}
}

func WithOutboxEventsAggregateID(value uuid.UUID) OutboxEventOption {
	return func(f *OutboxEventFactory) {
		f.OutboxEventEntity.AggregateID = value
	}
}

func WithOutboxEventsEventType(value string) OutboxEventOption {
	return func(f *OutboxEventFactory) {
		f.OutboxEventEntity.EventType = value
	}
}

func WithOutboxEventsSchemaVersion(value int32) OutboxEventOption {
	return func(f *OutboxEventFactory) {
		f.OutboxEventEntity.SchemaVersion = value
	}
}

func WithOutboxEventsCorrelationID(value uuid.UUID) OutboxEventOption {
	return func(f *OutboxEventFactory) {
		f.OutboxEventEntity.CorrelationID = value
	}
}

func WithOutboxEventsCausationID(value uuid.UUID) OutboxEventOption {
	return func(f *OutboxEventFactory) {
		f.OutboxEventEntity.CausationID = value
	}
}

func WithOutboxEventsPayload(value json.RawMessage) OutboxEventOption {
	return func(f *OutboxEventFactory) {
		f.OutboxEventEntity.Payload = value
	}
}

func WithOutboxEventsOccurredAt(value time.Time) OutboxEventOption {
	return func(f *OutboxEventFactory) {
		f.OutboxEventEntity.OccurredAt = value
	}
}

func WithOutboxEventsPublishedAt(value sql.NullTime) OutboxEventOption {
	return func(f *OutboxEventFactory) {
		f.OutboxEventEntity.PublishedAt = value
	}
}

func WithOutboxEventsPublishAttempts(value int32) OutboxEventOption {
	return func(f *OutboxEventFactory) {
		f.OutboxEventEntity.PublishAttempts = value
	}
}

func WithOutboxEventsLastError(value sql.NullString) OutboxEventOption {
	return func(f *OutboxEventFactory) {
		f.OutboxEventEntity.LastError = value
	}
}
