package factories

import (
	"context"
	"database/sql"
	"deploycrate-ce/internal/storage"
	"deploycrate-ce/models"
	"fmt"
	"time"

	"github.com/go-faker/faker/v4"
	"github.com/google/uuid"
)

// Factory declarations below are generated by Andurel.

type PrivateNetworkFactory struct {
	models.PrivateNetworkEntity
}

type PrivateNetworkOption func(*PrivateNetworkFactory)

func BuildPrivateNetwork(
	ownerEnvironmentID *uuid.UUID,
	opts ...PrivateNetworkOption,
) models.PrivateNetworkEntity {
	f := &PrivateNetworkFactory{
		PrivateNetworkEntity: models.PrivateNetworkEntity{
			Name:               faker.Word(),
			ArchivedAt:         sql.NullTime{Time: time.Now(), Valid: true},
			OwnerEnvironmentID: ownerEnvironmentID,
		},
	}

	for _, opt := range opts {
		opt(f)
	}

	return f.PrivateNetworkEntity
}

func CreatePrivateNetwork(
	ctx context.Context,
	exec storage.Executor,
	ownerEnvironmentID *uuid.UUID,
	opts ...PrivateNetworkOption,
) (models.PrivateNetworkEntity, error) {
	built := BuildPrivateNetwork(ownerEnvironmentID, opts...)

	entity := models.PrivateNetworkEntity{
		ID:                 uuid.New(),
		CreatedAt:          time.Now(),
		UpdatedAt:          time.Now(),
		Name:               built.Name,
		ArchivedAt:         built.ArchivedAt,
		OwnerEnvironmentID: built.OwnerEnvironmentID,
	}

	if err := exec.NewInsert().Model(&entity).Returning("*").Scan(ctx); err != nil {
		return models.PrivateNetworkEntity{}, err
	}

	return entity, nil
}

func CreatePrivateNetworks(
	ctx context.Context,
	exec storage.Executor,
	ownerEnvironmentID *uuid.UUID,
	count int,
	opts ...PrivateNetworkOption,
) ([]models.PrivateNetworkEntity, error) {
	privatenetworks := make([]models.PrivateNetworkEntity, 0, count)

	for i := range count {
		entity, err := CreatePrivateNetwork(ctx, exec, ownerEnvironmentID, opts...)
		if err != nil {
			return nil, fmt.Errorf("failed to create privatenetwork %d: %w", i+1, err)
		}
		privatenetworks = append(privatenetworks, entity)
	}

	return privatenetworks, nil
}

func WithPrivateNetworksName(value string) PrivateNetworkOption {
	return func(f *PrivateNetworkFactory) {
		f.PrivateNetworkEntity.Name = value
	}
}

func WithPrivateNetworksArchivedAt(value sql.NullTime) PrivateNetworkOption {
	return func(f *PrivateNetworkFactory) {
		f.PrivateNetworkEntity.ArchivedAt = value
	}
}

func WithPrivateNetworksOwnerEnvironmentID(value *uuid.UUID) PrivateNetworkOption {
	return func(f *PrivateNetworkFactory) {
		f.PrivateNetworkEntity.OwnerEnvironmentID = value
	}
}
