package factories

import (
	"context"
	"database/sql"
	"deploycrate-ce/internal/storage"
	"deploycrate-ce/models"
	"fmt"
	"time"

	"github.com/go-faker/faker/v4"
	"github.com/google/uuid"
)

// Factory declarations below are generated by Andurel.

type ReleaseFactory struct {
	models.ReleaseEntity
}

type ReleaseOption func(*ReleaseFactory)

func BuildRelease(
	environmentID uuid.UUID,
	environmentSourceID *uuid.UUID,
	buildID *uuid.UUID,
	createdByChangeID uuid.UUID,
	opts ...ReleaseOption,
) models.ReleaseEntity {
	f := &ReleaseFactory{
		ReleaseEntity: models.ReleaseEntity{
			Version:             sql.NullString{String: faker.Word(), Valid: true},
			SourceRevision:      sql.NullString{String: faker.Word(), Valid: true},
			ArtifactReference:   faker.Word(),
			ArtifactDigest:      []byte{},
			EnvironmentID:       environmentID,
			EnvironmentSourceID: environmentSourceID,
			BuildID:             buildID,
			CreatedByChangeID:   createdByChangeID,
		},
	}

	for _, opt := range opts {
		opt(f)
	}

	return f.ReleaseEntity
}

func CreateRelease(
	ctx context.Context,
	exec storage.Executor,
	environmentID uuid.UUID,
	environmentSourceID *uuid.UUID,
	buildID *uuid.UUID,
	createdByChangeID uuid.UUID,
	opts ...ReleaseOption,
) (models.ReleaseEntity, error) {
	built := BuildRelease(environmentID, environmentSourceID, buildID, createdByChangeID, opts...)

	entity := models.ReleaseEntity{
		ID:                  uuid.New(),
		CreatedAt:           time.Now(),
		UpdatedAt:           time.Now(),
		Version:             built.Version,
		SourceRevision:      built.SourceRevision,
		ArtifactReference:   built.ArtifactReference,
		ArtifactDigest:      built.ArtifactDigest,
		EnvironmentID:       built.EnvironmentID,
		EnvironmentSourceID: built.EnvironmentSourceID,
		BuildID:             built.BuildID,
		CreatedByChangeID:   built.CreatedByChangeID,
	}

	if err := exec.NewInsert().Model(&entity).Returning("*").Scan(ctx); err != nil {
		return models.ReleaseEntity{}, err
	}

	return entity, nil
}

func CreateReleases(
	ctx context.Context,
	exec storage.Executor,
	environmentID uuid.UUID,
	environmentSourceID *uuid.UUID,
	buildID *uuid.UUID,
	createdByChangeID uuid.UUID,
	count int,
	opts ...ReleaseOption,
) ([]models.ReleaseEntity, error) {
	releases := make([]models.ReleaseEntity, 0, count)

	for i := range count {
		entity, err := CreateRelease(
			ctx,
			exec,
			environmentID,
			environmentSourceID,
			buildID,
			createdByChangeID,
			opts...)
		if err != nil {
			return nil, fmt.Errorf("failed to create release %d: %w", i+1, err)
		}
		releases = append(releases, entity)
	}

	return releases, nil
}

func WithReleasesVersion(value sql.NullString) ReleaseOption {
	return func(f *ReleaseFactory) {
		f.ReleaseEntity.Version = value
	}
}

func WithReleasesSourceRevision(value sql.NullString) ReleaseOption {
	return func(f *ReleaseFactory) {
		f.ReleaseEntity.SourceRevision = value
	}
}

func WithReleasesArtifactReference(value string) ReleaseOption {
	return func(f *ReleaseFactory) {
		f.ReleaseEntity.ArtifactReference = value
	}
}

func WithReleasesArtifactDigest(value []byte) ReleaseOption {
	return func(f *ReleaseFactory) {
		f.ReleaseEntity.ArtifactDigest = value
	}
}

func WithReleasesEnvironmentID(value uuid.UUID) ReleaseOption {
	return func(f *ReleaseFactory) {
		f.ReleaseEntity.EnvironmentID = value
	}
}

func WithReleasesEnvironmentSourceID(value *uuid.UUID) ReleaseOption {
	return func(f *ReleaseFactory) {
		f.ReleaseEntity.EnvironmentSourceID = value
	}
}

func WithReleasesBuildID(value *uuid.UUID) ReleaseOption {
	return func(f *ReleaseFactory) {
		f.ReleaseEntity.BuildID = value
	}
}

func WithReleasesCreatedByChangeID(value uuid.UUID) ReleaseOption {
	return func(f *ReleaseFactory) {
		f.ReleaseEntity.CreatedByChangeID = value
	}
}
