package factories

import (
	"context"
	"database/sql"
	"deploycrate-ce/internal/storage"
	"deploycrate-ce/models"
	"encoding/json"
	"fmt"
	"time"

	"github.com/go-faker/faker/v4"
	"github.com/google/uuid"
)

// Factory declarations below are generated by Andurel.

type ResourceInstallationStatusFactory struct {
	models.ResourceInstallationStatusEntity
}

type ResourceInstallationStatusOption func(*ResourceInstallationStatusFactory)

func BuildResourceInstallationStatus(externalID sql.NullString, resourceInstallationID uuid.UUID, opts ...ResourceInstallationStatusOption) models.ResourceInstallationStatusEntity {
	f := &ResourceInstallationStatusFactory{
		ResourceInstallationStatusEntity: models.ResourceInstallationStatusEntity{
			ExternalID:             externalID,
			State:                  faker.Word(),
			InstalledVersion:       sql.NullString{String: faker.Word(), Valid: true},
			ServiceState:           faker.Word(),
			Health:                 faker.Word(),
			Source:                 faker.Word(),
			HealthReason:           sql.NullString{String: faker.Word(), Valid: true},
			Details:                json.RawMessage{},
			ObservedAt:             time.Time{},
			ExpiresAt:              time.Time{},
			ResourceInstallationID: resourceInstallationID,
		},
	}

	for _, opt := range opts {
		opt(f)
	}

	return f.ResourceInstallationStatusEntity
}

func CreateResourceInstallationStatus(ctx context.Context, exec storage.Executor, externalID sql.NullString, resourceInstallationID uuid.UUID, opts ...ResourceInstallationStatusOption) (models.ResourceInstallationStatusEntity, error) {
	built := BuildResourceInstallationStatus(externalID, resourceInstallationID, opts...)

	entity := models.ResourceInstallationStatusEntity{
		CreatedAt:              time.Now(),
		UpdatedAt:              time.Now(),
		ExternalID:             built.ExternalID,
		State:                  built.State,
		InstalledVersion:       built.InstalledVersion,
		ServiceState:           built.ServiceState,
		Health:                 built.Health,
		Source:                 built.Source,
		HealthReason:           built.HealthReason,
		Details:                built.Details,
		ObservedAt:             built.ObservedAt,
		ExpiresAt:              built.ExpiresAt,
		ResourceInstallationID: built.ResourceInstallationID,
	}

	if err := exec.NewInsert().Model(&entity).Returning("*").Scan(ctx); err != nil {
		return models.ResourceInstallationStatusEntity{}, err
	}

	return entity, nil
}

func CreateResourceInstallationStatuss(ctx context.Context, exec storage.Executor, externalID sql.NullString, resourceInstallationID uuid.UUID, count int, opts ...ResourceInstallationStatusOption) ([]models.ResourceInstallationStatusEntity, error) {
	resourceinstallationstatuss := make([]models.ResourceInstallationStatusEntity, 0, count)

	for i := range count {
		entity, err := CreateResourceInstallationStatus(ctx, exec, externalID, resourceInstallationID, opts...)
		if err != nil {
			return nil, fmt.Errorf("failed to create resourceinstallationstatus %d: %w", i+1, err)
		}
		resourceinstallationstatuss = append(resourceinstallationstatuss, entity)
	}

	return resourceinstallationstatuss, nil
}

func WithResourceInstallationStatusesExternalID(value sql.NullString) ResourceInstallationStatusOption {
	return func(f *ResourceInstallationStatusFactory) {
		f.ResourceInstallationStatusEntity.ExternalID = value
	}
}

func WithResourceInstallationStatusesState(value string) ResourceInstallationStatusOption {
	return func(f *ResourceInstallationStatusFactory) {
		f.ResourceInstallationStatusEntity.State = value
	}
}

func WithResourceInstallationStatusesInstalledVersion(value sql.NullString) ResourceInstallationStatusOption {
	return func(f *ResourceInstallationStatusFactory) {
		f.ResourceInstallationStatusEntity.InstalledVersion = value
	}
}

func WithResourceInstallationStatusesServiceState(value string) ResourceInstallationStatusOption {
	return func(f *ResourceInstallationStatusFactory) {
		f.ResourceInstallationStatusEntity.ServiceState = value
	}
}

func WithResourceInstallationStatusesHealth(value string) ResourceInstallationStatusOption {
	return func(f *ResourceInstallationStatusFactory) {
		f.ResourceInstallationStatusEntity.Health = value
	}
}

func WithResourceInstallationStatusesSource(value string) ResourceInstallationStatusOption {
	return func(f *ResourceInstallationStatusFactory) {
		f.ResourceInstallationStatusEntity.Source = value
	}
}

func WithResourceInstallationStatusesHealthReason(value sql.NullString) ResourceInstallationStatusOption {
	return func(f *ResourceInstallationStatusFactory) {
		f.ResourceInstallationStatusEntity.HealthReason = value
	}
}

func WithResourceInstallationStatusesDetails(value json.RawMessage) ResourceInstallationStatusOption {
	return func(f *ResourceInstallationStatusFactory) {
		f.ResourceInstallationStatusEntity.Details = value
	}
}

func WithResourceInstallationStatusesObservedAt(value time.Time) ResourceInstallationStatusOption {
	return func(f *ResourceInstallationStatusFactory) {
		f.ResourceInstallationStatusEntity.ObservedAt = value
	}
}

func WithResourceInstallationStatusesExpiresAt(value time.Time) ResourceInstallationStatusOption {
	return func(f *ResourceInstallationStatusFactory) {
		f.ResourceInstallationStatusEntity.ExpiresAt = value
	}
}

func WithResourceInstallationStatusesResourceInstallationID(value uuid.UUID) ResourceInstallationStatusOption {
	return func(f *ResourceInstallationStatusFactory) {
		f.ResourceInstallationStatusEntity.ResourceInstallationID = value
	}
}
