package factories

import (
	"context"
	"database/sql"
	"deploycrate-ce/internal/storage"
	"deploycrate-ce/models"
	"fmt"
	"time"

	"github.com/go-faker/faker/v4"
	"github.com/google/uuid"
)

// Factory declarations below are generated by Andurel.

type ResourceBindingCredentialFactory struct {
	models.ResourceBindingCredentialEntity
}

type ResourceBindingCredentialOption func(*ResourceBindingCredentialFactory)

func BuildResourceBindingCredential(resourceBindingID uuid.UUID, resourceCredentialID uuid.UUID, opts ...ResourceBindingCredentialOption) models.ResourceBindingCredentialEntity {
	f := &ResourceBindingCredentialFactory{
		ResourceBindingCredentialEntity: models.ResourceBindingCredentialEntity{
			ResourceBindingID:    resourceBindingID,
			ResourceCredentialID: resourceCredentialID,
			Generation:           randomInt(1, 1000, 100),
			State:                faker.Word(),
			ActivatedAt:          sql.NullTime{Time: time.Now(), Valid: true},
			RetiredAt:            sql.NullTime{Time: time.Now(), Valid: true},
		},
	}

	for _, opt := range opts {
		opt(f)
	}

	return f.ResourceBindingCredentialEntity
}

func CreateResourceBindingCredential(ctx context.Context, exec storage.Executor, resourceBindingID uuid.UUID, resourceCredentialID uuid.UUID, opts ...ResourceBindingCredentialOption) (models.ResourceBindingCredentialEntity, error) {
	built := BuildResourceBindingCredential(resourceBindingID, resourceCredentialID, opts...)

	entity := models.ResourceBindingCredentialEntity{
		ID:                   uuid.New(),
		CreatedAt:            time.Now(),
		UpdatedAt:            time.Now(),
		ResourceBindingID:    built.ResourceBindingID,
		ResourceCredentialID: built.ResourceCredentialID,
		Generation:           built.Generation,
		State:                built.State,
		ActivatedAt:          built.ActivatedAt,
		RetiredAt:            built.RetiredAt,
	}

	if err := exec.NewInsert().Model(&entity).Returning("*").Scan(ctx); err != nil {
		return models.ResourceBindingCredentialEntity{}, err
	}

	return entity, nil
}

func CreateResourceBindingCredentials(ctx context.Context, exec storage.Executor, resourceBindingID uuid.UUID, resourceCredentialID uuid.UUID, count int, opts ...ResourceBindingCredentialOption) ([]models.ResourceBindingCredentialEntity, error) {
	resourcebindingcredentials := make([]models.ResourceBindingCredentialEntity, 0, count)

	for i := range count {
		entity, err := CreateResourceBindingCredential(ctx, exec, resourceBindingID, resourceCredentialID, opts...)
		if err != nil {
			return nil, fmt.Errorf("failed to create resourcebindingcredential %d: %w", i+1, err)
		}
		resourcebindingcredentials = append(resourcebindingcredentials, entity)
	}

	return resourcebindingcredentials, nil
}

func WithResourceBindingCredentialsResourceBindingID(value uuid.UUID) ResourceBindingCredentialOption {
	return func(f *ResourceBindingCredentialFactory) {
		f.ResourceBindingCredentialEntity.ResourceBindingID = value
	}
}

func WithResourceBindingCredentialsResourceCredentialID(value uuid.UUID) ResourceBindingCredentialOption {
	return func(f *ResourceBindingCredentialFactory) {
		f.ResourceBindingCredentialEntity.ResourceCredentialID = value
	}
}

func WithResourceBindingCredentialsGeneration(value int32) ResourceBindingCredentialOption {
	return func(f *ResourceBindingCredentialFactory) {
		f.ResourceBindingCredentialEntity.Generation = value
	}
}

func WithResourceBindingCredentialsState(value string) ResourceBindingCredentialOption {
	return func(f *ResourceBindingCredentialFactory) {
		f.ResourceBindingCredentialEntity.State = value
	}
}

func WithResourceBindingCredentialsActivatedAt(value sql.NullTime) ResourceBindingCredentialOption {
	return func(f *ResourceBindingCredentialFactory) {
		f.ResourceBindingCredentialEntity.ActivatedAt = value
	}
}

func WithResourceBindingCredentialsRetiredAt(value sql.NullTime) ResourceBindingCredentialOption {
	return func(f *ResourceBindingCredentialFactory) {
		f.ResourceBindingCredentialEntity.RetiredAt = value
	}
}
