package factories

import (
	"context"
	"database/sql"
	"deploycrate-ce/internal/storage"
	"deploycrate-ce/models"
	"encoding/json"
	"fmt"
	"time"

	"github.com/go-faker/faker/v4"
	"github.com/google/uuid"
)

// Factory declarations below are generated by Andurel.

type ResourceVolumeFactory struct {
	models.ResourceVolumeEntity
}

type ResourceVolumeOption func(*ResourceVolumeFactory)

func BuildResourceVolume(
	resourceID uuid.UUID,
	serverID uuid.UUID,
	opts ...ResourceVolumeOption,
) models.ResourceVolumeEntity {
	f := &ResourceVolumeFactory{
		ResourceVolumeEntity: models.ResourceVolumeEntity{
			Name:          faker.Word(),
			Driver:        faker.Word(),
			Configuration: json.RawMessage{},
			ArchivedAt:    sql.NullTime{Time: time.Now(), Valid: true},
			ResourceID:    resourceID,
			ServerID:      serverID,
		},
	}

	for _, opt := range opts {
		opt(f)
	}

	return f.ResourceVolumeEntity
}

func CreateResourceVolume(
	ctx context.Context,
	exec storage.Executor,
	resourceID uuid.UUID,
	serverID uuid.UUID,
	opts ...ResourceVolumeOption,
) (models.ResourceVolumeEntity, error) {
	built := BuildResourceVolume(resourceID, serverID, opts...)

	entity := models.ResourceVolumeEntity{
		ID:            uuid.New(),
		CreatedAt:     time.Now(),
		UpdatedAt:     time.Now(),
		Name:          built.Name,
		Driver:        built.Driver,
		Configuration: built.Configuration,
		ArchivedAt:    built.ArchivedAt,
		ResourceID:    built.ResourceID,
		ServerID:      built.ServerID,
	}

	if err := exec.NewInsert().Model(&entity).Returning("*").Scan(ctx); err != nil {
		return models.ResourceVolumeEntity{}, err
	}

	return entity, nil
}

func CreateResourceVolumes(
	ctx context.Context,
	exec storage.Executor,
	resourceID uuid.UUID,
	serverID uuid.UUID,
	count int,
	opts ...ResourceVolumeOption,
) ([]models.ResourceVolumeEntity, error) {
	resourcevolumes := make([]models.ResourceVolumeEntity, 0, count)

	for i := range count {
		entity, err := CreateResourceVolume(ctx, exec, resourceID, serverID, opts...)
		if err != nil {
			return nil, fmt.Errorf("failed to create resourcevolume %d: %w", i+1, err)
		}
		resourcevolumes = append(resourcevolumes, entity)
	}

	return resourcevolumes, nil
}

func WithResourceVolumesName(value string) ResourceVolumeOption {
	return func(f *ResourceVolumeFactory) {
		f.ResourceVolumeEntity.Name = value
	}
}

func WithResourceVolumesDriver(value string) ResourceVolumeOption {
	return func(f *ResourceVolumeFactory) {
		f.ResourceVolumeEntity.Driver = value
	}
}

func WithResourceVolumesConfiguration(value json.RawMessage) ResourceVolumeOption {
	return func(f *ResourceVolumeFactory) {
		f.ResourceVolumeEntity.Configuration = value
	}
}

func WithResourceVolumesArchivedAt(value sql.NullTime) ResourceVolumeOption {
	return func(f *ResourceVolumeFactory) {
		f.ResourceVolumeEntity.ArchivedAt = value
	}
}

func WithResourceVolumesResourceID(value uuid.UUID) ResourceVolumeOption {
	return func(f *ResourceVolumeFactory) {
		f.ResourceVolumeEntity.ResourceID = value
	}
}

func WithResourceVolumesServerID(value uuid.UUID) ResourceVolumeOption {
	return func(f *ResourceVolumeFactory) {
		f.ResourceVolumeEntity.ServerID = value
	}
}
