package factories

import (
	"context"
	"database/sql"
	"deploycrate-ce/internal/storage"
	"deploycrate-ce/models"
	"fmt"
	"time"

	"github.com/go-faker/faker/v4"
	"github.com/google/uuid"
)

// Factory declarations below are generated by Andurel.

type ResourceRestoreFactory struct {
	models.ResourceRestoreEntity
}

type ResourceRestoreOption func(*ResourceRestoreFactory)

func BuildResourceRestore(changeID uuid.UUID, changeTaskID uuid.UUID, resourceBackupID uuid.UUID, resourceID uuid.UUID, sourceBindingID *uuid.UUID, targetBindingID *uuid.UUID, targetInstallationID *uuid.UUID, opts ...ResourceRestoreOption) models.ResourceRestoreEntity {
	f := &ResourceRestoreFactory{
		ResourceRestoreEntity: models.ResourceRestoreEntity{
			ChangeID:             changeID,
			ChangeTaskID:         changeTaskID,
			ResourceBackupID:     resourceBackupID,
			ResourceID:           resourceID,
			SourceBindingID:      sourceBindingID,
			TargetBindingID:      targetBindingID,
			TargetInstallationID: targetInstallationID,
			Status:               faker.Word(),
			RequestedAt:          time.Time{},
			StartedAt:            sql.NullTime{Time: time.Now(), Valid: true},
			FinishedAt:           sql.NullTime{Time: time.Now(), Valid: true},
			VerifiedAt:           sql.NullTime{Time: time.Now(), Valid: true},
			Error:                sql.NullString{String: faker.Word(), Valid: true},
		},
	}

	for _, opt := range opts {
		opt(f)
	}

	return f.ResourceRestoreEntity
}

func CreateResourceRestore(ctx context.Context, exec storage.Executor, changeID uuid.UUID, changeTaskID uuid.UUID, resourceBackupID uuid.UUID, resourceID uuid.UUID, sourceBindingID *uuid.UUID, targetBindingID *uuid.UUID, targetInstallationID *uuid.UUID, opts ...ResourceRestoreOption) (models.ResourceRestoreEntity, error) {
	built := BuildResourceRestore(changeID, changeTaskID, resourceBackupID, resourceID, sourceBindingID, targetBindingID, targetInstallationID, opts...)

	entity := models.ResourceRestoreEntity{
		ID:                   uuid.New(),
		CreatedAt:            time.Now(),
		UpdatedAt:            time.Now(),
		ChangeID:             built.ChangeID,
		ChangeTaskID:         built.ChangeTaskID,
		ResourceBackupID:     built.ResourceBackupID,
		ResourceID:           built.ResourceID,
		SourceBindingID:      built.SourceBindingID,
		TargetBindingID:      built.TargetBindingID,
		TargetInstallationID: built.TargetInstallationID,
		Status:               built.Status,
		RequestedAt:          built.RequestedAt,
		StartedAt:            built.StartedAt,
		FinishedAt:           built.FinishedAt,
		VerifiedAt:           built.VerifiedAt,
		Error:                built.Error,
	}

	if err := exec.NewInsert().Model(&entity).Returning("*").Scan(ctx); err != nil {
		return models.ResourceRestoreEntity{}, err
	}

	return entity, nil
}

func CreateResourceRestores(ctx context.Context, exec storage.Executor, changeID uuid.UUID, changeTaskID uuid.UUID, resourceBackupID uuid.UUID, resourceID uuid.UUID, sourceBindingID *uuid.UUID, targetBindingID *uuid.UUID, targetInstallationID *uuid.UUID, count int, opts ...ResourceRestoreOption) ([]models.ResourceRestoreEntity, error) {
	resourcerestores := make([]models.ResourceRestoreEntity, 0, count)

	for i := range count {
		entity, err := CreateResourceRestore(ctx, exec, changeID, changeTaskID, resourceBackupID, resourceID, sourceBindingID, targetBindingID, targetInstallationID, opts...)
		if err != nil {
			return nil, fmt.Errorf("failed to create resourcerestore %d: %w", i+1, err)
		}
		resourcerestores = append(resourcerestores, entity)
	}

	return resourcerestores, nil
}

func WithResourceRestoresChangeID(value uuid.UUID) ResourceRestoreOption {
	return func(f *ResourceRestoreFactory) {
		f.ResourceRestoreEntity.ChangeID = value
	}
}

func WithResourceRestoresChangeTaskID(value uuid.UUID) ResourceRestoreOption {
	return func(f *ResourceRestoreFactory) {
		f.ResourceRestoreEntity.ChangeTaskID = value
	}
}

func WithResourceRestoresResourceBackupID(value uuid.UUID) ResourceRestoreOption {
	return func(f *ResourceRestoreFactory) {
		f.ResourceRestoreEntity.ResourceBackupID = value
	}
}

func WithResourceRestoresResourceID(value uuid.UUID) ResourceRestoreOption {
	return func(f *ResourceRestoreFactory) {
		f.ResourceRestoreEntity.ResourceID = value
	}
}

func WithResourceRestoresSourceBindingID(value *uuid.UUID) ResourceRestoreOption {
	return func(f *ResourceRestoreFactory) {
		f.ResourceRestoreEntity.SourceBindingID = value
	}
}

func WithResourceRestoresTargetBindingID(value *uuid.UUID) ResourceRestoreOption {
	return func(f *ResourceRestoreFactory) {
		f.ResourceRestoreEntity.TargetBindingID = value
	}
}

func WithResourceRestoresTargetInstallationID(value *uuid.UUID) ResourceRestoreOption {
	return func(f *ResourceRestoreFactory) {
		f.ResourceRestoreEntity.TargetInstallationID = value
	}
}

func WithResourceRestoresStatus(value string) ResourceRestoreOption {
	return func(f *ResourceRestoreFactory) {
		f.ResourceRestoreEntity.Status = value
	}
}

func WithResourceRestoresRequestedAt(value time.Time) ResourceRestoreOption {
	return func(f *ResourceRestoreFactory) {
		f.ResourceRestoreEntity.RequestedAt = value
	}
}

func WithResourceRestoresStartedAt(value sql.NullTime) ResourceRestoreOption {
	return func(f *ResourceRestoreFactory) {
		f.ResourceRestoreEntity.StartedAt = value
	}
}

func WithResourceRestoresFinishedAt(value sql.NullTime) ResourceRestoreOption {
	return func(f *ResourceRestoreFactory) {
		f.ResourceRestoreEntity.FinishedAt = value
	}
}

func WithResourceRestoresVerifiedAt(value sql.NullTime) ResourceRestoreOption {
	return func(f *ResourceRestoreFactory) {
		f.ResourceRestoreEntity.VerifiedAt = value
	}
}

func WithResourceRestoresError(value sql.NullString) ResourceRestoreOption {
	return func(f *ResourceRestoreFactory) {
		f.ResourceRestoreEntity.Error = value
	}
}
