package factories

import (
	"context"
	"database/sql"
	"deploycrate-ce/internal/storage"
	"deploycrate-ce/models"
	"fmt"
	"time"

	"github.com/go-faker/faker/v4"
	"github.com/google/uuid"
)

// Factory declarations below are generated by Andurel.

type ResourceFactory struct {
	models.ResourceEntity
}

type ResourceOption func(*ResourceFactory)

func BuildResource(ownerEnvironmentID uuid.UUID, opts ...ResourceOption) models.ResourceEntity {
	f := &ResourceFactory{
		ResourceEntity: models.ResourceEntity{
			Name:               faker.Word(),
			Category:           faker.Word(),
			Kind:               faker.Word(),
			SharingScope:       faker.Word(),
			ArchivedAt:         sql.NullTime{Time: time.Now(), Valid: true},
			OwnerEnvironmentID: ownerEnvironmentID,
		},
	}

	for _, opt := range opts {
		opt(f)
	}

	return f.ResourceEntity
}

func CreateResource(ctx context.Context, exec storage.Executor, ownerEnvironmentID uuid.UUID, opts ...ResourceOption) (models.ResourceEntity, error) {
	built := BuildResource(ownerEnvironmentID, opts...)

	entity := models.ResourceEntity{
		ID:                 uuid.New(),
		CreatedAt:          time.Now(),
		UpdatedAt:          time.Now(),
		Name:               built.Name,
		Category:           built.Category,
		Kind:               built.Kind,
		SharingScope:       built.SharingScope,
		ArchivedAt:         built.ArchivedAt,
		OwnerEnvironmentID: built.OwnerEnvironmentID,
	}

	if err := exec.NewInsert().Model(&entity).Returning("*").Scan(ctx); err != nil {
		return models.ResourceEntity{}, err
	}

	return entity, nil
}

func CreateResources(ctx context.Context, exec storage.Executor, ownerEnvironmentID uuid.UUID, count int, opts ...ResourceOption) ([]models.ResourceEntity, error) {
	resources := make([]models.ResourceEntity, 0, count)

	for i := range count {
		entity, err := CreateResource(ctx, exec, ownerEnvironmentID, opts...)
		if err != nil {
			return nil, fmt.Errorf("failed to create resource %d: %w", i+1, err)
		}
		resources = append(resources, entity)
	}

	return resources, nil
}

func WithResourcesName(value string) ResourceOption {
	return func(f *ResourceFactory) {
		f.ResourceEntity.Name = value
	}
}

func WithResourcesCategory(value string) ResourceOption {
	return func(f *ResourceFactory) {
		f.ResourceEntity.Category = value
	}
}

func WithResourcesKind(value string) ResourceOption {
	return func(f *ResourceFactory) {
		f.ResourceEntity.Kind = value
	}
}

func WithResourcesSharingScope(value string) ResourceOption {
	return func(f *ResourceFactory) {
		f.ResourceEntity.SharingScope = value
	}
}

func WithResourcesArchivedAt(value sql.NullTime) ResourceOption {
	return func(f *ResourceFactory) {
		f.ResourceEntity.ArchivedAt = value
	}
}

func WithResourcesOwnerEnvironmentID(value uuid.UUID) ResourceOption {
	return func(f *ResourceFactory) {
		f.ResourceEntity.OwnerEnvironmentID = value
	}
}
