package factories

import (
	"context"
	"database/sql"
	"deploycrate-ce/internal/storage"
	"deploycrate-ce/models"
	"encoding/json"
	"fmt"
	"time"

	"github.com/go-faker/faker/v4"
	"github.com/google/uuid"
)

// Factory declarations below are generated by Andurel.

type ResourceHealthCheckFactory struct {
	models.ResourceHealthCheckEntity
}

type ResourceHealthCheckOption func(*ResourceHealthCheckFactory)

func BuildResourceHealthCheck(resourceInstallationID uuid.UUID, resourceEndpointID *uuid.UUID, resourceCredentialID *uuid.UUID, opts ...ResourceHealthCheckOption) models.ResourceHealthCheckEntity {
	f := &ResourceHealthCheckFactory{
		ResourceHealthCheckEntity: models.ResourceHealthCheckEntity{
			Name:                   faker.Word(),
			Kind:                   faker.Word(),
			Configuration:          json.RawMessage{},
			IntervalSeconds:        randomInt(1, 1000, 100),
			TimeoutSeconds:         randomInt(1, 1000, 100),
			FailureThreshold:       randomInt(1, 1000, 100),
			SuccessThreshold:       randomInt(1, 1000, 100),
			Enabled:                randomBool(),
			ArchivedAt:             sql.NullTime{Time: time.Now(), Valid: true},
			ResourceInstallationID: resourceInstallationID,
			ResourceEndpointID:     resourceEndpointID,
			ResourceCredentialID:   resourceCredentialID,
		},
	}

	for _, opt := range opts {
		opt(f)
	}

	return f.ResourceHealthCheckEntity
}

func CreateResourceHealthCheck(ctx context.Context, exec storage.Executor, resourceInstallationID uuid.UUID, resourceEndpointID *uuid.UUID, resourceCredentialID *uuid.UUID, opts ...ResourceHealthCheckOption) (models.ResourceHealthCheckEntity, error) {
	built := BuildResourceHealthCheck(resourceInstallationID, resourceEndpointID, resourceCredentialID, opts...)

	entity := models.ResourceHealthCheckEntity{
		ID:                     uuid.New(),
		CreatedAt:              time.Now(),
		UpdatedAt:              time.Now(),
		Name:                   built.Name,
		Kind:                   built.Kind,
		Configuration:          built.Configuration,
		IntervalSeconds:        built.IntervalSeconds,
		TimeoutSeconds:         built.TimeoutSeconds,
		FailureThreshold:       built.FailureThreshold,
		SuccessThreshold:       built.SuccessThreshold,
		Enabled:                built.Enabled,
		ArchivedAt:             built.ArchivedAt,
		ResourceInstallationID: built.ResourceInstallationID,
		ResourceEndpointID:     built.ResourceEndpointID,
		ResourceCredentialID:   built.ResourceCredentialID,
	}

	if err := exec.NewInsert().Model(&entity).Returning("*").Scan(ctx); err != nil {
		return models.ResourceHealthCheckEntity{}, err
	}

	return entity, nil
}

func CreateResourceHealthChecks(ctx context.Context, exec storage.Executor, resourceInstallationID uuid.UUID, resourceEndpointID *uuid.UUID, resourceCredentialID *uuid.UUID, count int, opts ...ResourceHealthCheckOption) ([]models.ResourceHealthCheckEntity, error) {
	resourcehealthchecks := make([]models.ResourceHealthCheckEntity, 0, count)

	for i := range count {
		entity, err := CreateResourceHealthCheck(ctx, exec, resourceInstallationID, resourceEndpointID, resourceCredentialID, opts...)
		if err != nil {
			return nil, fmt.Errorf("failed to create resourcehealthcheck %d: %w", i+1, err)
		}
		resourcehealthchecks = append(resourcehealthchecks, entity)
	}

	return resourcehealthchecks, nil
}

func WithResourceHealthChecksName(value string) ResourceHealthCheckOption {
	return func(f *ResourceHealthCheckFactory) {
		f.ResourceHealthCheckEntity.Name = value
	}
}

func WithResourceHealthChecksKind(value string) ResourceHealthCheckOption {
	return func(f *ResourceHealthCheckFactory) {
		f.ResourceHealthCheckEntity.Kind = value
	}
}

func WithResourceHealthChecksConfiguration(value json.RawMessage) ResourceHealthCheckOption {
	return func(f *ResourceHealthCheckFactory) {
		f.ResourceHealthCheckEntity.Configuration = value
	}
}

func WithResourceHealthChecksIntervalSeconds(value int32) ResourceHealthCheckOption {
	return func(f *ResourceHealthCheckFactory) {
		f.ResourceHealthCheckEntity.IntervalSeconds = value
	}
}

func WithResourceHealthChecksTimeoutSeconds(value int32) ResourceHealthCheckOption {
	return func(f *ResourceHealthCheckFactory) {
		f.ResourceHealthCheckEntity.TimeoutSeconds = value
	}
}

func WithResourceHealthChecksFailureThreshold(value int32) ResourceHealthCheckOption {
	return func(f *ResourceHealthCheckFactory) {
		f.ResourceHealthCheckEntity.FailureThreshold = value
	}
}

func WithResourceHealthChecksSuccessThreshold(value int32) ResourceHealthCheckOption {
	return func(f *ResourceHealthCheckFactory) {
		f.ResourceHealthCheckEntity.SuccessThreshold = value
	}
}

func WithResourceHealthChecksEnabled(value bool) ResourceHealthCheckOption {
	return func(f *ResourceHealthCheckFactory) {
		f.ResourceHealthCheckEntity.Enabled = value
	}
}

func WithResourceHealthChecksArchivedAt(value sql.NullTime) ResourceHealthCheckOption {
	return func(f *ResourceHealthCheckFactory) {
		f.ResourceHealthCheckEntity.ArchivedAt = value
	}
}

func WithResourceHealthChecksResourceInstallationID(value uuid.UUID) ResourceHealthCheckOption {
	return func(f *ResourceHealthCheckFactory) {
		f.ResourceHealthCheckEntity.ResourceInstallationID = value
	}
}

func WithResourceHealthChecksResourceEndpointID(value *uuid.UUID) ResourceHealthCheckOption {
	return func(f *ResourceHealthCheckFactory) {
		f.ResourceHealthCheckEntity.ResourceEndpointID = value
	}
}

func WithResourceHealthChecksResourceCredentialID(value *uuid.UUID) ResourceHealthCheckOption {
	return func(f *ResourceHealthCheckFactory) {
		f.ResourceHealthCheckEntity.ResourceCredentialID = value
	}
}
