package factories

import (
	"context"
	"database/sql"
	"deploycrate-ce/internal/storage"
	"deploycrate-ce/models"
	"encoding/json"
	"fmt"
	"time"

	"github.com/go-faker/faker/v4"
	"github.com/google/uuid"
)

// Factory declarations below are generated by Andurel.

type ResourceBindingFactory struct {
	models.ResourceBindingEntity
}

type ResourceBindingOption func(*ResourceBindingFactory)

func BuildResourceBinding(resourceID uuid.UUID, resourceEndpointID uuid.UUID, environmentDependencyID uuid.UUID, opts ...ResourceBindingOption) models.ResourceBindingEntity {
	f := &ResourceBindingFactory{
		ResourceBindingEntity: models.ResourceBindingEntity{
			ResourceID:              resourceID,
			ResourceEndpointID:      resourceEndpointID,
			EnvironmentDependencyID: environmentDependencyID,
			ProvisioningMode:        faker.Word(),
			SecretManagementMode:    faker.Word(),
			Kind:                    faker.Word(),
			ExternalDatabase:        sql.NullString{String: faker.Word(), Valid: true},
			ExternalPrincipal:       sql.NullString{String: faker.Word(), Valid: true},
			Configuration:           json.RawMessage{},
			Status:                  faker.Word(),
			ArchivedAt:              sql.NullTime{Time: time.Now(), Valid: true},
		},
	}

	for _, opt := range opts {
		opt(f)
	}

	return f.ResourceBindingEntity
}

func CreateResourceBinding(ctx context.Context, exec storage.Executor, resourceID uuid.UUID, resourceEndpointID uuid.UUID, environmentDependencyID uuid.UUID, opts ...ResourceBindingOption) (models.ResourceBindingEntity, error) {
	built := BuildResourceBinding(resourceID, resourceEndpointID, environmentDependencyID, opts...)

	entity := models.ResourceBindingEntity{
		ID:                      uuid.New(),
		CreatedAt:               time.Now(),
		UpdatedAt:               time.Now(),
		ResourceID:              built.ResourceID,
		ResourceEndpointID:      built.ResourceEndpointID,
		EnvironmentDependencyID: built.EnvironmentDependencyID,
		ProvisioningMode:        built.ProvisioningMode,
		SecretManagementMode:    built.SecretManagementMode,
		Kind:                    built.Kind,
		ExternalDatabase:        built.ExternalDatabase,
		ExternalPrincipal:       built.ExternalPrincipal,
		Configuration:           built.Configuration,
		Status:                  built.Status,
		ArchivedAt:              built.ArchivedAt,
	}

	if err := exec.NewInsert().Model(&entity).Returning("*").Scan(ctx); err != nil {
		return models.ResourceBindingEntity{}, err
	}

	return entity, nil
}

func CreateResourceBindings(ctx context.Context, exec storage.Executor, resourceID uuid.UUID, resourceEndpointID uuid.UUID, environmentDependencyID uuid.UUID, count int, opts ...ResourceBindingOption) ([]models.ResourceBindingEntity, error) {
	resourcebindings := make([]models.ResourceBindingEntity, 0, count)

	for i := range count {
		entity, err := CreateResourceBinding(ctx, exec, resourceID, resourceEndpointID, environmentDependencyID, opts...)
		if err != nil {
			return nil, fmt.Errorf("failed to create resourcebinding %d: %w", i+1, err)
		}
		resourcebindings = append(resourcebindings, entity)
	}

	return resourcebindings, nil
}

func WithResourceBindingsResourceID(value uuid.UUID) ResourceBindingOption {
	return func(f *ResourceBindingFactory) {
		f.ResourceBindingEntity.ResourceID = value
	}
}

func WithResourceBindingsResourceEndpointID(value uuid.UUID) ResourceBindingOption {
	return func(f *ResourceBindingFactory) {
		f.ResourceBindingEntity.ResourceEndpointID = value
	}
}

func WithResourceBindingsEnvironmentDependencyID(value uuid.UUID) ResourceBindingOption {
	return func(f *ResourceBindingFactory) {
		f.ResourceBindingEntity.EnvironmentDependencyID = value
	}
}

func WithResourceBindingsProvisioningMode(value string) ResourceBindingOption {
	return func(f *ResourceBindingFactory) {
		f.ResourceBindingEntity.ProvisioningMode = value
	}
}

func WithResourceBindingsSecretManagementMode(value string) ResourceBindingOption {
	return func(f *ResourceBindingFactory) {
		f.ResourceBindingEntity.SecretManagementMode = value
	}
}

func WithResourceBindingsKind(value string) ResourceBindingOption {
	return func(f *ResourceBindingFactory) {
		f.ResourceBindingEntity.Kind = value
	}
}

func WithResourceBindingsExternalDatabase(value sql.NullString) ResourceBindingOption {
	return func(f *ResourceBindingFactory) {
		f.ResourceBindingEntity.ExternalDatabase = value
	}
}

func WithResourceBindingsExternalPrincipal(value sql.NullString) ResourceBindingOption {
	return func(f *ResourceBindingFactory) {
		f.ResourceBindingEntity.ExternalPrincipal = value
	}
}

func WithResourceBindingsConfiguration(value json.RawMessage) ResourceBindingOption {
	return func(f *ResourceBindingFactory) {
		f.ResourceBindingEntity.Configuration = value
	}
}

func WithResourceBindingsStatus(value string) ResourceBindingOption {
	return func(f *ResourceBindingFactory) {
		f.ResourceBindingEntity.Status = value
	}
}

func WithResourceBindingsArchivedAt(value sql.NullTime) ResourceBindingOption {
	return func(f *ResourceBindingFactory) {
		f.ResourceBindingEntity.ArchivedAt = value
	}
}
