package factories

import (
	"context"
	"database/sql"
	"deploycrate-ce/internal/storage"
	"deploycrate-ce/models"
	"encoding/json"
	"fmt"
	"time"

	"github.com/go-faker/faker/v4"
	"github.com/google/uuid"
)

// Factory declarations below are generated by Andurel.

type ResourceInstallationFactory struct {
	models.ResourceInstallationEntity
}

type ResourceInstallationOption func(*ResourceInstallationFactory)

func BuildResourceInstallation(resourceID uuid.UUID, serverID *uuid.UUID, opts ...ResourceInstallationOption) models.ResourceInstallationEntity {
	f := &ResourceInstallationFactory{
		ResourceInstallationEntity: models.ResourceInstallationEntity{
			ResourceID:     resourceID,
			ServerID:       serverID,
			Mode:           faker.Word(),
			Driver:         faker.Word(),
			DesiredVersion: sql.NullString{String: faker.Word(), Valid: true},
			Configuration:  json.RawMessage{},
			ArchivedAt:     sql.NullTime{Time: time.Now(), Valid: true},
		},
	}

	for _, opt := range opts {
		opt(f)
	}

	return f.ResourceInstallationEntity
}

func CreateResourceInstallation(ctx context.Context, exec storage.Executor, resourceID uuid.UUID, serverID *uuid.UUID, opts ...ResourceInstallationOption) (models.ResourceInstallationEntity, error) {
	built := BuildResourceInstallation(resourceID, serverID, opts...)

	entity := models.ResourceInstallationEntity{
		ID:             uuid.New(),
		CreatedAt:      time.Now(),
		UpdatedAt:      time.Now(),
		ResourceID:     built.ResourceID,
		ServerID:       built.ServerID,
		Mode:           built.Mode,
		Driver:         built.Driver,
		DesiredVersion: built.DesiredVersion,
		Configuration:  built.Configuration,
		ArchivedAt:     built.ArchivedAt,
	}

	if err := exec.NewInsert().Model(&entity).Returning("*").Scan(ctx); err != nil {
		return models.ResourceInstallationEntity{}, err
	}

	return entity, nil
}

func CreateResourceInstallations(ctx context.Context, exec storage.Executor, resourceID uuid.UUID, serverID *uuid.UUID, count int, opts ...ResourceInstallationOption) ([]models.ResourceInstallationEntity, error) {
	resourceinstallations := make([]models.ResourceInstallationEntity, 0, count)

	for i := range count {
		entity, err := CreateResourceInstallation(ctx, exec, resourceID, serverID, opts...)
		if err != nil {
			return nil, fmt.Errorf("failed to create resourceinstallation %d: %w", i+1, err)
		}
		resourceinstallations = append(resourceinstallations, entity)
	}

	return resourceinstallations, nil
}

func WithResourceInstallationsResourceID(value uuid.UUID) ResourceInstallationOption {
	return func(f *ResourceInstallationFactory) {
		f.ResourceInstallationEntity.ResourceID = value
	}
}

func WithResourceInstallationsServerID(value *uuid.UUID) ResourceInstallationOption {
	return func(f *ResourceInstallationFactory) {
		f.ResourceInstallationEntity.ServerID = value
	}
}

func WithResourceInstallationsMode(value string) ResourceInstallationOption {
	return func(f *ResourceInstallationFactory) {
		f.ResourceInstallationEntity.Mode = value
	}
}

func WithResourceInstallationsDriver(value string) ResourceInstallationOption {
	return func(f *ResourceInstallationFactory) {
		f.ResourceInstallationEntity.Driver = value
	}
}

func WithResourceInstallationsDesiredVersion(value sql.NullString) ResourceInstallationOption {
	return func(f *ResourceInstallationFactory) {
		f.ResourceInstallationEntity.DesiredVersion = value
	}
}

func WithResourceInstallationsConfiguration(value json.RawMessage) ResourceInstallationOption {
	return func(f *ResourceInstallationFactory) {
		f.ResourceInstallationEntity.Configuration = value
	}
}

func WithResourceInstallationsArchivedAt(value sql.NullTime) ResourceInstallationOption {
	return func(f *ResourceInstallationFactory) {
		f.ResourceInstallationEntity.ArchivedAt = value
	}
}
