package factories

import (
	"context"
	"database/sql"
	"deploycrate-ce/internal/storage"
	"deploycrate-ce/models"
	"encoding/json"
	"fmt"
	"time"

	"github.com/go-faker/faker/v4"
	"github.com/google/uuid"
)

// Factory declarations below are generated by Andurel.

type ResourceCredentialFactory struct {
	models.ResourceCredentialEntity
}

type ResourceCredentialOption func(*ResourceCredentialFactory)

func BuildResourceCredential(
	resourceID uuid.UUID,
	resourceInstallationID *uuid.UUID,
	opts ...ResourceCredentialOption,
) models.ResourceCredentialEntity {
	f := &ResourceCredentialFactory{
		ResourceCredentialEntity: models.ResourceCredentialEntity{
			Name:                   faker.Word(),
			Role:                   faker.Word(),
			Username:               sql.NullString{String: faker.Word(), Valid: true},
			Metadata:               json.RawMessage{},
			EncPayload:             []byte{},
			ArchivedAt:             sql.NullTime{Time: time.Now(), Valid: true},
			ResourceID:             resourceID,
			ResourceInstallationID: resourceInstallationID,
		},
	}

	for _, opt := range opts {
		opt(f)
	}

	return f.ResourceCredentialEntity
}

func CreateResourceCredential(
	ctx context.Context,
	exec storage.Executor,
	resourceID uuid.UUID,
	resourceInstallationID *uuid.UUID,
	opts ...ResourceCredentialOption,
) (models.ResourceCredentialEntity, error) {
	built := BuildResourceCredential(resourceID, resourceInstallationID, opts...)

	entity := models.ResourceCredentialEntity{
		ID:                     uuid.New(),
		CreatedAt:              time.Now(),
		UpdatedAt:              time.Now(),
		Name:                   built.Name,
		Role:                   built.Role,
		Username:               built.Username,
		Metadata:               built.Metadata,
		EncPayload:             built.EncPayload,
		ArchivedAt:             built.ArchivedAt,
		ResourceID:             built.ResourceID,
		ResourceInstallationID: built.ResourceInstallationID,
	}

	if err := exec.NewInsert().Model(&entity).Returning("*").Scan(ctx); err != nil {
		return models.ResourceCredentialEntity{}, err
	}

	return entity, nil
}

func CreateResourceCredentials(
	ctx context.Context,
	exec storage.Executor,
	resourceID uuid.UUID,
	resourceInstallationID *uuid.UUID,
	count int,
	opts ...ResourceCredentialOption,
) ([]models.ResourceCredentialEntity, error) {
	resourcecredentials := make([]models.ResourceCredentialEntity, 0, count)

	for i := range count {
		entity, err := CreateResourceCredential(
			ctx,
			exec,
			resourceID,
			resourceInstallationID,
			opts...)
		if err != nil {
			return nil, fmt.Errorf("failed to create resourcecredential %d: %w", i+1, err)
		}
		resourcecredentials = append(resourcecredentials, entity)
	}

	return resourcecredentials, nil
}

func WithResourceCredentialsName(value string) ResourceCredentialOption {
	return func(f *ResourceCredentialFactory) {
		f.ResourceCredentialEntity.Name = value
	}
}

func WithResourceCredentialsRole(value string) ResourceCredentialOption {
	return func(f *ResourceCredentialFactory) {
		f.ResourceCredentialEntity.Role = value
	}
}

func WithResourceCredentialsUsername(value sql.NullString) ResourceCredentialOption {
	return func(f *ResourceCredentialFactory) {
		f.ResourceCredentialEntity.Username = value
	}
}

func WithResourceCredentialsMetadata(value json.RawMessage) ResourceCredentialOption {
	return func(f *ResourceCredentialFactory) {
		f.ResourceCredentialEntity.Metadata = value
	}
}

func WithResourceCredentialsEncPayload(value []byte) ResourceCredentialOption {
	return func(f *ResourceCredentialFactory) {
		f.ResourceCredentialEntity.EncPayload = value
	}
}

func WithResourceCredentialsArchivedAt(value sql.NullTime) ResourceCredentialOption {
	return func(f *ResourceCredentialFactory) {
		f.ResourceCredentialEntity.ArchivedAt = value
	}
}

func WithResourceCredentialsResourceID(value uuid.UUID) ResourceCredentialOption {
	return func(f *ResourceCredentialFactory) {
		f.ResourceCredentialEntity.ResourceID = value
	}
}

func WithResourceCredentialsResourceInstallationID(value *uuid.UUID) ResourceCredentialOption {
	return func(f *ResourceCredentialFactory) {
		f.ResourceCredentialEntity.ResourceInstallationID = value
	}
}
