package factories

import (
	"context"
	"database/sql"
	"deploycrate-ce/internal/storage"
	"deploycrate-ce/models"
	"fmt"
	"time"

	"github.com/go-faker/faker/v4"
	"github.com/google/uuid"
)

// Factory declarations below are generated by Andurel.

type ResourceRestoreFactory struct {
	models.ResourceRestoreEntity
}

type ResourceRestoreOption func(*ResourceRestoreFactory)

func BuildResourceRestore(
	changeID uuid.UUID,
	changeTaskID uuid.UUID,
	backupID uuid.UUID,
	resourceID uuid.UUID,
	sourceEnvironmentResourceID *uuid.UUID,
	targetEnvironmentResourceID *uuid.UUID,
	targetInstallationID *uuid.UUID,
	opts ...ResourceRestoreOption,
) models.ResourceRestoreEntity {
	f := &ResourceRestoreFactory{
		ResourceRestoreEntity: models.ResourceRestoreEntity{
			Status:                      faker.Word(),
			RequestedAt:                 time.Time{},
			StartedAt:                   sql.NullTime{Time: time.Now(), Valid: true},
			FinishedAt:                  sql.NullTime{Time: time.Now(), Valid: true},
			VerifiedAt:                  sql.NullTime{Time: time.Now(), Valid: true},
			Error:                       sql.NullString{String: faker.Word(), Valid: true},
			ChangeID:                    changeID,
			ChangeTaskID:                changeTaskID,
			BackupID:                    backupID,
			ResourceID:                  resourceID,
			SourceEnvironmentResourceID: sourceEnvironmentResourceID,
			TargetEnvironmentResourceID: targetEnvironmentResourceID,
			TargetInstallationID:        targetInstallationID,
		},
	}

	for _, opt := range opts {
		opt(f)
	}

	return f.ResourceRestoreEntity
}

func CreateResourceRestore(
	ctx context.Context,
	exec storage.Executor,
	changeID uuid.UUID,
	changeTaskID uuid.UUID,
	backupID uuid.UUID,
	resourceID uuid.UUID,
	sourceEnvironmentResourceID *uuid.UUID,
	targetEnvironmentResourceID *uuid.UUID,
	targetInstallationID *uuid.UUID,
	opts ...ResourceRestoreOption,
) (models.ResourceRestoreEntity, error) {
	built := BuildResourceRestore(
		changeID,
		changeTaskID,
		backupID,
		resourceID,
		sourceEnvironmentResourceID,
		targetEnvironmentResourceID,
		targetInstallationID,
		opts...)

	entity := models.ResourceRestoreEntity{
		ID:                          uuid.New(),
		CreatedAt:                   time.Now(),
		UpdatedAt:                   time.Now(),
		Status:                      built.Status,
		RequestedAt:                 built.RequestedAt,
		StartedAt:                   built.StartedAt,
		FinishedAt:                  built.FinishedAt,
		VerifiedAt:                  built.VerifiedAt,
		Error:                       built.Error,
		ChangeID:                    built.ChangeID,
		ChangeTaskID:                built.ChangeTaskID,
		BackupID:                    built.BackupID,
		ResourceID:                  built.ResourceID,
		SourceEnvironmentResourceID: built.SourceEnvironmentResourceID,
		TargetEnvironmentResourceID: built.TargetEnvironmentResourceID,
		TargetInstallationID:        built.TargetInstallationID,
	}

	if err := exec.NewInsert().Model(&entity).Returning("*").Scan(ctx); err != nil {
		return models.ResourceRestoreEntity{}, err
	}

	return entity, nil
}

func CreateResourceRestores(
	ctx context.Context,
	exec storage.Executor,
	changeID uuid.UUID,
	changeTaskID uuid.UUID,
	backupID uuid.UUID,
	resourceID uuid.UUID,
	sourceEnvironmentResourceID *uuid.UUID,
	targetEnvironmentResourceID *uuid.UUID,
	targetInstallationID *uuid.UUID,
	count int,
	opts ...ResourceRestoreOption,
) ([]models.ResourceRestoreEntity, error) {
	resourcerestores := make([]models.ResourceRestoreEntity, 0, count)

	for i := range count {
		entity, err := CreateResourceRestore(
			ctx,
			exec,
			changeID,
			changeTaskID,
			backupID,
			resourceID,
			sourceEnvironmentResourceID,
			targetEnvironmentResourceID,
			targetInstallationID,
			opts...)
		if err != nil {
			return nil, fmt.Errorf("failed to create resourcerestore %d: %w", i+1, err)
		}
		resourcerestores = append(resourcerestores, entity)
	}

	return resourcerestores, nil
}

func WithResourceRestoresStatus(value string) ResourceRestoreOption {
	return func(f *ResourceRestoreFactory) {
		f.ResourceRestoreEntity.Status = value
	}
}

func WithResourceRestoresRequestedAt(value time.Time) ResourceRestoreOption {
	return func(f *ResourceRestoreFactory) {
		f.ResourceRestoreEntity.RequestedAt = value
	}
}

func WithResourceRestoresStartedAt(value sql.NullTime) ResourceRestoreOption {
	return func(f *ResourceRestoreFactory) {
		f.ResourceRestoreEntity.StartedAt = value
	}
}

func WithResourceRestoresFinishedAt(value sql.NullTime) ResourceRestoreOption {
	return func(f *ResourceRestoreFactory) {
		f.ResourceRestoreEntity.FinishedAt = value
	}
}

func WithResourceRestoresVerifiedAt(value sql.NullTime) ResourceRestoreOption {
	return func(f *ResourceRestoreFactory) {
		f.ResourceRestoreEntity.VerifiedAt = value
	}
}

func WithResourceRestoresError(value sql.NullString) ResourceRestoreOption {
	return func(f *ResourceRestoreFactory) {
		f.ResourceRestoreEntity.Error = value
	}
}

func WithResourceRestoresChangeID(value uuid.UUID) ResourceRestoreOption {
	return func(f *ResourceRestoreFactory) {
		f.ResourceRestoreEntity.ChangeID = value
	}
}

func WithResourceRestoresChangeTaskID(value uuid.UUID) ResourceRestoreOption {
	return func(f *ResourceRestoreFactory) {
		f.ResourceRestoreEntity.ChangeTaskID = value
	}
}

func WithResourceRestoresBackupID(value uuid.UUID) ResourceRestoreOption {
	return func(f *ResourceRestoreFactory) {
		f.ResourceRestoreEntity.BackupID = value
	}
}

func WithResourceRestoresResourceID(value uuid.UUID) ResourceRestoreOption {
	return func(f *ResourceRestoreFactory) {
		f.ResourceRestoreEntity.ResourceID = value
	}
}

func WithResourceRestoresSourceEnvironmentResourceID(value *uuid.UUID) ResourceRestoreOption {
	return func(f *ResourceRestoreFactory) {
		f.ResourceRestoreEntity.SourceEnvironmentResourceID = value
	}
}

func WithResourceRestoresTargetEnvironmentResourceID(value *uuid.UUID) ResourceRestoreOption {
	return func(f *ResourceRestoreFactory) {
		f.ResourceRestoreEntity.TargetEnvironmentResourceID = value
	}
}

func WithResourceRestoresTargetInstallationID(value *uuid.UUID) ResourceRestoreOption {
	return func(f *ResourceRestoreFactory) {
		f.ResourceRestoreEntity.TargetInstallationID = value
	}
}
