package factories

import (
	"context"
	"database/sql"
	"deploycrate-ce/internal/storage"
	"deploycrate-ce/models"
	"encoding/json"
	"fmt"
	"time"

	"github.com/go-faker/faker/v4"
	"github.com/google/uuid"
)

// Factory declarations below are generated by Andurel.

type ResourceHealthCheckStatusFactory struct {
	models.ResourceHealthCheckStatusEntity
}

type ResourceHealthCheckStatusOption func(*ResourceHealthCheckStatusFactory)

func BuildResourceHealthCheckStatus(
	healthCheckID uuid.UUID,
	opts ...ResourceHealthCheckStatusOption,
) models.ResourceHealthCheckStatusEntity {
	f := &ResourceHealthCheckStatusFactory{
		ResourceHealthCheckStatusEntity: models.ResourceHealthCheckStatusEntity{
			State:                faker.Word(),
			StatusCode:           sql.NullInt32{Int32: randomInt(1, 1000, 100), Valid: true},
			LatencyMs:            sql.NullInt32{Int32: randomInt(1, 1000, 100), Valid: true},
			Message:              sql.NullString{String: faker.Word(), Valid: true},
			ConsecutiveSuccesses: randomInt(1, 1000, 100),
			ConsecutiveFailures:  randomInt(1, 1000, 100),
			Details:              json.RawMessage{},
			ObservedAt:           time.Time{},
			ExpiresAt:            time.Time{},
			HealthCheckID:        healthCheckID,
		},
	}

	for _, opt := range opts {
		opt(f)
	}

	return f.ResourceHealthCheckStatusEntity
}

func CreateResourceHealthCheckStatus(
	ctx context.Context,
	exec storage.Executor,
	healthCheckID uuid.UUID,
	opts ...ResourceHealthCheckStatusOption,
) (models.ResourceHealthCheckStatusEntity, error) {
	built := BuildResourceHealthCheckStatus(healthCheckID, opts...)

	entity := models.ResourceHealthCheckStatusEntity{
		CreatedAt:            time.Now(),
		UpdatedAt:            time.Now(),
		State:                built.State,
		StatusCode:           built.StatusCode,
		LatencyMs:            built.LatencyMs,
		Message:              built.Message,
		ConsecutiveSuccesses: built.ConsecutiveSuccesses,
		ConsecutiveFailures:  built.ConsecutiveFailures,
		Details:              built.Details,
		ObservedAt:           built.ObservedAt,
		ExpiresAt:            built.ExpiresAt,
		HealthCheckID:        built.HealthCheckID,
	}

	if err := exec.NewInsert().Model(&entity).Returning("*").Scan(ctx); err != nil {
		return models.ResourceHealthCheckStatusEntity{}, err
	}

	return entity, nil
}

func CreateResourceHealthCheckStatuss(
	ctx context.Context,
	exec storage.Executor,
	healthCheckID uuid.UUID,
	count int,
	opts ...ResourceHealthCheckStatusOption,
) ([]models.ResourceHealthCheckStatusEntity, error) {
	resourcehealthcheckstatuss := make([]models.ResourceHealthCheckStatusEntity, 0, count)

	for i := range count {
		entity, err := CreateResourceHealthCheckStatus(ctx, exec, healthCheckID, opts...)
		if err != nil {
			return nil, fmt.Errorf("failed to create resourcehealthcheckstatus %d: %w", i+1, err)
		}
		resourcehealthcheckstatuss = append(resourcehealthcheckstatuss, entity)
	}

	return resourcehealthcheckstatuss, nil
}

func WithResourceHealthCheckStatusesState(value string) ResourceHealthCheckStatusOption {
	return func(f *ResourceHealthCheckStatusFactory) {
		f.ResourceHealthCheckStatusEntity.State = value
	}
}

func WithResourceHealthCheckStatusesStatusCode(
	value sql.NullInt32,
) ResourceHealthCheckStatusOption {
	return func(f *ResourceHealthCheckStatusFactory) {
		f.ResourceHealthCheckStatusEntity.StatusCode = value
	}
}

func WithResourceHealthCheckStatusesLatencyMs(value sql.NullInt32) ResourceHealthCheckStatusOption {
	return func(f *ResourceHealthCheckStatusFactory) {
		f.ResourceHealthCheckStatusEntity.LatencyMs = value
	}
}

func WithResourceHealthCheckStatusesMessage(value sql.NullString) ResourceHealthCheckStatusOption {
	return func(f *ResourceHealthCheckStatusFactory) {
		f.ResourceHealthCheckStatusEntity.Message = value
	}
}

func WithResourceHealthCheckStatusesConsecutiveSuccesses(
	value int32,
) ResourceHealthCheckStatusOption {
	return func(f *ResourceHealthCheckStatusFactory) {
		f.ResourceHealthCheckStatusEntity.ConsecutiveSuccesses = value
	}
}

func WithResourceHealthCheckStatusesConsecutiveFailures(
	value int32,
) ResourceHealthCheckStatusOption {
	return func(f *ResourceHealthCheckStatusFactory) {
		f.ResourceHealthCheckStatusEntity.ConsecutiveFailures = value
	}
}

func WithResourceHealthCheckStatusesDetails(value json.RawMessage) ResourceHealthCheckStatusOption {
	return func(f *ResourceHealthCheckStatusFactory) {
		f.ResourceHealthCheckStatusEntity.Details = value
	}
}

func WithResourceHealthCheckStatusesObservedAt(value time.Time) ResourceHealthCheckStatusOption {
	return func(f *ResourceHealthCheckStatusFactory) {
		f.ResourceHealthCheckStatusEntity.ObservedAt = value
	}
}

func WithResourceHealthCheckStatusesExpiresAt(value time.Time) ResourceHealthCheckStatusOption {
	return func(f *ResourceHealthCheckStatusFactory) {
		f.ResourceHealthCheckStatusEntity.ExpiresAt = value
	}
}

func WithResourceHealthCheckStatusesHealthCheckID(value uuid.UUID) ResourceHealthCheckStatusOption {
	return func(f *ResourceHealthCheckStatusFactory) {
		f.ResourceHealthCheckStatusEntity.HealthCheckID = value
	}
}
