package factories

import (
	"context"
	"database/sql"
	"deploycrate-ce/internal/storage"
	"deploycrate-ce/models"
	"encoding/json"
	"fmt"
	"time"

	"github.com/go-faker/faker/v4"
	"github.com/google/uuid"
)

// Factory declarations below are generated by Andurel.

type ResourceInstallationStatusFactory struct {
	models.ResourceInstallationStatusEntity
}

type ResourceInstallationStatusOption func(*ResourceInstallationStatusFactory)

func BuildResourceInstallationStatus(resourceInstallationID uuid.UUID, externalID sql.NullString, opts ...ResourceInstallationStatusOption) models.ResourceInstallationStatusEntity {
	f := &ResourceInstallationStatusFactory{
		ResourceInstallationStatusEntity: models.ResourceInstallationStatusEntity{
			ResourceInstallationID: resourceInstallationID,
			ExternalID:             externalID,
			State:                  faker.Word(),
			InstalledVersion:       sql.NullString{String: faker.Word(), Valid: true},
			ServiceState:           sql.NullString{String: faker.Word(), Valid: true},
			Health:                 sql.NullString{String: faker.Word(), Valid: true},
			Details:                json.RawMessage{},
			ObservedAt:             time.Time{},
		},
	}

	for _, opt := range opts {
		opt(f)
	}

	return f.ResourceInstallationStatusEntity
}

func CreateResourceInstallationStatus(ctx context.Context, exec storage.Executor, resourceInstallationID uuid.UUID, externalID sql.NullString, opts ...ResourceInstallationStatusOption) (models.ResourceInstallationStatusEntity, error) {
	built := BuildResourceInstallationStatus(resourceInstallationID, externalID, opts...)

	entity := models.ResourceInstallationStatusEntity{
		ID:                     built.ID,
		CreatedAt:              time.Now(),
		UpdatedAt:              time.Now(),
		ResourceInstallationID: built.ResourceInstallationID,
		ExternalID:             built.ExternalID,
		State:                  built.State,
		InstalledVersion:       built.InstalledVersion,
		ServiceState:           built.ServiceState,
		Health:                 built.Health,
		Details:                built.Details,
		ObservedAt:             built.ObservedAt,
	}

	if err := exec.NewInsert().Model(&entity).Returning("*").Scan(ctx); err != nil {
		return models.ResourceInstallationStatusEntity{}, err
	}

	return entity, nil
}

func CreateResourceInstallationStatuses(ctx context.Context, exec storage.Executor, resourceInstallationID uuid.UUID, externalID sql.NullString, count int, opts ...ResourceInstallationStatusOption) ([]models.ResourceInstallationStatusEntity, error) {
	resourceInstallationStatuses := make([]models.ResourceInstallationStatusEntity, 0, count)

	for i := range count {
		entity, err := CreateResourceInstallationStatus(ctx, exec, resourceInstallationID, externalID, opts...)
		if err != nil {
			return nil, fmt.Errorf("failed to create resourceinstallationstatus %d: %w", i+1, err)
		}
		resourceInstallationStatuses = append(resourceInstallationStatuses, entity)
	}

	return resourceInstallationStatuses, nil
}

func WithResourceInstallationStatusesResourceInstallationID(value uuid.UUID) ResourceInstallationStatusOption {
	return func(f *ResourceInstallationStatusFactory) {
		f.ResourceInstallationStatusEntity.ResourceInstallationID = value
	}
}

func WithResourceInstallationStatusesExternalID(value sql.NullString) ResourceInstallationStatusOption {
	return func(f *ResourceInstallationStatusFactory) {
		f.ResourceInstallationStatusEntity.ExternalID = value
	}
}

func WithResourceInstallationStatusesState(value string) ResourceInstallationStatusOption {
	return func(f *ResourceInstallationStatusFactory) {
		f.ResourceInstallationStatusEntity.State = value
	}
}

func WithResourceInstallationStatusesInstalledVersion(value sql.NullString) ResourceInstallationStatusOption {
	return func(f *ResourceInstallationStatusFactory) {
		f.ResourceInstallationStatusEntity.InstalledVersion = value
	}
}

func WithResourceInstallationStatusesServiceState(value sql.NullString) ResourceInstallationStatusOption {
	return func(f *ResourceInstallationStatusFactory) {
		f.ResourceInstallationStatusEntity.ServiceState = value
	}
}

func WithResourceInstallationStatusesHealth(value sql.NullString) ResourceInstallationStatusOption {
	return func(f *ResourceInstallationStatusFactory) {
		f.ResourceInstallationStatusEntity.Health = value
	}
}

func WithResourceInstallationStatusesDetails(value json.RawMessage) ResourceInstallationStatusOption {
	return func(f *ResourceInstallationStatusFactory) {
		f.ResourceInstallationStatusEntity.Details = value
	}
}

func WithResourceInstallationStatusesObservedAt(value time.Time) ResourceInstallationStatusOption {
	return func(f *ResourceInstallationStatusFactory) {
		f.ResourceInstallationStatusEntity.ObservedAt = value
	}
}
