package factories

import (
	"context"
	"database/sql"
	"deploycrate-ce/internal/storage"
	"deploycrate-ce/models"
	"fmt"
	"time"

	"github.com/go-faker/faker/v4"
	"github.com/google/uuid"
)

// Factory declarations below are generated by Andurel.

type ResourceBackupFactory struct {
	models.ResourceBackupEntity
}

type ResourceBackupOption func(*ResourceBackupFactory)

func BuildResourceBackup(changeID uuid.UUID, changeTaskID uuid.UUID, backupPolicyID uuid.UUID, resourceID uuid.UUID, resourceBindingID *uuid.UUID, resourceInstallationID *uuid.UUID, backupDestinationID uuid.UUID, opts ...ResourceBackupOption) models.ResourceBackupEntity {
	f := &ResourceBackupFactory{
		ResourceBackupEntity: models.ResourceBackupEntity{
			ChangeID:               changeID,
			ChangeTaskID:           changeTaskID,
			BackupPolicyID:         backupPolicyID,
			ResourceID:             resourceID,
			ResourceBindingID:      resourceBindingID,
			ResourceInstallationID: resourceInstallationID,
			BackupDestinationID:    backupDestinationID,
			TriggerType:            faker.Word(),
			Format:                 faker.Word(),
			ObjectKey:              faker.Word(),
			Status:                 faker.Word(),
			RequestedAt:            time.Time{},
			StartedAt:              sql.NullTime{Time: time.Now(), Valid: true},
			FinishedAt:             sql.NullTime{Time: time.Now(), Valid: true},
			SizeBytes:              sql.NullInt64{Int64: randomInt64(1, 1000, 100), Valid: true},
			Digest:                 []byte{},
			VerifiedAt:             sql.NullTime{Time: time.Now(), Valid: true},
			Error:                  sql.NullString{String: faker.Word(), Valid: true},
		},
	}

	for _, opt := range opts {
		opt(f)
	}

	return f.ResourceBackupEntity
}

func CreateResourceBackup(ctx context.Context, exec storage.Executor, changeID uuid.UUID, changeTaskID uuid.UUID, backupPolicyID uuid.UUID, resourceID uuid.UUID, resourceBindingID *uuid.UUID, resourceInstallationID *uuid.UUID, backupDestinationID uuid.UUID, opts ...ResourceBackupOption) (models.ResourceBackupEntity, error) {
	built := BuildResourceBackup(changeID, changeTaskID, backupPolicyID, resourceID, resourceBindingID, resourceInstallationID, backupDestinationID, opts...)

	entity := models.ResourceBackupEntity{
		ID:                     uuid.New(),
		CreatedAt:              time.Now(),
		UpdatedAt:              time.Now(),
		ChangeID:               built.ChangeID,
		ChangeTaskID:           built.ChangeTaskID,
		BackupPolicyID:         built.BackupPolicyID,
		ResourceID:             built.ResourceID,
		ResourceBindingID:      built.ResourceBindingID,
		ResourceInstallationID: built.ResourceInstallationID,
		BackupDestinationID:    built.BackupDestinationID,
		TriggerType:            built.TriggerType,
		Format:                 built.Format,
		ObjectKey:              built.ObjectKey,
		Status:                 built.Status,
		RequestedAt:            built.RequestedAt,
		StartedAt:              built.StartedAt,
		FinishedAt:             built.FinishedAt,
		SizeBytes:              built.SizeBytes,
		Digest:                 built.Digest,
		VerifiedAt:             built.VerifiedAt,
		Error:                  built.Error,
	}

	if err := exec.NewInsert().Model(&entity).Returning("*").Scan(ctx); err != nil {
		return models.ResourceBackupEntity{}, err
	}

	return entity, nil
}

func CreateResourceBackups(ctx context.Context, exec storage.Executor, changeID uuid.UUID, changeTaskID uuid.UUID, backupPolicyID uuid.UUID, resourceID uuid.UUID, resourceBindingID *uuid.UUID, resourceInstallationID *uuid.UUID, backupDestinationID uuid.UUID, count int, opts ...ResourceBackupOption) ([]models.ResourceBackupEntity, error) {
	resourcebackups := make([]models.ResourceBackupEntity, 0, count)

	for i := range count {
		entity, err := CreateResourceBackup(ctx, exec, changeID, changeTaskID, backupPolicyID, resourceID, resourceBindingID, resourceInstallationID, backupDestinationID, opts...)
		if err != nil {
			return nil, fmt.Errorf("failed to create resourcebackup %d: %w", i+1, err)
		}
		resourcebackups = append(resourcebackups, entity)
	}

	return resourcebackups, nil
}

func WithResourceBackupsChangeID(value uuid.UUID) ResourceBackupOption {
	return func(f *ResourceBackupFactory) {
		f.ResourceBackupEntity.ChangeID = value
	}
}

func WithResourceBackupsChangeTaskID(value uuid.UUID) ResourceBackupOption {
	return func(f *ResourceBackupFactory) {
		f.ResourceBackupEntity.ChangeTaskID = value
	}
}

func WithResourceBackupsBackupPolicyID(value uuid.UUID) ResourceBackupOption {
	return func(f *ResourceBackupFactory) {
		f.ResourceBackupEntity.BackupPolicyID = value
	}
}

func WithResourceBackupsResourceID(value uuid.UUID) ResourceBackupOption {
	return func(f *ResourceBackupFactory) {
		f.ResourceBackupEntity.ResourceID = value
	}
}

func WithResourceBackupsResourceBindingID(value *uuid.UUID) ResourceBackupOption {
	return func(f *ResourceBackupFactory) {
		f.ResourceBackupEntity.ResourceBindingID = value
	}
}

func WithResourceBackupsResourceInstallationID(value *uuid.UUID) ResourceBackupOption {
	return func(f *ResourceBackupFactory) {
		f.ResourceBackupEntity.ResourceInstallationID = value
	}
}

func WithResourceBackupsBackupDestinationID(value uuid.UUID) ResourceBackupOption {
	return func(f *ResourceBackupFactory) {
		f.ResourceBackupEntity.BackupDestinationID = value
	}
}

func WithResourceBackupsTriggerType(value string) ResourceBackupOption {
	return func(f *ResourceBackupFactory) {
		f.ResourceBackupEntity.TriggerType = value
	}
}

func WithResourceBackupsFormat(value string) ResourceBackupOption {
	return func(f *ResourceBackupFactory) {
		f.ResourceBackupEntity.Format = value
	}
}

func WithResourceBackupsObjectKey(value string) ResourceBackupOption {
	return func(f *ResourceBackupFactory) {
		f.ResourceBackupEntity.ObjectKey = value
	}
}

func WithResourceBackupsStatus(value string) ResourceBackupOption {
	return func(f *ResourceBackupFactory) {
		f.ResourceBackupEntity.Status = value
	}
}

func WithResourceBackupsRequestedAt(value time.Time) ResourceBackupOption {
	return func(f *ResourceBackupFactory) {
		f.ResourceBackupEntity.RequestedAt = value
	}
}

func WithResourceBackupsStartedAt(value sql.NullTime) ResourceBackupOption {
	return func(f *ResourceBackupFactory) {
		f.ResourceBackupEntity.StartedAt = value
	}
}

func WithResourceBackupsFinishedAt(value sql.NullTime) ResourceBackupOption {
	return func(f *ResourceBackupFactory) {
		f.ResourceBackupEntity.FinishedAt = value
	}
}

func WithResourceBackupsSizeBytes(value sql.NullInt64) ResourceBackupOption {
	return func(f *ResourceBackupFactory) {
		f.ResourceBackupEntity.SizeBytes = value
	}
}

func WithResourceBackupsDigest(value []byte) ResourceBackupOption {
	return func(f *ResourceBackupFactory) {
		f.ResourceBackupEntity.Digest = value
	}
}

func WithResourceBackupsVerifiedAt(value sql.NullTime) ResourceBackupOption {
	return func(f *ResourceBackupFactory) {
		f.ResourceBackupEntity.VerifiedAt = value
	}
}

func WithResourceBackupsError(value sql.NullString) ResourceBackupOption {
	return func(f *ResourceBackupFactory) {
		f.ResourceBackupEntity.Error = value
	}
}
