package factories

import (
	"context"
	"database/sql"
	"deploycrate-ce/internal/storage"
	"deploycrate-ce/models"
	"encoding/json"
	"fmt"
	"time"

	"github.com/go-faker/faker/v4"
	"github.com/google/uuid"
)

// Factory declarations below are generated by Andurel.

type ResourceEndpointFactory struct {
	models.ResourceEndpointEntity
}

type ResourceEndpointOption func(*ResourceEndpointFactory)

func BuildResourceEndpoint(
	resourceID uuid.UUID,
	privateNetworkID *uuid.UUID,
	opts ...ResourceEndpointOption,
) models.ResourceEndpointEntity {
	f := &ResourceEndpointFactory{
		ResourceEndpointEntity: models.ResourceEndpointEntity{
			Name:             faker.Word(),
			Role:             faker.Word(),
			Address:          faker.Word(),
			Port:             randomInt(1, 1000, 100),
			Protocol:         faker.Word(),
			TLSMode:          faker.Word(),
			Settings:         json.RawMessage{},
			ArchivedAt:       sql.NullTime{Time: time.Now(), Valid: true},
			ResourceID:       resourceID,
			PrivateNetworkID: privateNetworkID,
		},
	}

	for _, opt := range opts {
		opt(f)
	}

	return f.ResourceEndpointEntity
}

func CreateResourceEndpoint(
	ctx context.Context,
	exec storage.Executor,
	resourceID uuid.UUID,
	privateNetworkID *uuid.UUID,
	opts ...ResourceEndpointOption,
) (models.ResourceEndpointEntity, error) {
	built := BuildResourceEndpoint(resourceID, privateNetworkID, opts...)

	entity := models.ResourceEndpointEntity{
		ID:               uuid.New(),
		CreatedAt:        time.Now(),
		UpdatedAt:        time.Now(),
		Name:             built.Name,
		Role:             built.Role,
		Address:          built.Address,
		Port:             built.Port,
		Protocol:         built.Protocol,
		TLSMode:          built.TLSMode,
		Settings:         built.Settings,
		ArchivedAt:       built.ArchivedAt,
		ResourceID:       built.ResourceID,
		PrivateNetworkID: built.PrivateNetworkID,
	}

	if err := exec.NewInsert().Model(&entity).Returning("*").Scan(ctx); err != nil {
		return models.ResourceEndpointEntity{}, err
	}

	return entity, nil
}

func CreateResourceEndpoints(
	ctx context.Context,
	exec storage.Executor,
	resourceID uuid.UUID,
	privateNetworkID *uuid.UUID,
	count int,
	opts ...ResourceEndpointOption,
) ([]models.ResourceEndpointEntity, error) {
	resourceendpoints := make([]models.ResourceEndpointEntity, 0, count)

	for i := range count {
		entity, err := CreateResourceEndpoint(ctx, exec, resourceID, privateNetworkID, opts...)
		if err != nil {
			return nil, fmt.Errorf("failed to create resourceendpoint %d: %w", i+1, err)
		}
		resourceendpoints = append(resourceendpoints, entity)
	}

	return resourceendpoints, nil
}

func WithResourceEndpointsName(value string) ResourceEndpointOption {
	return func(f *ResourceEndpointFactory) {
		f.ResourceEndpointEntity.Name = value
	}
}

func WithResourceEndpointsRole(value string) ResourceEndpointOption {
	return func(f *ResourceEndpointFactory) {
		f.ResourceEndpointEntity.Role = value
	}
}

func WithResourceEndpointsAddress(value string) ResourceEndpointOption {
	return func(f *ResourceEndpointFactory) {
		f.ResourceEndpointEntity.Address = value
	}
}

func WithResourceEndpointsPort(value int32) ResourceEndpointOption {
	return func(f *ResourceEndpointFactory) {
		f.ResourceEndpointEntity.Port = value
	}
}

func WithResourceEndpointsProtocol(value string) ResourceEndpointOption {
	return func(f *ResourceEndpointFactory) {
		f.ResourceEndpointEntity.Protocol = value
	}
}

func WithResourceEndpointsTlsMode(value string) ResourceEndpointOption {
	return func(f *ResourceEndpointFactory) {
		f.ResourceEndpointEntity.TLSMode = value
	}
}

func WithResourceEndpointsSettings(value json.RawMessage) ResourceEndpointOption {
	return func(f *ResourceEndpointFactory) {
		f.ResourceEndpointEntity.Settings = value
	}
}

func WithResourceEndpointsArchivedAt(value sql.NullTime) ResourceEndpointOption {
	return func(f *ResourceEndpointFactory) {
		f.ResourceEndpointEntity.ArchivedAt = value
	}
}

func WithResourceEndpointsResourceID(value uuid.UUID) ResourceEndpointOption {
	return func(f *ResourceEndpointFactory) {
		f.ResourceEndpointEntity.ResourceID = value
	}
}

func WithResourceEndpointsPrivateNetworkID(value *uuid.UUID) ResourceEndpointOption {
	return func(f *ResourceEndpointFactory) {
		f.ResourceEndpointEntity.PrivateNetworkID = value
	}
}
