package factories

import (
	"context"
	"database/sql"
	"deploycrate-ce/internal/storage"
	"deploycrate-ce/models"
	"fmt"
	"github.com/go-faker/faker/v4"
	"time"
)

// Factory declarations below are generated by Andurel.

type ResourceFactory struct {
	models.ResourceEntity
}

type ResourceOption func(*ResourceFactory)

func BuildResource(opts ...ResourceOption) models.ResourceEntity {
	f := &ResourceFactory{
		ResourceEntity: models.ResourceEntity{
			Name:           faker.Word(),
			Slug:           faker.Word(),
			Kind:           "postgresql",
			ManagementMode: models.ResourceManagementManaged,
			SharingScope:   models.ResourceSharingEnvironment,
			SystemManaged:  false,
			ArchivedAt:     sql.NullTime{Time: time.Now(), Valid: true},
		},
	}

	for _, opt := range opts {
		opt(f)
	}

	return f.ResourceEntity
}

func CreateResource(ctx context.Context, exec storage.Executor, opts ...ResourceOption) (models.ResourceEntity, error) {
	built := BuildResource(opts...)

	entity, err := models.Resource.Create(ctx, exec, models.CreateResourceData{
		Name:           built.Name,
		Slug:           built.Slug,
		Kind:           built.Kind,
		ManagementMode: built.ManagementMode,
		SharingScope:   built.SharingScope,
		SystemManaged:  built.SystemManaged,
		ArchivedAt:     built.ArchivedAt,
	})
	if err != nil {
		return models.ResourceEntity{}, err
	}

	return entity, nil
}

func CreateResources(ctx context.Context, exec storage.Executor, count int, opts ...ResourceOption) ([]models.ResourceEntity, error) {
	resources := make([]models.ResourceEntity, 0, count)

	for i := range count {
		entity, err := CreateResource(ctx, exec, opts...)
		if err != nil {
			return nil, fmt.Errorf("failed to create resource %d: %w", i+1, err)
		}
		resources = append(resources, entity)
	}

	return resources, nil
}

func WithResourcesName(value string) ResourceOption {
	return func(f *ResourceFactory) {
		f.ResourceEntity.Name = value
	}
}

func WithResourcesSlug(value string) ResourceOption {
	return func(f *ResourceFactory) {
		f.ResourceEntity.Slug = value
	}
}

func WithResourcesKind(value string) ResourceOption {
	return func(f *ResourceFactory) {
		f.ResourceEntity.Kind = value
	}
}

func WithResourcesManagementMode(value models.ResourceManagementModeEnum) ResourceOption {
	return func(f *ResourceFactory) {
		f.ResourceEntity.ManagementMode = value
	}
}

func WithResourcesSharingScope(value models.ResourceSharingScopeEnum) ResourceOption {
	return func(f *ResourceFactory) {
		f.ResourceEntity.SharingScope = value
	}
}

func WithResourcesSystemManaged(value bool) ResourceOption {
	return func(f *ResourceFactory) {
		f.ResourceEntity.SystemManaged = value
	}
}

func WithResourcesArchivedAt(value sql.NullTime) ResourceOption {
	return func(f *ResourceFactory) {
		f.ResourceEntity.ArchivedAt = value
	}
}
