package factories

import (
	"context"
	"database/sql"
	"deploycrate-ce/internal/storage"
	"deploycrate-ce/models"
	"fmt"
	"time"

	"github.com/go-faker/faker/v4"
	"github.com/google/uuid"
)

// Factory declarations below are generated by Andurel.

type ResourceBackupFactory struct {
	models.ResourceBackupEntity
}

type ResourceBackupOption func(*ResourceBackupFactory)

func BuildResourceBackup(
	changeID uuid.UUID,
	changeTaskID uuid.UUID,
	backupPolicyID uuid.UUID,
	resourceID uuid.UUID,
	environmentResourceID *uuid.UUID,
	resourceInstallationID *uuid.UUID,
	resourceVolumeID *uuid.UUID,
	backupDestinationID uuid.UUID,
	opts ...ResourceBackupOption,
) models.ResourceBackupEntity {
	f := &ResourceBackupFactory{
		ResourceBackupEntity: models.ResourceBackupEntity{
			TriggerType:            faker.Word(),
			Strategy:               faker.Word(),
			Driver:                 faker.Word(),
			Format:                 faker.Word(),
			ObjectKey:              faker.Word(),
			Status:                 faker.Word(),
			RequestedAt:            time.Time{},
			StartedAt:              sql.NullTime{Time: time.Now(), Valid: true},
			FinishedAt:             sql.NullTime{Time: time.Now(), Valid: true},
			SizeBytes:              sql.NullInt64{Int64: randomInt64(1, 1000, 100), Valid: true},
			Digest:                 []byte{},
			VerifiedAt:             sql.NullTime{Time: time.Now(), Valid: true},
			Error:                  sql.NullString{String: faker.Word(), Valid: true},
			ChangeID:               changeID,
			ChangeTaskID:           changeTaskID,
			BackupPolicyID:         backupPolicyID,
			ResourceID:             resourceID,
			EnvironmentResourceID:  environmentResourceID,
			ResourceInstallationID: resourceInstallationID,
			ResourceVolumeID:       resourceVolumeID,
			BackupDestinationID:    backupDestinationID,
		},
	}

	for _, opt := range opts {
		opt(f)
	}

	return f.ResourceBackupEntity
}

func CreateResourceBackup(
	ctx context.Context,
	exec storage.Executor,
	changeID uuid.UUID,
	changeTaskID uuid.UUID,
	backupPolicyID uuid.UUID,
	resourceID uuid.UUID,
	environmentResourceID *uuid.UUID,
	resourceInstallationID *uuid.UUID,
	resourceVolumeID *uuid.UUID,
	backupDestinationID uuid.UUID,
	opts ...ResourceBackupOption,
) (models.ResourceBackupEntity, error) {
	built := BuildResourceBackup(
		changeID,
		changeTaskID,
		backupPolicyID,
		resourceID,
		environmentResourceID,
		resourceInstallationID,
		resourceVolumeID,
		backupDestinationID,
		opts...)

	entity := models.ResourceBackupEntity{
		ID:                     uuid.New(),
		CreatedAt:              time.Now(),
		UpdatedAt:              time.Now(),
		TriggerType:            built.TriggerType,
		Strategy:               built.Strategy,
		Driver:                 built.Driver,
		Format:                 built.Format,
		ObjectKey:              built.ObjectKey,
		Status:                 built.Status,
		RequestedAt:            built.RequestedAt,
		StartedAt:              built.StartedAt,
		FinishedAt:             built.FinishedAt,
		SizeBytes:              built.SizeBytes,
		Digest:                 built.Digest,
		VerifiedAt:             built.VerifiedAt,
		Error:                  built.Error,
		ChangeID:               built.ChangeID,
		ChangeTaskID:           built.ChangeTaskID,
		BackupPolicyID:         built.BackupPolicyID,
		ResourceID:             built.ResourceID,
		EnvironmentResourceID:  built.EnvironmentResourceID,
		ResourceInstallationID: built.ResourceInstallationID,
		ResourceVolumeID:       built.ResourceVolumeID,
		BackupDestinationID:    built.BackupDestinationID,
	}

	if err := exec.NewInsert().Model(&entity).Returning("*").Scan(ctx); err != nil {
		return models.ResourceBackupEntity{}, err
	}

	return entity, nil
}

func CreateResourceBackups(
	ctx context.Context,
	exec storage.Executor,
	changeID uuid.UUID,
	changeTaskID uuid.UUID,
	backupPolicyID uuid.UUID,
	resourceID uuid.UUID,
	environmentResourceID *uuid.UUID,
	resourceInstallationID *uuid.UUID,
	resourceVolumeID *uuid.UUID,
	backupDestinationID uuid.UUID,
	count int,
	opts ...ResourceBackupOption,
) ([]models.ResourceBackupEntity, error) {
	resourcebackups := make([]models.ResourceBackupEntity, 0, count)

	for i := range count {
		entity, err := CreateResourceBackup(
			ctx,
			exec,
			changeID,
			changeTaskID,
			backupPolicyID,
			resourceID,
			environmentResourceID,
			resourceInstallationID,
			resourceVolumeID,
			backupDestinationID,
			opts...)
		if err != nil {
			return nil, fmt.Errorf("failed to create resourcebackup %d: %w", i+1, err)
		}
		resourcebackups = append(resourcebackups, entity)
	}

	return resourcebackups, nil
}

func WithResourceBackupsTriggerType(value string) ResourceBackupOption {
	return func(f *ResourceBackupFactory) {
		f.ResourceBackupEntity.TriggerType = value
	}
}

func WithResourceBackupsStrategy(value string) ResourceBackupOption {
	return func(f *ResourceBackupFactory) {
		f.ResourceBackupEntity.Strategy = value
	}
}

func WithResourceBackupsDriver(value string) ResourceBackupOption {
	return func(f *ResourceBackupFactory) {
		f.ResourceBackupEntity.Driver = value
	}
}

func WithResourceBackupsFormat(value string) ResourceBackupOption {
	return func(f *ResourceBackupFactory) {
		f.ResourceBackupEntity.Format = value
	}
}

func WithResourceBackupsObjectKey(value string) ResourceBackupOption {
	return func(f *ResourceBackupFactory) {
		f.ResourceBackupEntity.ObjectKey = value
	}
}

func WithResourceBackupsStatus(value string) ResourceBackupOption {
	return func(f *ResourceBackupFactory) {
		f.ResourceBackupEntity.Status = value
	}
}

func WithResourceBackupsRequestedAt(value time.Time) ResourceBackupOption {
	return func(f *ResourceBackupFactory) {
		f.ResourceBackupEntity.RequestedAt = value
	}
}

func WithResourceBackupsStartedAt(value sql.NullTime) ResourceBackupOption {
	return func(f *ResourceBackupFactory) {
		f.ResourceBackupEntity.StartedAt = value
	}
}

func WithResourceBackupsFinishedAt(value sql.NullTime) ResourceBackupOption {
	return func(f *ResourceBackupFactory) {
		f.ResourceBackupEntity.FinishedAt = value
	}
}

func WithResourceBackupsSizeBytes(value sql.NullInt64) ResourceBackupOption {
	return func(f *ResourceBackupFactory) {
		f.ResourceBackupEntity.SizeBytes = value
	}
}

func WithResourceBackupsDigest(value []byte) ResourceBackupOption {
	return func(f *ResourceBackupFactory) {
		f.ResourceBackupEntity.Digest = value
	}
}

func WithResourceBackupsVerifiedAt(value sql.NullTime) ResourceBackupOption {
	return func(f *ResourceBackupFactory) {
		f.ResourceBackupEntity.VerifiedAt = value
	}
}

func WithResourceBackupsError(value sql.NullString) ResourceBackupOption {
	return func(f *ResourceBackupFactory) {
		f.ResourceBackupEntity.Error = value
	}
}

func WithResourceBackupsChangeID(value uuid.UUID) ResourceBackupOption {
	return func(f *ResourceBackupFactory) {
		f.ResourceBackupEntity.ChangeID = value
	}
}

func WithResourceBackupsChangeTaskID(value uuid.UUID) ResourceBackupOption {
	return func(f *ResourceBackupFactory) {
		f.ResourceBackupEntity.ChangeTaskID = value
	}
}

func WithResourceBackupsBackupPolicyID(value uuid.UUID) ResourceBackupOption {
	return func(f *ResourceBackupFactory) {
		f.ResourceBackupEntity.BackupPolicyID = value
	}
}

func WithResourceBackupsResourceID(value uuid.UUID) ResourceBackupOption {
	return func(f *ResourceBackupFactory) {
		f.ResourceBackupEntity.ResourceID = value
	}
}

func WithResourceBackupsEnvironmentResourceID(value *uuid.UUID) ResourceBackupOption {
	return func(f *ResourceBackupFactory) {
		f.ResourceBackupEntity.EnvironmentResourceID = value
	}
}

func WithResourceBackupsResourceInstallationID(value *uuid.UUID) ResourceBackupOption {
	return func(f *ResourceBackupFactory) {
		f.ResourceBackupEntity.ResourceInstallationID = value
	}
}

func WithResourceBackupsResourceVolumeID(value *uuid.UUID) ResourceBackupOption {
	return func(f *ResourceBackupFactory) {
		f.ResourceBackupEntity.ResourceVolumeID = value
	}
}

func WithResourceBackupsBackupDestinationID(value uuid.UUID) ResourceBackupOption {
	return func(f *ResourceBackupFactory) {
		f.ResourceBackupEntity.BackupDestinationID = value
	}
}
