package factories

import (
	"context"
	"database/sql"
	"deploycrate-ce/internal/storage"
	"deploycrate-ce/models"
	"fmt"
	"time"

	"github.com/go-faker/faker/v4"
	"github.com/google/uuid"
)

// Factory declarations below are generated by Andurel.

type ResourceVolumeMountFactory struct {
	models.ResourceVolumeMountEntity
}

type ResourceVolumeMountOption func(*ResourceVolumeMountFactory)

func BuildResourceVolumeMount(resourceVolumeID uuid.UUID, resourceInstallationID uuid.UUID, opts ...ResourceVolumeMountOption) models.ResourceVolumeMountEntity {
	f := &ResourceVolumeMountFactory{
		ResourceVolumeMountEntity: models.ResourceVolumeMountEntity{
			MountPath:              faker.Word(),
			ReadOnly:               randomBool(),
			ArchivedAt:             sql.NullTime{Time: time.Now(), Valid: true},
			ResourceVolumeID:       resourceVolumeID,
			ResourceInstallationID: resourceInstallationID,
		},
	}

	for _, opt := range opts {
		opt(f)
	}

	return f.ResourceVolumeMountEntity
}

func CreateResourceVolumeMount(ctx context.Context, exec storage.Executor, resourceVolumeID uuid.UUID, resourceInstallationID uuid.UUID, opts ...ResourceVolumeMountOption) (models.ResourceVolumeMountEntity, error) {
	built := BuildResourceVolumeMount(resourceVolumeID, resourceInstallationID, opts...)

	entity := models.ResourceVolumeMountEntity{
		ID:                     uuid.New(),
		CreatedAt:              time.Now(),
		UpdatedAt:              time.Now(),
		MountPath:              built.MountPath,
		ReadOnly:               built.ReadOnly,
		ArchivedAt:             built.ArchivedAt,
		ResourceVolumeID:       built.ResourceVolumeID,
		ResourceInstallationID: built.ResourceInstallationID,
	}

	if err := exec.NewInsert().Model(&entity).Returning("*").Scan(ctx); err != nil {
		return models.ResourceVolumeMountEntity{}, err
	}

	return entity, nil
}

func CreateResourceVolumeMounts(ctx context.Context, exec storage.Executor, resourceVolumeID uuid.UUID, resourceInstallationID uuid.UUID, count int, opts ...ResourceVolumeMountOption) ([]models.ResourceVolumeMountEntity, error) {
	resourcevolumemounts := make([]models.ResourceVolumeMountEntity, 0, count)

	for i := range count {
		entity, err := CreateResourceVolumeMount(ctx, exec, resourceVolumeID, resourceInstallationID, opts...)
		if err != nil {
			return nil, fmt.Errorf("failed to create resourcevolumemount %d: %w", i+1, err)
		}
		resourcevolumemounts = append(resourcevolumemounts, entity)
	}

	return resourcevolumemounts, nil
}

func WithResourceVolumeMountsMountPath(value string) ResourceVolumeMountOption {
	return func(f *ResourceVolumeMountFactory) {
		f.ResourceVolumeMountEntity.MountPath = value
	}
}

func WithResourceVolumeMountsReadOnly(value bool) ResourceVolumeMountOption {
	return func(f *ResourceVolumeMountFactory) {
		f.ResourceVolumeMountEntity.ReadOnly = value
	}
}

func WithResourceVolumeMountsArchivedAt(value sql.NullTime) ResourceVolumeMountOption {
	return func(f *ResourceVolumeMountFactory) {
		f.ResourceVolumeMountEntity.ArchivedAt = value
	}
}

func WithResourceVolumeMountsResourceVolumeID(value uuid.UUID) ResourceVolumeMountOption {
	return func(f *ResourceVolumeMountFactory) {
		f.ResourceVolumeMountEntity.ResourceVolumeID = value
	}
}

func WithResourceVolumeMountsResourceInstallationID(value uuid.UUID) ResourceVolumeMountOption {
	return func(f *ResourceVolumeMountFactory) {
		f.ResourceVolumeMountEntity.ResourceInstallationID = value
	}
}
