package factories

import (
	"context"
	"deploycrate-ce/internal/storage"
	"deploycrate-ce/models"
	"encoding/json"
	"fmt"
	"time"

	"github.com/go-faker/faker/v4"
	"github.com/google/uuid"
)

// Factory declarations below are generated by Andurel.

type RuntimeConfigurationFactory struct {
	models.RuntimeConfigurationEntity
}

type RuntimeConfigurationOption func(*RuntimeConfigurationFactory)

func BuildRuntimeConfiguration(environmentID uuid.UUID, opts ...RuntimeConfigurationOption) models.RuntimeConfigurationEntity {
	f := &RuntimeConfigurationFactory{
		RuntimeConfigurationEntity: models.RuntimeConfigurationEntity{
			Runtime:        faker.Word(),
			ResourceLimits: json.RawMessage{},
			RestartPolicy:  faker.Word(),
			Settings:       json.RawMessage{},
			EnvironmentID:  environmentID,
		},
	}

	for _, opt := range opts {
		opt(f)
	}

	return f.RuntimeConfigurationEntity
}

func CreateRuntimeConfiguration(ctx context.Context, exec storage.Executor, environmentID uuid.UUID, opts ...RuntimeConfigurationOption) (models.RuntimeConfigurationEntity, error) {
	built := BuildRuntimeConfiguration(environmentID, opts...)

	entity := models.RuntimeConfigurationEntity{
		ID:             built.ID,
		CreatedAt:      time.Now(),
		UpdatedAt:      time.Now(),
		Runtime:        built.Runtime,
		ResourceLimits: built.ResourceLimits,
		RestartPolicy:  built.RestartPolicy,
		Settings:       built.Settings,
		EnvironmentID:  built.EnvironmentID,
	}

	if err := exec.NewInsert().Model(&entity).Returning("*").Scan(ctx); err != nil {
		return models.RuntimeConfigurationEntity{}, err
	}

	return entity, nil
}

func CreateRuntimeConfigurations(ctx context.Context, exec storage.Executor, environmentID uuid.UUID, count int, opts ...RuntimeConfigurationOption) ([]models.RuntimeConfigurationEntity, error) {
	runtimeconfigurations := make([]models.RuntimeConfigurationEntity, 0, count)

	for i := range count {
		entity, err := CreateRuntimeConfiguration(ctx, exec, environmentID, opts...)
		if err != nil {
			return nil, fmt.Errorf("failed to create runtimeconfiguration %d: %w", i+1, err)
		}
		runtimeconfigurations = append(runtimeconfigurations, entity)
	}

	return runtimeconfigurations, nil
}

func WithRuntimeConfigurationsRuntime(value string) RuntimeConfigurationOption {
	return func(f *RuntimeConfigurationFactory) {
		f.RuntimeConfigurationEntity.Runtime = value
	}
}

func WithRuntimeConfigurationsResourceLimits(value json.RawMessage) RuntimeConfigurationOption {
	return func(f *RuntimeConfigurationFactory) {
		f.RuntimeConfigurationEntity.ResourceLimits = value
	}
}

func WithRuntimeConfigurationsRestartPolicy(value string) RuntimeConfigurationOption {
	return func(f *RuntimeConfigurationFactory) {
		f.RuntimeConfigurationEntity.RestartPolicy = value
	}
}

func WithRuntimeConfigurationsSettings(value json.RawMessage) RuntimeConfigurationOption {
	return func(f *RuntimeConfigurationFactory) {
		f.RuntimeConfigurationEntity.Settings = value
	}
}

func WithRuntimeConfigurationsEnvironmentID(value uuid.UUID) RuntimeConfigurationOption {
	return func(f *RuntimeConfigurationFactory) {
		f.RuntimeConfigurationEntity.EnvironmentID = value
	}
}
