package factories

import (
	"context"
	"database/sql"
	"deploycrate-ce/internal/storage"
	"deploycrate-ce/models"
	"encoding/json"
	"fmt"
	"time"

	"github.com/go-faker/faker/v4"
	"github.com/google/uuid"
)

// Factory declarations below are generated by Andurel.

type ServerFactory struct {
	models.ServerEntity
}

type ServerOption func(*ServerFactory)

func BuildServer(opts ...ServerOption) models.ServerEntity {
	f := &ServerFactory{
		ServerEntity: models.ServerEntity{
			ArchivedAt:          sql.NullTime{Time: time.Now(), Valid: true},
			Name:                faker.Word(),
			Slug:                faker.Word(),
			Kind:                faker.Word(),
			Capabilities:        json.RawMessage{},
			OperatingSystem:     sql.NullString{String: faker.Word(), Valid: true},
			Distribution:        sql.NullString{String: faker.Word(), Valid: true},
			DistributionVersion: sql.NullString{String: faker.Word(), Valid: true},
			Architecture:        sql.NullString{String: faker.Word(), Valid: true},
			PackageManager:      sql.NullString{String: faker.Word(), Valid: true},
			InitSystem:          sql.NullString{String: faker.Word(), Valid: true},
			Ipv4Address:         faker.Word(),
			Ipv6Address:         faker.Word(),
			IsConfigured:        randomBool(),
			Address:             faker.Word(),
		},
	}

	for _, opt := range opts {
		opt(f)
	}

	return f.ServerEntity
}

func CreateServer(
	ctx context.Context,
	exec storage.Executor,
	opts ...ServerOption,
) (models.ServerEntity, error) {
	built := BuildServer(opts...)

	entity := models.ServerEntity{
		ID:                  uuid.New(),
		CreatedAt:           time.Now(),
		UpdatedAt:           time.Now(),
		ArchivedAt:          built.ArchivedAt,
		Name:                built.Name,
		Slug:                built.Slug,
		Kind:                built.Kind,
		Capabilities:        built.Capabilities,
		OperatingSystem:     built.OperatingSystem,
		Distribution:        built.Distribution,
		DistributionVersion: built.DistributionVersion,
		Architecture:        built.Architecture,
		PackageManager:      built.PackageManager,
		InitSystem:          built.InitSystem,
		Ipv4Address:         built.Ipv4Address,
		Ipv6Address:         built.Ipv6Address,
		IsConfigured:        built.IsConfigured,
		Address:             built.Address,
	}

	if err := exec.NewInsert().Model(&entity).Returning("*").Scan(ctx); err != nil {
		return models.ServerEntity{}, err
	}

	return entity, nil
}

func CreateServers(
	ctx context.Context,
	exec storage.Executor,
	count int,
	opts ...ServerOption,
) ([]models.ServerEntity, error) {
	servers := make([]models.ServerEntity, 0, count)

	for i := range count {
		entity, err := CreateServer(ctx, exec, opts...)
		if err != nil {
			return nil, fmt.Errorf("failed to create server %d: %w", i+1, err)
		}
		servers = append(servers, entity)
	}

	return servers, nil
}

func WithServersArchivedAt(value sql.NullTime) ServerOption {
	return func(f *ServerFactory) {
		f.ServerEntity.ArchivedAt = value
	}
}

func WithServersName(value string) ServerOption {
	return func(f *ServerFactory) {
		f.ServerEntity.Name = value
	}
}

func WithServersSlug(value string) ServerOption {
	return func(f *ServerFactory) {
		f.ServerEntity.Slug = value
	}
}

func WithServersKind(value string) ServerOption {
	return func(f *ServerFactory) {
		f.ServerEntity.Kind = value
	}
}

func WithServersCapabilities(value json.RawMessage) ServerOption {
	return func(f *ServerFactory) {
		f.ServerEntity.Capabilities = value
	}
}

func WithServersOperatingSystem(value sql.NullString) ServerOption {
	return func(f *ServerFactory) {
		f.ServerEntity.OperatingSystem = value
	}
}

func WithServersDistribution(value sql.NullString) ServerOption {
	return func(f *ServerFactory) {
		f.ServerEntity.Distribution = value
	}
}

func WithServersDistributionVersion(value sql.NullString) ServerOption {
	return func(f *ServerFactory) {
		f.ServerEntity.DistributionVersion = value
	}
}

func WithServersArchitecture(value sql.NullString) ServerOption {
	return func(f *ServerFactory) {
		f.ServerEntity.Architecture = value
	}
}

func WithServersPackageManager(value sql.NullString) ServerOption {
	return func(f *ServerFactory) {
		f.ServerEntity.PackageManager = value
	}
}

func WithServersInitSystem(value sql.NullString) ServerOption {
	return func(f *ServerFactory) {
		f.ServerEntity.InitSystem = value
	}
}

func WithServersIpv4Address(value string) ServerOption {
	return func(f *ServerFactory) {
		f.ServerEntity.Ipv4Address = value
	}
}

func WithServersIpv6Address(value string) ServerOption {
	return func(f *ServerFactory) {
		f.ServerEntity.Ipv6Address = value
	}
}

func WithServersIsConfigured(value bool) ServerOption {
	return func(f *ServerFactory) {
		f.ServerEntity.IsConfigured = value
	}
}

func WithServersAddress(value string) ServerOption {
	return func(f *ServerFactory) {
		f.ServerEntity.Address = value
	}
}

func WithServersIPv4Address(value string) ServerOption {
	return WithServersIpv4Address(value)
}

func WithServersIPv6Address(value string) ServerOption {
	return WithServersIpv6Address(value)
}
