package factories

import (
	"context"
	"deploycrate-ce/internal/storage"
	"deploycrate-ce/models"
	"fmt"
	"time"

	"github.com/go-faker/faker/v4"
	"github.com/google/uuid"
)

// Factory declarations below are generated by Andurel.

type ServerStatusFactory struct {
	models.ServerStatusEntity
}

type ServerStatusOption func(*ServerStatusFactory)

func BuildServerStatus(serverID uuid.UUID, opts ...ServerStatusOption) models.ServerStatusEntity {
	f := &ServerStatusFactory{
		ServerStatusEntity: models.ServerStatusEntity{
			State:      faker.Word(),
			ObservedAt: time.Time{},
			ServerID:   serverID,
		},
	}

	for _, opt := range opts {
		opt(f)
	}

	return f.ServerStatusEntity
}

func CreateServerStatus(
	ctx context.Context,
	exec storage.Executor,
	serverID uuid.UUID,
	opts ...ServerStatusOption,
) (models.ServerStatusEntity, error) {
	built := BuildServerStatus(serverID, opts...)

	entity := models.ServerStatusEntity{
		ID:         built.ID,
		CreatedAt:  time.Now(),
		UpdatedAt:  time.Now(),
		State:      built.State,
		ObservedAt: built.ObservedAt,
		ServerID:   built.ServerID,
	}

	if err := exec.NewInsert().Model(&entity).Returning("*").Scan(ctx); err != nil {
		return models.ServerStatusEntity{}, err
	}

	return entity, nil
}

func CreateServerStatuss(
	ctx context.Context,
	exec storage.Executor,
	serverID uuid.UUID,
	count int,
	opts ...ServerStatusOption,
) ([]models.ServerStatusEntity, error) {
	serverstatuss := make([]models.ServerStatusEntity, 0, count)

	for i := range count {
		entity, err := CreateServerStatus(ctx, exec, serverID, opts...)
		if err != nil {
			return nil, fmt.Errorf("failed to create serverstatus %d: %w", i+1, err)
		}
		serverstatuss = append(serverstatuss, entity)
	}

	return serverstatuss, nil
}

func WithServerStatusesState(value string) ServerStatusOption {
	return func(f *ServerStatusFactory) {
		f.ServerStatusEntity.State = value
	}
}

func WithServerStatusesObservedAt(value time.Time) ServerStatusOption {
	return func(f *ServerStatusFactory) {
		f.ServerStatusEntity.ObservedAt = value
	}
}

func WithServerStatusesServerID(value uuid.UUID) ServerStatusOption {
	return func(f *ServerStatusFactory) {
		f.ServerStatusEntity.ServerID = value
	}
}
