package factories

import (
	"context"
	"database/sql"
	"deploycrate-ce/internal/storage"
	"deploycrate-ce/models"
	"fmt"
	"time"

	"github.com/go-faker/faker/v4"
	"github.com/google/uuid"
)

// Factory declarations below are generated by Andurel.

type ServerFactory struct {
	models.ServerEntity
}

type ServerOption func(*ServerFactory)

func BuildServer(opts ...ServerOption) models.ServerEntity {
	f := &ServerFactory{
		ServerEntity: models.ServerEntity{
			Name:       faker.Word(),
			Slug:       faker.Word(),
			Address:    faker.Word(),
			ArchivedAt: sql.NullTime{Time: time.Now(), Valid: true},
		},
	}

	for _, opt := range opts {
		opt(f)
	}

	return f.ServerEntity
}

func CreateServer(ctx context.Context, exec storage.Executor, opts ...ServerOption) (models.ServerEntity, error) {
	built := BuildServer(opts...)

	entity := models.ServerEntity{
		ID:         uuid.New(),
		CreatedAt:  time.Now(),
		UpdatedAt:  time.Now(),
		Name:       built.Name,
		Slug:       built.Slug,
		Address:    built.Address,
		ArchivedAt: built.ArchivedAt,
	}

	if err := exec.NewInsert().Model(&entity).Returning("*").Scan(ctx); err != nil {
		return models.ServerEntity{}, err
	}

	return entity, nil
}

func CreateServers(ctx context.Context, exec storage.Executor, count int, opts ...ServerOption) ([]models.ServerEntity, error) {
	servers := make([]models.ServerEntity, 0, count)

	for i := range count {
		entity, err := CreateServer(ctx, exec, opts...)
		if err != nil {
			return nil, fmt.Errorf("failed to create server %d: %w", i+1, err)
		}
		servers = append(servers, entity)
	}

	return servers, nil
}

func WithServersName(value string) ServerOption {
	return func(f *ServerFactory) {
		f.ServerEntity.Name = value
	}
}

func WithServersSlug(value string) ServerOption {
	return func(f *ServerFactory) {
		f.ServerEntity.Slug = value
	}
}

func WithServersAddress(value string) ServerOption {
	return func(f *ServerFactory) {
		f.ServerEntity.Address = value
	}
}

func WithServersArchivedAt(value sql.NullTime) ServerOption {
	return func(f *ServerFactory) {
		f.ServerEntity.ArchivedAt = value
	}
}
