package factories

import (
	"context"
	"database/sql"
	"deploycrate-ce/internal/storage"
	"deploycrate-ce/models"
	"encoding/json"
	"fmt"
	"time"

	"github.com/go-faker/faker/v4"
	"github.com/google/uuid"
)

// Factory declarations below are generated by Andurel.

type ServerNetworkFactory struct {
	models.ServerNetworkEntity
}

type ServerNetworkOption func(*ServerNetworkFactory)

func BuildServerNetwork(serverID uuid.UUID, privateNetworkID uuid.UUID, externalID sql.NullString, opts ...ServerNetworkOption) models.ServerNetworkEntity {
	f := &ServerNetworkFactory{
		ServerNetworkEntity: models.ServerNetworkEntity{
			ServerID:         serverID,
			PrivateNetworkID: privateNetworkID,
			Address:          faker.Word(),
			Driver:           faker.Word(),
			ExternalID:       externalID,
			Configuration:    json.RawMessage{},
			State:            faker.Word(),
			AppliedAt:        sql.NullTime{Time: time.Now(), Valid: true},
			ObservedAt:       sql.NullTime{Time: time.Now(), Valid: true},
			Error:            sql.NullString{String: faker.Word(), Valid: true},
			RemovedAt:        sql.NullTime{Time: time.Now(), Valid: true},
		},
	}

	for _, opt := range opts {
		opt(f)
	}

	return f.ServerNetworkEntity
}

func CreateServerNetwork(ctx context.Context, exec storage.Executor, serverID uuid.UUID, privateNetworkID uuid.UUID, externalID sql.NullString, opts ...ServerNetworkOption) (models.ServerNetworkEntity, error) {
	built := BuildServerNetwork(serverID, privateNetworkID, externalID, opts...)

	entity := models.ServerNetworkEntity{
		ID:               built.ID,
		CreatedAt:        time.Now(),
		UpdatedAt:        time.Now(),
		ServerID:         built.ServerID,
		PrivateNetworkID: built.PrivateNetworkID,
		Address:          built.Address,
		Driver:           built.Driver,
		ExternalID:       built.ExternalID,
		Configuration:    built.Configuration,
		State:            built.State,
		AppliedAt:        built.AppliedAt,
		ObservedAt:       built.ObservedAt,
		Error:            built.Error,
		RemovedAt:        built.RemovedAt,
	}

	if err := exec.NewInsert().Model(&entity).Returning("*").Scan(ctx); err != nil {
		return models.ServerNetworkEntity{}, err
	}

	return entity, nil
}

func CreateServerNetworks(ctx context.Context, exec storage.Executor, serverID uuid.UUID, privateNetworkID uuid.UUID, externalID sql.NullString, count int, opts ...ServerNetworkOption) ([]models.ServerNetworkEntity, error) {
	servernetworks := make([]models.ServerNetworkEntity, 0, count)

	for i := range count {
		entity, err := CreateServerNetwork(ctx, exec, serverID, privateNetworkID, externalID, opts...)
		if err != nil {
			return nil, fmt.Errorf("failed to create servernetwork %d: %w", i+1, err)
		}
		servernetworks = append(servernetworks, entity)
	}

	return servernetworks, nil
}

func WithServerNetworksServerID(value uuid.UUID) ServerNetworkOption {
	return func(f *ServerNetworkFactory) {
		f.ServerNetworkEntity.ServerID = value
	}
}

func WithServerNetworksPrivateNetworkID(value uuid.UUID) ServerNetworkOption {
	return func(f *ServerNetworkFactory) {
		f.ServerNetworkEntity.PrivateNetworkID = value
	}
}

func WithServerNetworksAddress(value string) ServerNetworkOption {
	return func(f *ServerNetworkFactory) {
		f.ServerNetworkEntity.Address = value
	}
}

func WithServerNetworksDriver(value string) ServerNetworkOption {
	return func(f *ServerNetworkFactory) {
		f.ServerNetworkEntity.Driver = value
	}
}

func WithServerNetworksExternalID(value sql.NullString) ServerNetworkOption {
	return func(f *ServerNetworkFactory) {
		f.ServerNetworkEntity.ExternalID = value
	}
}

func WithServerNetworksConfiguration(value json.RawMessage) ServerNetworkOption {
	return func(f *ServerNetworkFactory) {
		f.ServerNetworkEntity.Configuration = value
	}
}

func WithServerNetworksState(value string) ServerNetworkOption {
	return func(f *ServerNetworkFactory) {
		f.ServerNetworkEntity.State = value
	}
}

func WithServerNetworksAppliedAt(value sql.NullTime) ServerNetworkOption {
	return func(f *ServerNetworkFactory) {
		f.ServerNetworkEntity.AppliedAt = value
	}
}

func WithServerNetworksObservedAt(value sql.NullTime) ServerNetworkOption {
	return func(f *ServerNetworkFactory) {
		f.ServerNetworkEntity.ObservedAt = value
	}
}

func WithServerNetworksError(value sql.NullString) ServerNetworkOption {
	return func(f *ServerNetworkFactory) {
		f.ServerNetworkEntity.Error = value
	}
}

func WithServerNetworksRemovedAt(value sql.NullTime) ServerNetworkOption {
	return func(f *ServerNetworkFactory) {
		f.ServerNetworkEntity.RemovedAt = value
	}
}
