package factories

import (
	"context"
	"deploycrate-ce/internal/storage"
	"deploycrate-ce/models"
	"fmt"
	"time"

	"github.com/go-faker/faker/v4"
	"github.com/google/uuid"
)

// Factory declarations below are generated by Andurel.

type ServerSSHCredentialFactory struct {
	models.ServerSSHCredentialEntity
}

type ServerSSHCredentialOption func(*ServerSSHCredentialFactory)

func BuildServerSSHCredential(
	serverID uuid.UUID,
	opts ...ServerSSHCredentialOption,
) models.ServerSSHCredentialEntity {
	f := &ServerSSHCredentialFactory{
		ServerSSHCredentialEntity: models.ServerSSHCredentialEntity{
			Username:      faker.Word(),
			Port:          randomInt(1, 1000, 100),
			EncPrivateKey: []byte{},
			KnownHostKey:  faker.Word(),
			ServerID:      serverID,
		},
	}

	for _, opt := range opts {
		opt(f)
	}

	return f.ServerSSHCredentialEntity
}

func CreateServerSSHCredential(
	ctx context.Context,
	exec storage.Executor,
	serverID uuid.UUID,
	opts ...ServerSSHCredentialOption,
) (models.ServerSSHCredentialEntity, error) {
	built := BuildServerSSHCredential(serverID, opts...)

	entity := models.ServerSSHCredentialEntity{
		ID:            built.ID,
		CreatedAt:     time.Now(),
		UpdatedAt:     time.Now(),
		Username:      built.Username,
		Port:          built.Port,
		EncPrivateKey: built.EncPrivateKey,
		KnownHostKey:  built.KnownHostKey,
		ServerID:      built.ServerID,
	}

	if err := exec.NewInsert().Model(&entity).Returning("*").Scan(ctx); err != nil {
		return models.ServerSSHCredentialEntity{}, err
	}

	return entity, nil
}

func CreateServerSSHCredentials(
	ctx context.Context,
	exec storage.Executor,
	serverID uuid.UUID,
	count int,
	opts ...ServerSSHCredentialOption,
) ([]models.ServerSSHCredentialEntity, error) {
	serversshcredentials := make([]models.ServerSSHCredentialEntity, 0, count)

	for i := range count {
		entity, err := CreateServerSSHCredential(ctx, exec, serverID, opts...)
		if err != nil {
			return nil, fmt.Errorf("failed to create serversshcredential %d: %w", i+1, err)
		}
		serversshcredentials = append(serversshcredentials, entity)
	}

	return serversshcredentials, nil
}

func WithServerSshCredentialsUsername(value string) ServerSSHCredentialOption {
	return func(f *ServerSSHCredentialFactory) {
		f.ServerSSHCredentialEntity.Username = value
	}
}

func WithServerSshCredentialsPort(value int32) ServerSSHCredentialOption {
	return func(f *ServerSSHCredentialFactory) {
		f.ServerSSHCredentialEntity.Port = value
	}
}

func WithServerSshCredentialsEncPrivateKey(value []byte) ServerSSHCredentialOption {
	return func(f *ServerSSHCredentialFactory) {
		f.ServerSSHCredentialEntity.EncPrivateKey = value
	}
}

func WithServerSshCredentialsKnownHostKey(value string) ServerSSHCredentialOption {
	return func(f *ServerSSHCredentialFactory) {
		f.ServerSSHCredentialEntity.KnownHostKey = value
	}
}

func WithServerSshCredentialsServerID(value uuid.UUID) ServerSSHCredentialOption {
	return func(f *ServerSSHCredentialFactory) {
		f.ServerSSHCredentialEntity.ServerID = value
	}
}
