package factories

import (
	"context"
	"database/sql"
	"deploycrate-ce/internal/storage"
	"deploycrate-ce/models"
	"encoding/json"
	"fmt"
	"time"

	"github.com/go-faker/faker/v4"
	"github.com/google/uuid"
)

// Factory declarations below are generated by Andurel.

type SourceEventFactory struct {
	models.SourceEventEntity
}

type SourceEventOption func(*SourceEventFactory)

func BuildSourceEvent(environmentSourceID uuid.UUID, externalID string, opts ...SourceEventOption) models.SourceEventEntity {
	f := &SourceEventFactory{
		SourceEventEntity: models.SourceEventEntity{
			EnvironmentSourceID: environmentSourceID,
			ExternalID:          externalID,
			Kind:                faker.Word(),
			SourceRevision:      sql.NullString{String: faker.Word(), Valid: true},
			Payload:             json.RawMessage{},
			ReceivedAt:          time.Time{},
			ProcessedAt:         sql.NullTime{Time: time.Now(), Valid: true},
			Error:               sql.NullString{String: faker.Word(), Valid: true},
		},
	}

	for _, opt := range opts {
		opt(f)
	}

	return f.SourceEventEntity
}

func CreateSourceEvent(ctx context.Context, exec storage.Executor, environmentSourceID uuid.UUID, externalID string, opts ...SourceEventOption) (models.SourceEventEntity, error) {
	built := BuildSourceEvent(environmentSourceID, externalID, opts...)

	entity := models.SourceEventEntity{
		ID:                  uuid.New(),
		CreatedAt:           time.Now(),
		UpdatedAt:           time.Now(),
		EnvironmentSourceID: built.EnvironmentSourceID,
		ExternalID:          built.ExternalID,
		Kind:                built.Kind,
		SourceRevision:      built.SourceRevision,
		Payload:             built.Payload,
		ReceivedAt:          built.ReceivedAt,
		ProcessedAt:         built.ProcessedAt,
		Error:               built.Error,
	}

	if err := exec.NewInsert().Model(&entity).Returning("*").Scan(ctx); err != nil {
		return models.SourceEventEntity{}, err
	}

	return entity, nil
}

func CreateSourceEvents(ctx context.Context, exec storage.Executor, environmentSourceID uuid.UUID, externalID string, count int, opts ...SourceEventOption) ([]models.SourceEventEntity, error) {
	sourceevents := make([]models.SourceEventEntity, 0, count)

	for i := range count {
		entity, err := CreateSourceEvent(ctx, exec, environmentSourceID, externalID, opts...)
		if err != nil {
			return nil, fmt.Errorf("failed to create sourceevent %d: %w", i+1, err)
		}
		sourceevents = append(sourceevents, entity)
	}

	return sourceevents, nil
}

func WithSourceEventsEnvironmentSourceID(value uuid.UUID) SourceEventOption {
	return func(f *SourceEventFactory) {
		f.SourceEventEntity.EnvironmentSourceID = value
	}
}

func WithSourceEventsExternalID(value string) SourceEventOption {
	return func(f *SourceEventFactory) {
		f.SourceEventEntity.ExternalID = value
	}
}

func WithSourceEventsKind(value string) SourceEventOption {
	return func(f *SourceEventFactory) {
		f.SourceEventEntity.Kind = value
	}
}

func WithSourceEventsSourceRevision(value sql.NullString) SourceEventOption {
	return func(f *SourceEventFactory) {
		f.SourceEventEntity.SourceRevision = value
	}
}

func WithSourceEventsPayload(value json.RawMessage) SourceEventOption {
	return func(f *SourceEventFactory) {
		f.SourceEventEntity.Payload = value
	}
}

func WithSourceEventsReceivedAt(value time.Time) SourceEventOption {
	return func(f *SourceEventFactory) {
		f.SourceEventEntity.ReceivedAt = value
	}
}

func WithSourceEventsProcessedAt(value sql.NullTime) SourceEventOption {
	return func(f *SourceEventFactory) {
		f.SourceEventEntity.ProcessedAt = value
	}
}

func WithSourceEventsError(value sql.NullString) SourceEventOption {
	return func(f *SourceEventFactory) {
		f.SourceEventEntity.Error = value
	}
}
