package factories

import (
	"context"
	"database/sql"
	"deploycrate-ce/internal/storage"
	"deploycrate-ce/models"
	"fmt"
	"time"

	"github.com/go-faker/faker/v4"
	"github.com/google/uuid"
)

// Factory declarations below are generated by Andurel.

type WireGuardPeerFactory struct {
	models.WireGuardPeerEntity
}

type WireGuardPeerOption func(*WireGuardPeerFactory)

func BuildWireGuardPeer(
	serverID uuid.UUID,
	opts ...WireGuardPeerOption,
) models.WireGuardPeerEntity {
	f := &WireGuardPeerFactory{
		WireGuardPeerEntity: models.WireGuardPeerEntity{
			PublicKey:      faker.Word(),
			EncPrivateKey:  []byte{},
			PrivateAddress: faker.Word(),
			Endpoint:       sql.NullString{String: faker.Word(), Valid: true},
			ListenPort:     randomInt(1, 1000, 100),
			ActivatedAt:    time.Time{},
			RetiredAt:      sql.NullTime{Time: time.Now(), Valid: true},
			ServerID:       serverID,
		},
	}

	for _, opt := range opts {
		opt(f)
	}

	return f.WireGuardPeerEntity
}

func CreateWireGuardPeer(
	ctx context.Context,
	exec storage.Executor,
	serverID uuid.UUID,
	opts ...WireGuardPeerOption,
) (models.WireGuardPeerEntity, error) {
	built := BuildWireGuardPeer(serverID, opts...)

	entity := models.WireGuardPeerEntity{
		ID:             uuid.New(),
		CreatedAt:      time.Now(),
		UpdatedAt:      time.Now(),
		PublicKey:      built.PublicKey,
		EncPrivateKey:  built.EncPrivateKey,
		PrivateAddress: built.PrivateAddress,
		Endpoint:       built.Endpoint,
		ListenPort:     built.ListenPort,
		ActivatedAt:    built.ActivatedAt,
		RetiredAt:      built.RetiredAt,
		ServerID:       built.ServerID,
	}

	if err := exec.NewInsert().Model(&entity).Returning("*").Scan(ctx); err != nil {
		return models.WireGuardPeerEntity{}, err
	}

	return entity, nil
}

func CreateWireGuardPeers(
	ctx context.Context,
	exec storage.Executor,
	serverID uuid.UUID,
	count int,
	opts ...WireGuardPeerOption,
) ([]models.WireGuardPeerEntity, error) {
	wireguardpeers := make([]models.WireGuardPeerEntity, 0, count)

	for i := range count {
		entity, err := CreateWireGuardPeer(ctx, exec, serverID, opts...)
		if err != nil {
			return nil, fmt.Errorf("failed to create wireguardpeer %d: %w", i+1, err)
		}
		wireguardpeers = append(wireguardpeers, entity)
	}

	return wireguardpeers, nil
}

func WithWireguardPeersPublicKey(value string) WireGuardPeerOption {
	return func(f *WireGuardPeerFactory) {
		f.WireGuardPeerEntity.PublicKey = value
	}
}

func WithWireguardPeersEncPrivateKey(value []byte) WireGuardPeerOption {
	return func(f *WireGuardPeerFactory) {
		f.WireGuardPeerEntity.EncPrivateKey = value
	}
}

func WithWireguardPeersPrivateAddress(value string) WireGuardPeerOption {
	return func(f *WireGuardPeerFactory) {
		f.WireGuardPeerEntity.PrivateAddress = value
	}
}

func WithWireguardPeersEndpoint(value sql.NullString) WireGuardPeerOption {
	return func(f *WireGuardPeerFactory) {
		f.WireGuardPeerEntity.Endpoint = value
	}
}

func WithWireguardPeersListenPort(value int32) WireGuardPeerOption {
	return func(f *WireGuardPeerFactory) {
		f.WireGuardPeerEntity.ListenPort = value
	}
}

func WithWireguardPeersActivatedAt(value time.Time) WireGuardPeerOption {
	return func(f *WireGuardPeerFactory) {
		f.WireGuardPeerEntity.ActivatedAt = value
	}
}

func WithWireguardPeersRetiredAt(value sql.NullTime) WireGuardPeerOption {
	return func(f *WireGuardPeerFactory) {
		f.WireGuardPeerEntity.RetiredAt = value
	}
}

func WithWireguardPeersServerID(value uuid.UUID) WireGuardPeerOption {
	return func(f *WireGuardPeerFactory) {
		f.WireGuardPeerEntity.ServerID = value
	}
}
