package factories

import (
	"context"
	"database/sql"
	"deploycrate-ce/internal/storage"
	"deploycrate-ce/models"
	"fmt"
	"time"

	"github.com/go-faker/faker/v4"
	"github.com/google/uuid"
)

// Factory declarations below are generated by Andurel.

type WireGuardPeerStatusFactory struct {
	models.WireGuardPeerStatusEntity
}

type WireGuardPeerStatusOption func(*WireGuardPeerStatusFactory)

func BuildWireGuardPeerStatus(wireguardPeerID uuid.UUID, opts ...WireGuardPeerStatusOption) models.WireGuardPeerStatusEntity {
	f := &WireGuardPeerStatusFactory{
		WireGuardPeerStatusEntity: models.WireGuardPeerStatusEntity{
			WireguardPeerID:   wireguardPeerID,
			State:             faker.Word(),
			LatestHandshakeAt: sql.NullTime{Time: time.Now(), Valid: true},
			Error:             sql.NullString{String: faker.Word(), Valid: true},
			ObservedAt:        time.Time{},
		},
	}

	for _, opt := range opts {
		opt(f)
	}

	return f.WireGuardPeerStatusEntity
}

func CreateWireGuardPeerStatus(ctx context.Context, exec storage.Executor, wireguardPeerID uuid.UUID, opts ...WireGuardPeerStatusOption) (models.WireGuardPeerStatusEntity, error) {
	built := BuildWireGuardPeerStatus(wireguardPeerID, opts...)

	entity := models.WireGuardPeerStatusEntity{
		ID:                uuid.New(),
		CreatedAt:         time.Now(),
		UpdatedAt:         time.Now(),
		WireguardPeerID:   built.WireguardPeerID,
		State:             built.State,
		LatestHandshakeAt: built.LatestHandshakeAt,
		Error:             built.Error,
		ObservedAt:        built.ObservedAt,
	}

	if err := exec.NewInsert().Model(&entity).Returning("*").Scan(ctx); err != nil {
		return models.WireGuardPeerStatusEntity{}, err
	}

	return entity, nil
}

func CreateWireGuardPeerStatuses(ctx context.Context, exec storage.Executor, wireguardPeerID uuid.UUID, count int, opts ...WireGuardPeerStatusOption) ([]models.WireGuardPeerStatusEntity, error) {
	wireGuardPeerStatuses := make([]models.WireGuardPeerStatusEntity, 0, count)

	for i := range count {
		entity, err := CreateWireGuardPeerStatus(ctx, exec, wireguardPeerID, opts...)
		if err != nil {
			return nil, fmt.Errorf("failed to create wireguardpeerstatus %d: %w", i+1, err)
		}
		wireGuardPeerStatuses = append(wireGuardPeerStatuses, entity)
	}

	return wireGuardPeerStatuses, nil
}

func WithWireguardPeerStatusesWireguardPeerID(value uuid.UUID) WireGuardPeerStatusOption {
	return func(f *WireGuardPeerStatusFactory) {
		f.WireGuardPeerStatusEntity.WireguardPeerID = value
	}
}

func WithWireguardPeerStatusesState(value string) WireGuardPeerStatusOption {
	return func(f *WireGuardPeerStatusFactory) {
		f.WireGuardPeerStatusEntity.State = value
	}
}

func WithWireguardPeerStatusesLatestHandshakeAt(value sql.NullTime) WireGuardPeerStatusOption {
	return func(f *WireGuardPeerStatusFactory) {
		f.WireGuardPeerStatusEntity.LatestHandshakeAt = value
	}
}

func WithWireguardPeerStatusesError(value sql.NullString) WireGuardPeerStatusOption {
	return func(f *WireGuardPeerStatusFactory) {
		f.WireGuardPeerStatusEntity.Error = value
	}
}

func WithWireguardPeerStatusesObservedAt(value time.Time) WireGuardPeerStatusOption {
	return func(f *WireGuardPeerStatusFactory) {
		f.WireGuardPeerStatusEntity.ObservedAt = value
	}
}
