// Package models contains data models and validation logic.
package models

type (
	user                            struct{}
	token                           struct{}
	credential                      struct{}
	application                     struct{}
	server                          struct{}
	serverStatus                    struct{}
	environment                     struct{}
	environmentSource               struct{}
	environmentBuildConfiguration   struct{}
	environmentRuntimeConfiguration struct{}
	environmentSecret               struct{}
	environmentTarget               struct{}
	privateNetwork                  struct{}
	environmentNetwork              struct{}
	serverNetwork                   struct{}
	environmentTargetNetwork        struct{}
	resource                        struct{}
	resourceInstallation            struct{}
	resourceInstallationStatus      struct{}
	resourceEndpoint                struct{}
	resourceCredential              struct{}
	environmentDependency           struct{}
	resourceBinding                 struct{}
	resourceBindingCredential       struct{}
	environmentDomain               struct{}
	environmentHealthCheck          struct{}
	sourceEvent                     struct{}
	change                          struct{}
	changeItem                      struct{}
	changeTask                      struct{}
	changeTaskAttempt               struct{}
	changeLog                       struct{}
	build                           struct{}
	release                         struct{}
	deployment                      struct{}
	deploymentEvent                 struct{}
	instance                        struct{}
	caddyRoute                      struct{}
	caddyRouteBackend               struct{}
	backupDestination               struct{}
	backupPolicy                    struct{}
	resourceBackup                  struct{}
	resourceRestore                 struct{}
	outboxEvent                     struct{}
	environmentStateRevision        struct{}
	environmentTargetState          struct{}
	networkAccessRule               struct{}
	networkAccessRuleApplication    struct{}
	environmentHealthCheckStatus    struct{}
	changeRelease                   struct{}
	changeStateRevision             struct{}
	serverSSHCredential             struct{}
	wireGuardPeer                   struct{}
	wireGuardPeerStatus             struct{}
)

var (
	User                            user
	Token                           token
	Credential                      credential
	Application                     application
	Server                          server
	ServerStatus                    serverStatus
	Environment                     environment
	EnvironmentSource               environmentSource
	EnvironmentBuildConfiguration   environmentBuildConfiguration
	EnvironmentRuntimeConfiguration environmentRuntimeConfiguration
	EnvironmentSecret               environmentSecret
	EnvironmentTarget               environmentTarget
	PrivateNetwork                  privateNetwork
	EnvironmentNetwork              environmentNetwork
	ServerNetwork                   serverNetwork
	EnvironmentTargetNetwork        environmentTargetNetwork
	Resource                        resource
	ResourceInstallation            resourceInstallation
	ResourceInstallationStatus      resourceInstallationStatus
	ResourceEndpoint                resourceEndpoint
	ResourceCredential              resourceCredential
	EnvironmentDependency           environmentDependency
	ResourceBinding                 resourceBinding
	ResourceBindingCredential       resourceBindingCredential
	EnvironmentDomain               environmentDomain
	EnvironmentHealthCheck          environmentHealthCheck
	SourceEvent                     sourceEvent
	Change                          change
	ChangeItem                      changeItem
	ChangeTask                      changeTask
	ChangeTaskAttempt               changeTaskAttempt
	ChangeLog                       changeLog
	Build                           build
	Release                         release
	Deployment                      deployment
	DeploymentEvent                 deploymentEvent
	Instance                        instance
	CaddyRoute                      caddyRoute
	CaddyRouteBackend               caddyRouteBackend
	BackupDestination               backupDestination
	BackupPolicy                    backupPolicy
	ResourceBackup                  resourceBackup
	ResourceRestore                 resourceRestore
	OutboxEvent                     outboxEvent
	EnvironmentStateRevision        environmentStateRevision
	EnvironmentTargetState          environmentTargetState
	NetworkAccessRule               networkAccessRule
	NetworkAccessRuleApplication    networkAccessRuleApplication
	EnvironmentHealthCheckStatus    environmentHealthCheckStatus
	ChangeRelease                   changeRelease
	ChangeStateRevision             changeStateRevision
	ServerSSHCredential             serverSSHCredential
	WireGuardPeer                   wireGuardPeer
	WireGuardPeerStatus             wireGuardPeerStatus
)
