// Package models contains data models and validation logic.
package models

type (
	user                         struct{}
	token                        struct{}
	credential                   struct{}
	dnsConnection                struct{}
	dnsZone                      struct{}
	application                  struct{}
	server                       struct{}
	serverSSHCredential          struct{}
	serverStatus                 struct{}
	nodeEnrollment               struct{}
	wireGuardPeer                struct{}
	wireGuardPeerStatus          struct{}
	wireGuardDevice              struct{}
	wireGuardDeviceResourceGrant struct{}
	wireGuardGrantApplication    struct{}
	wireGuardDeviceStatus        struct{}
	environment                  struct{}
	registryResource             struct{}
	environmentSource            struct{}
	imageConfiguration           struct{}
	buildpackConfiguration       struct{}
	runtimeConfiguration         struct{}
	environmentSecret            struct{}
	environmentTarget            struct{}
	privateNetwork               struct{}
	environmentNetwork           struct{}
	serverNetwork                struct{}
	environmentTargetNetwork     struct{}
	resource                     struct{}
	resourceInstallation         struct{}
	resourceInstallationStatus   struct{}
	resourceEndpoint             struct{}
	resourceDNSBinding           struct{}
	resourceDNSRecord            struct{}
	resourceCredential           struct{}
	environmentResource          struct{}
	resourceVolume               struct{}
	resourceVolumeMount          struct{}
	environmentDomain            struct{}
	environmentDNSBinding        struct{}
	environmentDNSRecord         struct{}
	environmentHealthCheck       struct{}
	sourceEvent                  struct{}
	change                       struct{}
	changeItem                   struct{}
	changeTask                   struct{}
	changeTaskAttempt            struct{}
	changeLog                    struct{}
	build                        struct{}
	buildLog                     struct{}
	environmentProcess           struct{}
	releaseCommandExecution      struct{}
	releaseCommandLog            struct{}
	job                          struct{}
	release                      struct{}
	deployment                   struct{}
	deploymentEvent              struct{}
	instance                     struct{}
	caddyRoute                   struct{}
	caddyRouteBackend            struct{}
	customCaddyRoute             struct{}
	backupDestination            struct{}
	backupPolicy                 struct{}
	backup                       struct{}
	resourceRestore              struct{}
	outboxEvent                  struct{}
	environmentStateRevision     struct{}
	environmentTargetState       struct{}
	networkAccessRule            struct{}
	networkAccessRuleApplication struct{}
	environmentHealthCheckStatus struct{}
	changeRelease                struct{}
	changeStateRevision          struct{}
	resourceHealthCheck          struct{}
	resourceHealthCheckStatus    struct{}
	wireGuardAddress             struct{}
	dashboard                    struct{}
)

var (
	User                         user
	Token                        token
	Credential                   credential
	DNSConnection                dnsConnection
	DNSZone                      dnsZone
	Application                  application
	Server                       server
	ServerSSHCredential          serverSSHCredential
	ServerStatus                 serverStatus
	NodeEnrollment               nodeEnrollment
	WireGuardPeer                wireGuardPeer
	WireGuardPeerStatus          wireGuardPeerStatus
	WireGuardDevice              wireGuardDevice
	WireGuardDeviceResourceGrant wireGuardDeviceResourceGrant
	WireGuardGrantApplication    wireGuardGrantApplication
	WireGuardDeviceStatus        wireGuardDeviceStatus
	Environment                  environment
	RegistryResource             registryResource
	EnvironmentSource            environmentSource
	ImageConfiguration           imageConfiguration
	BuildpackConfiguration       buildpackConfiguration
	RuntimeConfiguration         runtimeConfiguration
	EnvironmentSecret            environmentSecret
	EnvironmentTarget            environmentTarget
	PrivateNetwork               privateNetwork
	EnvironmentNetwork           environmentNetwork
	ServerNetwork                serverNetwork
	EnvironmentTargetNetwork     environmentTargetNetwork
	Resource                     resource
	ResourceInstallation         resourceInstallation
	ResourceInstallationStatus   resourceInstallationStatus
	ResourceEndpoint             resourceEndpoint
	ResourceDNSBinding           resourceDNSBinding
	ResourceDNSRecord            resourceDNSRecord
	ResourceCredential           resourceCredential
	EnvironmentResource          environmentResource
	ResourceVolume               resourceVolume
	ResourceVolumeMount          resourceVolumeMount
	EnvironmentDomain            environmentDomain
	EnvironmentDNSBinding        environmentDNSBinding
	EnvironmentDNSRecord         environmentDNSRecord
	EnvironmentHealthCheck       environmentHealthCheck
	SourceEvent                  sourceEvent
	Change                       change
	ChangeItem                   changeItem
	ChangeTask                   changeTask
	ChangeTaskAttempt            changeTaskAttempt
	ChangeLog                    changeLog
	Build                        build
	BuildLog                     buildLog
	EnvironmentProcess           environmentProcess
	ReleaseCommandExecution      releaseCommandExecution
	ReleaseCommandLog            releaseCommandLog
	Job                          job
	Release                      release
	Deployment                   deployment
	DeploymentEvent              deploymentEvent
	Instance                     instance
	CaddyRoute                   caddyRoute
	CaddyRouteBackend            caddyRouteBackend
	CustomCaddyRoute             customCaddyRoute
	BackupDestination            backupDestination
	BackupPolicy                 backupPolicy
	Backup                       backup
	ResourceRestore              resourceRestore
	OutboxEvent                  outboxEvent
	EnvironmentStateRevision     environmentStateRevision
	EnvironmentTargetState       environmentTargetState
	NetworkAccessRule            networkAccessRule
	NetworkAccessRuleApplication networkAccessRuleApplication
	EnvironmentHealthCheckStatus environmentHealthCheckStatus
	ChangeRelease                changeRelease
	ChangeStateRevision          changeStateRevision
	ResourceHealthCheck          resourceHealthCheck
	ResourceHealthCheckStatus    resourceHealthCheckStatus
	WireGuardAddress             wireGuardAddress
	Dashboard                    dashboard
)
